var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,c){a.raw=c;return a};var glob=glob||{namespace:"recr",ga_event_category:"\uacf5\uac1c\ubaa8\uc9d1 \uacc4\uc0b0\uae30"};window[glob.namespace]=window[glob.namespace]||{};
window[glob.namespace].getCheckedTagIDs=function(){for(var a=[],c=$(getCheckboxList()),e=0,h=0;e<c.length;++e)c.eq(e).prop("checked")&&(a[h++]=c.eq(e).attr("id").split("_")[1]);return a};
window[glob.namespace].showResult=function(){var a=getCheckedTagIDs(),c=calc(a);0>=a.length?$("#result-panel-footer-btn").html(""):($("#result-panel-footer-btn").html('<button onclick="clearSelection()">\ud0dc\uadf8 \ucd08\uae30\ud654</button> <input onclick="filterClicked(\'onlyHighStars\')" type="checkbox" id="result-panel-footer-ohsf" class="checkboxButton"><label class="button" for="result-panel-footer-ohsf"><span>\uace0\ub4f1\uae09 \ud655\uc815\uc2dd\ub9cc</span></label><div><br></div>'),syncButtons());
if(0==c.length)return $("#result-panel .panel:not(.guide-panel, .advertise)").remove(),!1===userConfig.display.guidePanel.value&&$("#result-panel").prepend('<div class="panel"></div>'),!1;a=new String;for(var e=0;e<c.length;++e){var h=c[e].lowestRarity;if(!(1==userConfig.filter.onlyHighRarity.value&&3>=h)){var g=c[e].opIDs,f=getTagNames(c[e].tagCode),l="",k="";l+='<div style="margin-bottom: 0.4em" data-lang="'+userConfig.locale.region.value+'">';for(var b=0;b<f.length;++b)l+='<span class="tag result-tag">'+
f[b]+"</span> ";l+="</div>";var d=0;for(b=0;b<g.length;++b)if(f=db.op[g[b]].rarity,!(0>userConfig.filter.rarity.value.indexOf(f))){0!=d&&d!=f&&(k+="<br>");var m=d="",t="",n="",p="",u="",q="";d=0<="tiny|small|medium|large".indexOf(userConfig.display.image.value)?d+('<div id="op_'+String(g[b])+'" class="tag result-op rarity_'+String(f)+'">'):d+('<div id="op_'+String(g[b])+'" class="tag result-op no-img rarity_'+String(f)+'">');q+="</div>";0<="tiny|small|medium|large".indexOf(userConfig.display.image.value)&&
(m+='<img class="result_op_thumb ',m+=userConfig.display.image.value,m+='" src="./images/op/thumb/'+db.op[g[b]].releaseOrder+'.png"> ');if(userConfig.display.name.value||userConfig.display.rarity.value){var r="result_op_text "+userConfig.display.image.value;userConfig.display.name.value&&!userConfig.display.rarity.value&&(r+=" only-name");!userConfig.display.name.value&&userConfig.display.rarity.value&&(r+=" only-rarity");t+='<div class="'+r+'">';u+="</div>"}userConfig.display.name.value&&(n+="<span>"+
db.op[g[b]].name[userConfig.locale.lang.value]+"</span> ",0<="tiny|small|large".indexOf(userConfig.display.image.value)?n+="<br>":0<="medium".indexOf(userConfig.display.image.value)&&(n+="<br>"));userConfig.display.rarity.value?(p+=' <span id="op_'+String(g[b])+'" class="star rarity_'+String(f)+'">',p+=" \u2605"+String(f),p+="</span><br>"):userConfig.display.name.value&&"small|medium".indexOf(userConfig.display.image.value);d="large"===userConfig.display.image.value?d+'<div style="display:flex; flex-direction: column">':
d+'<div style="display:flex; justify-content:space-between">';q+="</div>";k+=d+m+t+n+p+u+q;d=f}""===k&&(k='<span id="op_-1" class="tag result-op no-img">\ud544\ud130\ub9c1 \uc870\uac74\uc5d0 \ub9de\ub294 \uacb0\uacfc \uc5c6\uc74c</span>');a=userConfig.display.name.value||userConfig.display.rarity.value?a+('<div class="panel rarity_'+String(h)+'">'):a+('<div class="panel rarity_'+String(h)+' only-image">');a+=l+'<div style="display:inline-block" data-lang="'+userConfig.locale.lang.value+'">'+k+"</div>";
a+="</div>"}}""==a&&(a='<div class="panel"><span class="tag result-tag">\uacb0\uacfc \uc5c6\uc74c</span><br><span id="op_-1" class="tag result-op no-img">\ud544\ud130\ub9c1 \uc870\uac74\uc5d0 \ub9de\ub294 \uacb0\uacfc \uc5c6\uc74c</span></div>');$("#result-panel .panel:not(.guide-panel, .advertise)").remove();$("#result-panel").prepend(a)};
