var gtag_searchByNameUsed=!1,gtag_searchByRarityUsed=!1;gtag_searchByClassUsed=!1;
const openModalPrompt=function(){gtag("event","\ub300\uc6d0 \ucd94\uac00 \ud504\ub86c\ud504\ud2b8 \uc5f4\uae30",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"});var b=document.querySelector(".modal");b.style.display="block";b.style.opacity="1";doNotRefreshResult=!0;showSearchResult()},closeModalPrompt=function(){var b=document.querySelector(".modal");b.style.opacity="0";setTimeout(function(){b.style.display="none"},300);doNotRefreshResult=!1;showResult()};
var getAllIDs=function(b){b=b.split("-")[0];for(var c=[],d=0;d<db.op.keys.length;++d)db.op.keys[d]===b?c.push(db.op.keys[d]):0===db.op.keys[d].indexOf(b+"-")&&c.push(db.op.keys[d]);c.sort(function(k,a){k=k.split("-");a=a.split("-");1===k.length&&k.push(0);1===a.length&&a.push(0);return k[0]<a[0]?-1:k[0]>a[0]?1:Number(k[1])<Number(a[1])?-1:1});return c},main=function(){document.querySelector(".add-btn").addEventListener("click",function(){openModalPrompt()});document.querySelector(".close-btn").addEventListener("click",
function(){gtag("event","\ub300\uc6d0 \ucd94\uac00 \ud504\ub86c\ud504\ud2b8 \ub2eb\uae30: \ubc84\ud2bc \ud074\ub9ad",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"});closeModalPrompt(!0)});window.addEventListener("mousedown",function(b){"modal"===b.target.getAttribute("id")&&(gtag("event","\ub300\uc6d0 \ucd94\uac00 \ud504\ub86c\ud504\ud2b8 \ub2eb\uae30: \uc678\ubd80 \ud074\ub9ad",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"}),
closeModalPrompt(!0))});document.getElementById("opname").addEventListener("keyup",function(b){gtag_searchByNameUsed||(gtag_searchByNameUsed=!0,gtag("event","\ub300\uc6d0 \uc774\ub984\uc73c\ub85c \ucd5c\ucd08 \uac80\uc0c9",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"}));if(13===b.keyCode){for(;0<document.querySelectorAll(".search-result-op").length;)document.querySelector(".search-result-op").click();this.value="";searchingCondition.name=""}else{b=
"";for(var c=this.value.split(" "),d=0,k=c.length;d<k;++d)0!==c[d].length&&(0<d&&(b+=" "),b+=c[d][0].toUpperCase()+c[d].slice(1).toLowerCase());searchingCondition.name=b;showSearchResult()}});document.querySelectorAll(".rarity-btn").forEach(function(b){b.addEventListener("click",function(){gtag_searchByRarityUsed||(gtag_searchByRarityUsed=!0,gtag("event","\ub300\uc6d0 \ub808\uc5b4\ub3c4\ub85c \ucd5c\ucd08 \uac80\uc0c9",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"}));
var c=Number(this.getAttribute("name")),d=searchingCondition.rarityArray.indexOf(c);0<=d?(searchingCondition.rarityArray.splice(d,1),this.classList.remove("selected")):(searchingCondition.rarityArray.push(c),this.classList.add("selected"));showSearchResult()})});document.querySelectorAll(".class-btn").forEach(function(b){b.addEventListener("click",function(){gtag_searchByClassUsed||(gtag_searchByClassUsed=!0,gtag("event","\ub300\uc6d0 \ud074\ub798\uc2a4\ub85c \ucd5c\ucd08 \uac80\uc0c9",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"}));
var c=getTagCodeByKRTagName(this.getAttribute("name"));c&searchingCondition.tagCode?this.classList.remove("selected"):this.classList.add("selected");searchingCondition.tagCode^=c;showSearchResult()})});loadLocalStorage()},getTextWidth=function(b){var c="font-size:"+b.css("font-size")+";";c+="font-family:"+b.css("font-family")+";";b=$('<span style="'+c+'">'+b.html()+"</span>").appendTo("body");c=b.width();b.remove();return c},centerCnt=0,centerCacheHit=0,centerCache={},csp=[],ncsp=[],centerTime=0,
doNotCenter=!1,centerSelect=function(b){if(!doNotCenter){centerTime=Date.now();var c=b.options[b.selectedIndex].innerText,d=centerCache[c];d?(b.style.textIndent=d,csp.push(Date.now()-centerTime)):(d=$(b),b=getTextWidth($(b.options[b.selectedIndex])),b=(d.width()-b)/2,d.css("text-indent",b),centerCache[c]=b+"px",ncsp.push(Date.now()-centerTime))}};
const makeOpForm=function(b,c={}){var d={},k=!0;c||={};"object"===typeof c.values&&(d=c.values);"boolean"===typeof c.asElement&&(k=c.asElement);var a=Number(db.op[b].rarity),r=[0,0,1,2,2,2][a-1],g=getMaxLevel(r,a),n=[4,7,7][r];c=getMaxModuleLevel(b);getNumOfModules(b);db.op[b].name.en.toLowerCase();var f=Number.isInteger(d["current-elite"])?d["current-elite"]:0,p=Number.isInteger(d["target-elite"])?d["target-elite"]:r,h=Number.isInteger(d["current-op-level"])?d["current-op-level"]:1,u=Number.isInteger(d["target-op-level"])?
d["target-op-level"]:g,t=[];if(d["current-skill-level"]){d["current-skill-level"].forEach(function(B){t.push(1<=B&&10>=B?B:1)});var m=0;for(g=3-t.length;m<g;++m)t.push(1)}else t=[1,1,1];var z=[];if(d["target-skill-level"])for(d["target-skill-level"].forEach(function(B){z.push(1<=B&&10>=B?B:n)}),m=0,g=3-z.length;m<g;++m)z.push(n);else z=[n,n,n];g=null!==db.op[b].module;if(d=d.module&&0<Object.keys(d.module).length?d.module:null)for(var l in d){m=d[l][0];if(0>m||m>c)d[l][0]=0;m=d[l][1];if(0>m||m>c)d[l][0]=
c}l=`<div class="remove-op thumb rarity_${a}"><button class="no-margin square caution button remove-btn">\uc81c\uac70</button><img alt=${db.op[b].releaseOrder} src="./images/op/thumb/${db.op[b].releaseOrder}.png">`;l+='</div><div class="elite"><span class="category">\uc815\uc608\ud654</span><br><select class="current-elite">';for(m=0;m<=r;++m)l+=`<option value="${m}"`,m===f&&(l+=" selected"),l+=`>${m}\ub2e8\uacc4</option>`;l+='</select><span> \u25b8 </span><select class="target-elite">';for(m=0;m<=
r;++m)l+=`<option value="${m}"`,m===p&&(l+=" selected"),l+=`>${m}\ub2e8\uacc4</option>`;l=l+'</select></div><div class="opLevel"><hr><button type="button" class="set-current-op-level-to-max-btn">MAX</button><span class="category"> \ub808\ubca8 </span><button type="button" class="set-target-op-level-to-max-btn">MAX</button><br>'+`<input type="text" class="current-op-level" value="${h}">`+"<span> \u25b8 </span>"+`<input type="text" class="target-op-level" value="${u}"></div><hr>`;r=getNumOfSkills(b);
if(0<r){l+='<span class="category">\uc2a4\ud0ac \ub808\ubca8</span><br>';l+='<div class="skill">';for(m=1;m<=r;++m){1<m&&(l+="<br>");l+=`<span>${m}\uc2a4\ud0ac </span>`;l+=`<select class="current-skill-level" data-index="${m-1}">`;for(f=1;10>=f;++f)l+=`<option value="${f}"`,f===t[m-1]&&(l+="selected"),l+=`>${f}</option>`;l+="</select>";l+="<span> \u25b8 </span>";l+=`<select class="target-skill-level" data-index="${m-1}">`;for(f=1;10>=f;++f)l+=`<option value="${f}"`,f===z[m-1]&&(l+="selected"),l+=
`>${f}</option>`;l+="</select>"}l+="</div>"}if(g){d||={};l+='<hr><span class="category">\uac15\ud654 \ubaa8\ub4c8</span><br>';l+='<div class="module">';r=Object.keys(db.op[b].module).sort();for(f=0;f<r.length;++f){p=r[f];d[p]||(d[p]=[0,c]);1<f&&(l+="<br>");l+=`<span>${p} </span>`;l+=`<select class="current-module-level" data-module-code="${p}">`;for(h=0;h<=c;++h)l+=`<option value="${h}"`,h===d[p][0]&&(l+="selected"),l+=`>${h}</option>`;l+="</select>";l+="<span> \u25b8 </span>";l+=`<select class="target-module-level" data-module-code="${p}">`;
for(h=0;h<=c;++h)l+=`<option value="${h}"`,h===d[p][1]&&(l+="selected"),l+=`>${h}</option>`;l+="</select>"}l+="</div>"}l+="</div>";return k?(k=document.createElement("div"),k.classList.add("op"),k.setAttribute("name",`op_${b}`),k.innerHTML=l,k):`<div class="op" name="op_${b}">`+l+"</div>"};
var convertOldIDToNewID=function(){gtag("event","ID \uccb4\uacc4 \uc804\ud658(\ubc84\uc804 1\uc5d0\uc11c 2\ub85c)",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"});var b={0:"LN02",1:"RL03",2:"LT77",3:"RE41",4:"LM04",5:"AZ01",6:"JC01",7:"AA01",8:"FO03",9:"FO01",10:"PL03",11:"SS02",12:"LM20",13:"SR02",14:"RL06",15:"LM05",16:"NM01",17:"RL02",18:"GG01",19:"R001",20:"VC03",21:"SK01",22:"RR01",23:"SR27",24:"R137",25:"BS01",26:"GG03",27:"SR01",28:"RB01",29:"AA02",
30:"LM08",31:"R132",32:"SS01",33:"RL04",34:"RL01",35:"R106",36:"AA03",37:"LT01",38:"ST01",39:"R110",40:"ST03",41:"KZ03",42:"SR03",43:"JC06",44:"YD01",45:"SG01",46:"SW01",47:"LM16",48:"LM12",49:"R130",50:"R128",51:"RL05",52:"JC05",53:"PL05",54:"USS2",55:"LM15",56:"PL04",57:"LM19",58:"BS02",59:"FO02",60:"MN02",61:"VC05",62:"HT03",63:"PL02",64:"USS1",65:"SI01",66:"R119",67:"VC02",68:"US10",69:"R100",70:"IU04",71:"R123",72:"HK01",73:"VC04",74:"IU07",75:"R104",76:"MN03",77:"R107",78:"LT02",79:"BS03",80:"VC01",
81:"ST02",82:"LM10",83:"R122",84:"KZ04",85:"RB02",86:"LM11",87:"AA04",88:"LN01",89:"IU05",90:"R124",91:"JC03",92:"USS3",93:"JC04",94:"R108",95:"SW02",96:"R105",97:"PA15",98:"PA42",99:"PA41",100:"PA62",101:"PA65",102:"PA43",103:"PA13",104:"PA44",105:"PA63",106:"PA12",107:"PA61",108:"PA14",109:"PA45",110:"PA64",111:"PA11",112:"LT05",113:"BS04",114:"R303",115:"A44",116:"A43",117:"A41",118:"A42",119:"RCX3",120:"RCX2"},c=Object.keys(localStorage).filter(n=>0<=n.indexOf("optotal_")),d="",k="",a="";d="";
for(var r=0,g=c.length;r<g;++r)a=c[r].split("_"),d=a[1],a[1]=b[d],a[1]?(a=a.join("_"),k=c[r],d=localStorage.getItem(k),localStorage.setItem(a,d),localStorage.removeItem(k)):console.error(d+": \uc624\ud37c\ub808\uc774\ud130 ID \uccb4\uacc4 \ucd5c\uc2e0\ud654 \uc2e4\ud328. \ub9e4\uce6d\ub418\ub294 ID\uac00 \uc874\uc7ac\ud558\uc9c0 \uc54a\uc74c.");localStorage.setItem("version_optotal_localStorage",JSON.stringify(db.idVersion.op))};
const sleep=function(b){return new Promise((c,d)=>{setTimeout(c,b)})},loadLocalStorage=function(){console.log("loadLocalStorage");JSON.parse(localStorage.getItem("version_optotal_localStorage")||"1")<db.idVersion.op&&(console.log("\uc624\ud37c\ub808\uc774\ud130 ID \uccb4\uacc4 \ucd5c\uc2e0\ud654 \uc218\ud589"),convertOldIDToNewID());for(var b="current-elite target-elite current-op-level target-op-level current-skill-level target-skill-level module".split(" "),c={IDs:[]},d=0;d<db.op.keys.length;++d){var k=
db.op.keys[d],a="optotal_"+k+"_";c[k]=[];for(var r=!1,g=0;g<b.length;++g)null!==localStorage.getItem(a+b[g])&&(c[k].push(b[g]),r=!0);r&&c.IDs.push(k)}if(0===c.IDs.length)document.getElementById("content-body").style.opacity=1,console.log("loadComplete");else{document.getElementById("selected-op-guide").style.display="none";c.IDs.sort(function(n,f){let p=Number(n.split("-")[1]||0),h=Number(f.split("-")[1]||0),u,t;n=n.split("-")[0];f=f.split("-")[0];u=Number(db.op[n].rarity);t=Number(db.op[f].rarity);
if(u>t)return-1;if(u<t)return 1;u=getNumOfSkills(n);t=getNumOfSkills(f);if(u>t)return-1;if(u<t)return 1;u=db.op[n].module?Object.keys(db.op[n].module).length:0;t=db.op[f].module?Object.keys(db.op[f].module).length:0;if(u>t)return-1;if(u<t)return 1;if(n<f)return-1;if(n>f)return 1;1===n.length&&n.push(0);1===f.length&&f.push(0);return p<h?-1:1});Date.now();doNotRefreshResult=!0;b="";d=0;for(k=c.IDs.length;d<k;++d)b+=`<div class="op" name="${c.IDs[d]}" style="color:#bbb;text-align:center;"><pre>\n\n\n\nLoading...</pre></div>`;
document.getElementById("selected-op").innerHTML=b;document.getElementById("content-body").style.opacity=1;setTimeout(function(){for(var n="",f=0,p=c.IDs.length;f<p;++f){for(var h=c.IDs[f],u="optotal_"+h+"_",t={keys:[]},m=0,z=c[h].length;m<z;++m){var l=c[h][m],B=JSON.parse(localStorage.getItem(u+l));t[l]=B;t.keys.push(l)}n+=makeOpForm(h,{values:t,asElement:!1})}f=document.getElementById("selected-op");f.innerHTML=n;doNotCenter=!0;f.querySelectorAll(".op").forEach(function(y){addOpEventListener(y,
!0)});doNotRefreshResult=!1;showResult();console.log("loadComplete")},0)}},removeAllInputData=function(b){gtag("event","\ubaa8\ub4e0 \uc785\ub825 \ub370\uc774\ud130 \uc0ad\uc81c: \ubc84\ud2bc \ud074\ub9ad",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"});confirm("\uc8fc\uc758: \uc774 \uc791\uc5c5\uc740 \ub418\ub3cc\ub9b4 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4.\n\uc815\ub9d0 \uc774 \uc11c\ube44\uc2a4\uc758 \ubaa8\ub4e0 \ub370\uc774\ud130\ub97c \uc0ad\uc81c\ud558\uc2dc\uaca0\uc2b5\ub2c8\uae4c?")?
(Object.keys(localStorage).filter(c=>0<=c.indexOf("optotal_")).forEach(c=>localStorage.removeItem(c)),location.reload()):(gtag("event","\ubaa8\ub4e0 \uc785\ub825 \ub370\uc774\ud130 \uc0ad\uc81c: \ucde8\uc18c",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"}),alert("\ub370\uc774\ud130 \uc0ad\uc81c\uac00 \ucde8\uc18c\ub418\uc5c8\uc2b5\ub2c8\ub2e4."))};
var triggerEvent=function(b,c,d=null){null!==d?b.dispatchEvent(new CustomEvent(c,{detail:d})):b.dispatchEvent(new CustomEvent(c))},getMaxElite=function(b){return[0,0,1,2,2,2][b-1]},getMaxModuleLevel=function(b){return 3},getNumOfSkills=function(b,c=null){var d=db.op[b].rarity;null===c&&(c=getMaxElite(d));if(null===db.op[b].skill){var k=b.split("-")[0];if(k===b||null===db.op[k].skill)return console.error("\ub2e4\uc74c \uc6d0\ubcf8 \uc624\ud37c\ub808\uc774\ud130\uc758 skill \uac12\uc774 null\uc784:",
b),0;b=k}b=2<=getMaxElite(d)?db.op[b].skill.mastery.length:[0,0,1,2,2,3][d-1];k=[1,2,3][c];void 0===k&&(console.error("elite \uac12\uc5d0 \ubb38\uc81c \uc788\uc74c:",c),k=[1,2,3][getMaxElite(d)]);k>b&&(k=b);return k},getNumOfModules=function(b){return(b=db.op[b].module)?Object.keys(b).length:0},getMaxSkillLevel=function(b){return[4,7,10][b]},opFormRecalcHandler=function(b){var c=this.getAttribute("name").split("_")[1],d=c.split("-")[0],k=c===d,a={};document.querySelectorAll(`#selected-op [name^="op_${d}"]`).forEach(function(e){let q=
e.getAttribute("name").split("_")[1];a[q]={};a[q].form=e;a[q].currentEliteElem=e.querySelectorAll(".current-elite")[0];a[q].targetEliteElem=e.querySelectorAll(".target-elite")[0];a[q].currentLevelElem=e.querySelectorAll(".current-op-level")[0];a[q].targetLevelElem=e.querySelectorAll(".target-op-level")[0];a[q].currentSkillLevelElems=e.querySelectorAll(".current-skill-level");a[q].targetSkillLevelElems=e.querySelectorAll(".target-skill-level");a[q].currentModuleLevelElems=e.querySelectorAll(".current-module-level");
a[q].targetModuleLevelElems=e.querySelectorAll(".target-module-level");a[q].currentElite=Number(e.querySelector(".current-elite").value);a[q].targetElite=Number(e.querySelector(".target-elite").value);a[q].currentLevel=Number(e.querySelector(".current-op-level").value);a[q].targetLevel=Number(e.querySelector(".target-op-level").value);a[q].currentSkillLevels=Array.from(e.querySelectorAll(".current-skill-level"),A=>Number(A.value));a[q].targetSkillLevels=Array.from(e.querySelectorAll(".target-skill-level"),
A=>Number(A.value));a[q].module={};e.querySelectorAll(".current-module-level").forEach(A=>{a[q].module[A.dataset.moduleCode]=[Number(A.value)]});e.querySelectorAll(".target-module-level").forEach(A=>{a[q].module[A.dataset.moduleCode].push(Number(A.value))})});if(!k){var r=null===db.op[c].elite;var g=null===db.op[c].skill}r&&(a[c].currentElite=a[d].currentElite,a[c].targetElite=a[d].targetElite,a[c].currentLevel=a[d].currentLevel,a[c].targetLevel=a[d].targetLevel,a[c].currentEliteElem.disabled=!0,
a[c].targetEliteElem.disabled=!0,a[c].currentLevelElem.disabled=!0,a[c].targetLevelElem.disabled=!0,this.querySelectorAll(".set-current-op-level-to-max-btn, .set-target-op-level-to-max-btn").forEach(e=>e.disabled=!0),this.querySelectorAll(".elite, .opLevel").forEach(e=>e.style.opacity=0));g&&(a[c].currentSkillLevels=[...a[d].currentSkillLevels],a[c].targetSkillLevels=[...a[d].targetSkillLevels],a[c].currentSkillLevelElems.forEach(function(e){e.disabled=!0}),a[c].targetSkillLevelElems.forEach(function(e){e.disabled=
!0}),this.querySelector(".skill").style.opacity=0);var n=Number(db.op[c].rarity);getNumOfSkills(c);r=getMaxModuleLevel(c);var f=null;f=b.detail&&b.detail.from?b.detail.from:{type:"all"};if("all"===f.type)var p=!0,h=b=!0,u=!0;else{if("elite"===f.type)h=b=p=!0,u=!1;else if("level"===f.type)p=!1,b=!0,u=h=!1;else if("skill"===f.type){if(b=p=!1,h=!0,u=!1,!Number.isInteger(f.index)||0>f.index||3<=f.index){console.error("\uc778\ub371\uc2a4 \uc624\ub958:",f.index);return}}else if("module"===f.type)h=b=p=
!1,u=!0;else{console.error("\ud0c0\uc785 \uc624\ub958:",f.type);return}if("current"!==f.position&&"target"!==f.position){console.error("\ud3ec\uc9c0\uc158 \uc624\ub958:",f.position);return}}g&&(h=!1);if(p&&(g=getMaxElite(n),a[c].currentElite>g&&(a[c].currentElite=g),a[c].targetElite>g&&(a[c].targetElite=g),a[c].targetElite<a[c].currentElite&&(a[c].targetElite=a[c].currentElite),k))for(var t in a)1==a[t].currentEliteElem.disabled&&(a[t].currentElite=a[d].currentElite),1==a[t].targetEliteElem.disabled&&
(a[t].targetElite=a[d].targetElite);if(h){for(var m in a)for(d=getMaxSkillLevel(a[m].currentElite),t=getNumOfSkills(m),g=0;g<t;++g)a[m].currentSkillLevels[g]>d&&(a[m].currentSkillLevels[g]=d);if("skill"===f.type&&"current"===f.position){let e=a[c].currentSkillLevels[f.index];if(7>e)for(var z in a)a[z].currentSkillLevels=a[z].currentSkillLevels.map(q=>e);else for(let q in a)a[q].currentSkillLevels=a[q].currentSkillLevels.map(A=>7>A?7:A)}else{let e=-Infinity;for(var l in a){m=getNumOfSkills(l,a[l].currentElite);
for(z=0;z<m&&(e=a[l].currentSkillLevels[z]>e?a[l].currentSkillLevels[z]:e,e=7<e?7:e,7!==e);++z);if(7===e)break}for(var B in a)a[B].currentSkillLevels=a[B].currentSkillLevels.map(q=>q<e?e:q)}console.log(JSON.parse(JSON.stringify(a)));for(var y in a)for(l=getMaxSkillLevel(a[y].targetElite),B=getNumOfSkills(y),m=0;m<B;++m)a[y].targetSkillLevels[m]<a[y].currentSkillLevels[m]?a[y].targetSkillLevels[m]=a[y].currentSkillLevels[m]:a[y].targetSkillLevels[m]>l&&(a[y].targetSkillLevels[m]=l);if("skill"===f.type&&
"target"===f.position){let e=a[c].targetSkillLevels[f.index];if(7>e)for(var C in a)a[C].targetSkillLevels=a[C].targetSkillLevels.map(q=>e);else for(let q in a)a[q].targetSkillLevels=a[q].targetSkillLevels.map(A=>7>A?7:A)}else{let e=-Infinity;for(var F in a){y=getNumOfSkills(F,a[F].targetElite);for(C=0;C<y&&(e=a[F].targetSkillLevels[C]>e?a[F].targetSkillLevels[C]:e,e=7<e?7:e,7!==e);++C);if(7===e)break}for(var H in a)a[H].targetSkillLevels=a[H].targetSkillLevels.map(q=>q<e?e:q)}}if(u)for(var x in a)if(F=
a[x].module,H=[],db.op[x].module){H=f.moduleCode?[f.moduleCode]:Object.keys(F);console.log(x,"\ubaa8\ub4c8",F,"from",f,"moduleCodes",H);for(var G in H){G=H[G];y=F[G][0];C=F[G][1];if(0>y||y>r)y=0;if(0>C||C>r)C=r;C<y&&(C=y);F[G][0]=y;F[G][1]=C}}if(b)for(var v in a)x=getMaxLevel(a[v].currentElite,n),a[v].currentLevel>x&&(a[v].currentLevel=x),1>a[v].currentLevel&&(a[v].currentLevel=1),x=getMaxLevel(a[v].targetElite,n),a[v].targetLevel>x&&(a[v].targetLevel=x),a[v].currentElite===a[v].targetElite&&a[v].targetLevel<
a[v].currentLevel?a[v].targetLevel=a[v].currentLevel:1>a[v].targetLevel&&(a[v].targetLevel=1);if(p){v=null;for(var D in a){n=getMaxElite(db.op[D].rarity);v=a[D].currentEliteElem.options;for(let e=0,q=n;e<q;++e)v[e].disabled=e>n?!0:!1;a[D].currentEliteElem.value=a[D].currentElite;v=a[D].targetEliteElem.options;for(let e=0,q=v.length;e<q;++e)v[e].disabled=e<a[D].currentElite||e>n?!0:!1;a[D].targetEliteElem.value=a[D].targetElite}}if(h)for(var w in a){D=getNumOfSkills(w);n=getNumOfSkills(w,a[w].currentElite);
h=getNumOfSkills(w,a[w].targetElite);p=getMaxSkillLevel(a[w].currentElite);v=getMaxSkillLevel(a[w].targetElite);for(x=0;x<n;++x){a[w].currentSkillLevelElems[x].disabled=!1;G=a[w].currentSkillLevelElems[x].options;for(let e=0,q=G.length;e<q;++e)G[e].disabled=e>=p?!0:!1;a[w].currentSkillLevelElems[x].value=a[w].currentSkillLevels[x]}for(;n<D;++n)a[w].currentSkillLevelElems[n].disabled=!0,a[w].currentSkillLevelElems[n].value=a[w].currentSkillLevels[n];for(n=0;n<h;++n){a[w].targetSkillLevelElems[n].disabled=
!1;p=a[w].targetSkillLevelElems[n].options;for(let e=0,q=p.length,A=a[w].currentSkillLevels[n]-1;e<q;++e)p[e].disabled=e<A||e>=v?!0:!1;a[w].targetSkillLevelElems[n].value=a[w].targetSkillLevels[n]}for(;h<D;++h)a[w].targetSkillLevelElems[h].disabled=!0,a[w].targetSkillLevelElems[h].value=a[w].targetSkillLevels[h]}if(u)for(var E in a)if(w=a[E].module,u=[],db.op[E].module){u=f.moduleCode?[f.moduleCode]:Object.keys(w);for(let e in u){e=u[e];D=document.querySelector(`.op[name="op_${E}"] .current-module-level[data-module-code=${e}]`);
h=document.querySelector(`.op[name="op_${E}"] .target-module-level[data-module-code=${e}]`);v=h.querySelectorAll("option");n=w[e][0];p=w[e][1];for(x=0;x<=r;++x)v[x].disabled=x<n?!0:!1;D.value=n;h.value=p}}if(b)for(let e in a)a[e].currentLevelElem.value=a[e].currentLevel,a[e].targetLevelElem.value=a[e].targetLevel;for(let e in a)E="optotal_"+e+"_",localStorage.setItem(E+"current-elite",JSON.stringify(a[e].currentElite)),localStorage.setItem(E+"current-op-level",JSON.stringify(a[e].currentLevel)),localStorage.setItem(E+
"current-skill-level",JSON.stringify(a[e].currentSkillLevels)),localStorage.setItem(E+"target-elite",JSON.stringify(a[e].targetElite)),localStorage.setItem(E+"target-op-level",JSON.stringify(a[e].targetLevel)),localStorage.setItem(E+"target-skill-level",JSON.stringify(a[e].targetSkillLevels)),localStorage.setItem(E+"module",JSON.stringify(a[e].module));if(k)for(c=document.querySelectorAll(`#selected-op [name^="op_${c}-"]`),k=0;k<c.length;++k)triggerEvent(c[k],"recalc");showResult()},thumbMouseoverHandler=
function(b){b.currentTarget.querySelectorAll(".remove-btn, .module-btn").forEach(function(c){c.classList.add("active")})},thumbMouseoutHandler=function(b){b.currentTarget.querySelectorAll(".remove-btn, .module-btn").forEach(function(c){c.classList.remove("active")})},removeBtnClickHandler=function(){gtag("event","\uc624\ud37c\ub808\uc774\ud130 \uc0ad\uc81c: \ubc84\ud2bc \ud074\ub9ad",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"});var b=this.closest(".op").getAttribute("name").split("_")[1];
b=getAllIDs(b);for(var c=0;c<b.length;++c){document.querySelector(`#selected-op [name="op_${b[c]}"]`).remove();for(var d="optotal_"+b[c]+"_",k="current-elite target-elite current-op-level target-op-level current-skill-level target-skill-level module".split(" "),a=0;a<k.length;++a)localStorage.removeItem(d+k[a])}null===document.querySelector('div[name*="op_"].op')&&(document.getElementById("selected-op-guide").style.display="block");showResult()},setCurrentOpLevelToMaxHandler=function(){gtag("event",
"\ud604\uc7ac \ub808\ubca8 \ucd5c\ub300 \uc124\uc815",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"});if(!this.disabled){var b=this.closest(".op"),c=b.getAttribute("name").split("_")[1],d=b.querySelector(".current-op-level");if(c in db.op){var k=Number(b.querySelector(".current-elite").value);c=getMaxLevel(k,Number(db.op[c].rarity));d.value=c;triggerEvent(b,"recalc",{from:{type:"level",position:"current"}})}else console.error("\uc5d0\ub7ec: \ucde8\ub4dd\ud55c \uc624\ud37c\ub808\uc774\ud130 \uc544\uc774\ub514("+
c+")\ub97c DB\uc5d0\uc11c \ucc3e\uc744 \uc218 \uc5c6\uc74c")}},setTargetOpLevelToMaxHandler=function(){gtag("event","\ubaa9\ud45c \ub808\ubca8 \ucd5c\ub300 \uc124\uc815",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"});if(!this.disabled){var b=this.closest(".op"),c=b.getAttribute("name").split("_")[1],d=b.querySelector(".target-op-level");if(c in db.op){var k=Number(b.querySelector(".target-elite").value);c=getMaxLevel(k,Number(db.op[c].rarity));d.value=
c;triggerEvent(b,"recalc",{from:{type:"level",position:"target"}})}else console.error("\uc5d0\ub7ec: \ucde8\ub4dd\ud55c \uc624\ud37c\ub808\uc774\ud130 \uc544\uc774\ub514("+c+")\ub97c DB\uc5d0\uc11c \ucc3e\uc744 \uc218 \uc5c6\uc74c")}},currentEliteChangeHandler=function(){this.disabled||triggerEvent(this.closest(".op"),"recalc",{from:{type:"elite",position:"current"}})},targetEliteChangeHandler=function(){this.disabled||triggerEvent(this.closest(".op"),"recalc",{from:{type:"elite",position:"target"}})},
currentOpLevelChangeHandler=function(){this.disabled||triggerEvent(this.closest(".op"),"recalc",{from:{type:"level",position:"current"}})},targetOpLevelChangeHandler=function(){this.disabled||triggerEvent(this.closest(".op"),"recalc",{from:{type:"level",position:"target"}})},currentSkillLevelChangeHandler=function(b){this.disabled||triggerEvent(this.closest(".op"),"recalc",{from:{type:"skill",position:"current",index:Number(b.target.dataset.index)}})},targetSkillLevelChangeHandler=function(b){this.disabled||
triggerEvent(this.closest(".op"),"recalc",{from:{type:"skill",position:"target",index:Number(b.target.dataset.index)}})},currentModuleLevelChangeHandler=function(b){this.disabled||triggerEvent(this.closest(".op"),"recalc",{from:{type:"module",position:"current",moduleCode:b.target.dataset.moduleCode}})},targetModuleLevelChangeHandler=function(b){this.disabled||triggerEvent(this.closest(".op"),"recalc",{from:{type:"module",position:"target",moduleCode:b.target.dataset.moduleCode}})};
const addOpEventListener=function(b,c=!1){b.addEventListener("recalc",opFormRecalcHandler);b.querySelector(".thumb").addEventListener("mouseover",thumbMouseoverHandler);b.querySelector(".thumb").addEventListener("mouseout",thumbMouseoutHandler);b.querySelector(".remove-btn").addEventListener("click",removeBtnClickHandler);b.querySelector(".set-current-op-level-to-max-btn").addEventListener("click",setCurrentOpLevelToMaxHandler);b.querySelector(".set-target-op-level-to-max-btn").addEventListener("click",
setTargetOpLevelToMaxHandler);b.querySelector(".current-elite").addEventListener("change",currentEliteChangeHandler);b.querySelector(".target-elite").addEventListener("change",targetEliteChangeHandler);b.querySelector(".current-op-level").addEventListener("change",currentOpLevelChangeHandler);b.querySelector(".target-op-level").addEventListener("change",targetOpLevelChangeHandler);b.querySelectorAll(".current-skill-level").forEach(function(d){d.addEventListener("change",currentSkillLevelChangeHandler)});
b.querySelectorAll(".target-skill-level").forEach(function(d){d.addEventListener("change",targetSkillLevelChangeHandler)});b.querySelectorAll(".current-module-level").forEach(function(d){d.addEventListener("change",currentModuleLevelChangeHandler)});b.querySelectorAll(".target-module-level").forEach(function(d){d.addEventListener("change",targetModuleLevelChangeHandler)});c&&triggerEvent(b,"recalc",{from:{type:"all"}})};var searchingCondition={name:"",rarityArray:[],tagCode:0};
const getTagCodeByKRTagName=function(b){for(var c=0;c<db.tag.keys.length;++c)if(db.tag[db.tag.keys[c]].name.kr==b)return Number(db.tag[db.tag.keys[c]].tagCode)},showSearchResult=function(){searchingCondition.rarityArray.sort(function(r,g){return r>g?-1:1});for(var b=searchOp(searchingCondition.name,searchingCondition.rarityArray,searchingCondition.tagCode),c=[],d=0,k=b.keys.length,a="";d<k;++d)a=b.keys[d],c.push([b[a].name.kr,a]);c.sort(function(r,g){return r[0].localeCompare(g[0])});b="";for(d=0;d<
c.length;++d)b+='<div class="search-result-op" name="op_'+c[d][1]+'"><img src="./images/op/thumb/'+db.op[c[d][1]].releaseOrder+'.png"><div><span>'+c[d][0]+"</span></div></div>";""==b&&(b='<p style="font-size: 0.5em; text-align: center">\uac80\uc0c9 \uacb0\uacfc\uac00 \uc874\uc7ac\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.</p>');document.querySelector(".modal-footer>.search-result").innerHTML=b;document.querySelectorAll(".search-result-op").forEach(function(r){r.addEventListener("click",function(){for(var g=
this.getAttribute("name").split("_")[1],n=g.split("-")[0],f=getAllIDs(g),p=0;p<f.length;++p)if(console.log(f[p],"\ucd94\uac00"),`optotal_${f[p]}_current-elite`in localStorage)console.error(g+": \uc774\ubbf8 \ucd94\uac00\ub41c \uc624\ud37c\ub808\uc774\ud130");else{var h=makeOpForm(f[p],{values:{},asElement:!0});document.getElementById("selected-op").appendChild(h);addOpEventListener(h,!0);document.getElementById("selected-op-guide").style.display="none";gtag("event","\uc624\ud37c\ub808\uc774\ud130 \ucd94\uac00",
{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"})}g=document.querySelectorAll('.search-result-op[name^="op_'+n+'"]');for(p=0;p<g.length;++p)g[p].remove();0===document.querySelectorAll(".modal-footer>.search-result>.search-result-op").length&&(document.querySelector(".modal-footer>.search-result").innerHTML='<p style="font-size: 0.5em; text-align: center">\uac80\uc0c9 \uacb0\uacfc\uac00 \uc874\uc7ac\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.</p>')})});document.querySelectorAll(".search-result-op div").forEach(function(r){$(r).textfill()})};
(function(b){b.fn.textfill=function(c){c=parseInt(c,10);return this.each(function(){function d(){var a=k.parent(),r=a.height(),g=a.width();a=parseInt(k.css("font-size"),10);g/=k.width();var n=a*(g-.1);g=r/k.height();c=a*(g-.1);k.css("fontSize",0<c&&n>c?c:n)}var k=b("span",this);b(window).resize(function(){"block"===document.querySelector(".modal").style.display&&d()});d()})}})(jQuery);
const searchOp=function(b,c,d){b=b.replace(/(\s*)/g,"").toLowerCase();var k=0<b.length,a=0<c.length,r=0!=d;if(!(k||a||r))return{keys:[]};for(var g={},n=Object.keys(localStorage).filter(z=>0===z.indexOf("optotal_")),f=0,p=db.op.keys.length,h="",u="";f<p;++f){h=db.op.keys[f];u="optotal_"+h;for(var t=0,m=n.length;t<m&&0!==n[t].indexOf(u);++t);t<m||(g[h]={},g[h].rarity=db.op[h].rarity,g[h].tagCode=db.op[h].tagCode,g[h].name={},g[h].name.kr=db.op[h].name.kr,g[h].name.en=db.op[h].name.en,g[h].name.jp=db.op[h].name.jp,
g[h].name.cn=db.op[h].name.cn)}g.keys=Object.keys(g);if(k)for(f=0,p=g.keys.length,h="";f<p;++f)h=g.keys[f],0>g[h].name.kr.replace(/(\s*)/g,"").toLowerCase().indexOf(b)&&0>g[h].name.en.replace(/(\s*)/g,"").toLowerCase().indexOf(b)&&0>g[h].name.jp.replace(/(\s*)/g,"").toLowerCase().indexOf(b)&&0>g[h].name.cn.replace(/(\s*)/g,"").toLowerCase().indexOf(b)&&(delete g[h],g.keys.splice(f,1),--f,--p);if(a)for(b=!1,f=0,k=g.keys.length,h="";f<k;++f){h=g.keys[f];b=!1;t=0;for(m=c.length;t<m;++t)if(rarity=c[t],
g[h].rarity==rarity){b=!0;break}b||(delete g[h],g.keys.splice(f,1),--f,--k)}if(r)for(f=0,p=g.keys.length,h="";f<p;++f)h=g.keys[f],d&g[h].tagCode||(delete g[h],g.keys.splice(f,1),--f,--p);return g},addResultToMcalc=function(b){var c=fetchInputData();if(!1===c)showTooltip("\uc804\uc1a1\ud560 \ub370\uc774\ud130\uac00 \uc874\uc7ac\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4",b.target,"error");else if(gtag("event","\uc7ac\ub8cc \uacc4\uc0b0\uae30\ub85c \uc804\uc1a1 \uc2dc\uc791",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"}),
confirm("\uacb0\uacfc \ub370\uc774\ud130\ub97c \uc804\uc1a1\ud558\uc2dc\ub824\uba74 \ud655\uc778 \ubc84\ud2bc\uc744 \ub20c\ub7ec\uc8fc\uc2ed\uc2dc\uc624.")){c=sortResultData(calc(c));for(var d=0;d<c.total.IDs.length;++d){var k=Number(c.total.IDs[d]),a=Number(c.total[k]);a+=JSON.parse(localStorage.getItem("mcalc_item-need_"+k));localStorage.setItem("mcalc_item-need_"+k,JSON.stringify(a))}showTooltip("\uc131\uacf5\uc801\uc73c\ub85c \uacb0\uacfc \ub370\uc774\ud130\ub97c \uc804\uc1a1\ud558\uc600\uc2b5\ub2c8\ub2e4",
b.target,"success");confirm("\uc131\uacf5\uc801\uc73c\ub85c \uacb0\uacfc \ub370\uc774\ud130\ub97c \uc804\uc1a1\ud558\uc600\uc2b5\ub2c8\ub2e4.\n\ubc14\ub85c \uc7ac\ub8cc \uacc4\uc0b0\uae30\ub85c \uc774\ub3d9\ud558\uc2dc\uaca0\uc2b5\ub2c8\uae4c?")&&("1"==localStorage.getItem("preferred-version_mcalc")?location.href="mcalc-legacy.html":location.href="mcalc.html")}else gtag("event","\uc7ac\ub8cc \uacc4\uc0b0\uae30\ub85c \uc804\uc1a1 \ucde8\uc18c",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"}),
showTooltip("\ub370\uc774\ud130 \uc804\uc1a1\uc774 \ucde8\uc18c\ub418\uc5c8\uc2b5\ub2c8\ub2e4",b.target,"error")};main();
