var setSkillLevelBound=function(a,b,f){f=$(f);var g=Number(f.val());g<a&&f.val(a);g>b&&f.val(b);f=f.find("option");for(g=0;g<f.length;++g){var c=f.eq(g),d=Number(c.val());d<a||d>b?c.prop("disabled",!0):c.prop("disabled",!1)}},validateTargetSkillLevel=function(a,b){var f=$(b),g=a.currentSkillLevel,c=[4,7,10][a.targetElite];g>c&&console.log("\uc5d0\ub7ec: \ud558\ud55c\uc774 \uc0c1\ud55c\ubcf4\ub2e4 \ud07d\ub2c8\ub2e4.",g,c,a,f);setSkillLevelBound(g,c,f)},validateCurrentSkillLevel=function(a,b){var f=
$(b),g=[4,7,10][a.currentElite];1>g&&console.log("\uc5d0\ub7ec: \ud558\ud55c\uc774 \uc0c1\ud55c\ubcf4\ub2e4 \ud07d\ub2c8\ub2e4.",1,g,a,f);setSkillLevelBound(1,g,f)},openModalPrompt=function(){$(".modal").css("display","block");doNotRefreshResult=!0},closeModalPrompt=function(){$("#modal").css("display","none");doNotRefreshResult=!1;showResult()};
$(document).ready(function(){toastr.options={closeButton:!1,debug:!1,newestOnTop:!1,progressBar:!1,positionClass:"toast-top-full-width",preventDuplicates:!1,onclick:null,showDuration:"200",hideDuration:"500",timeOut:"1000",extendedTimeOut:"500",showEasing:"swing",hideEasing:"linear",showMethod:"fadeIn",hideMethod:"fadeOut"};$(".add-btn").click(function(){openModalPrompt()});$(".close-btn").click(function(){closeModalPrompt()});$(window).click(function(a){$(a.target).is($("#modal"))&&closeModalPrompt()});
$("#opname").keyup(function(){for(var a="",b=$(this).val().split(" "),f=0;f<b.length;++f)0<f&&(a+=" "),a+=b[f].charAt(0).toUpperCase()+b[f].slice(1).toLowerCase();searchingCondition.name=a;showSearchResult()});$(".rarity-btn").click(function(){var a=Number($(this).attr("name")),b=searchingCondition.rarityArray.indexOf(a);0<=b?(searchingCondition.rarityArray.splice(b,1),$(this).removeClass("selected")):(searchingCondition.rarityArray.push(a),$(this).addClass("selected"));showSearchResult()});$(".class-btn").click(function(){var a=
getTagCodeByKRTagName($(this).attr("name"));a&searchingCondition.tagCode?$(this).removeClass("selected"):$(this).addClass("selected");searchingCondition.tagCode^=a;showSearchResult()});loadLocalStorage()});
var makeOpForm=function(a){var b=data.opData[a].name.en,f=Number(data.opData[a].rarity);b=b.toLowerCase();a='<form class="op" align="center" name="op_'+a+'"> <span class="remove-op-btn">\u00d7</span> <img class="op" src="./images/op/thumb/'+(b+'.png"><br>');a+="<span>\uc815\uc608\ud654</span><br> ";a+='<select style="font-size: 60%;" class="current-elite"> ';f=[0,0,1,2,2,2][f-1];for(b=0;b<=f;++b)a+='<option value="'+b+'"',0==b&&(a+=" selected"),a+=">"+b+"\ub2e8\uacc4</option> ";a+="</select> ";a+=
"<span>\u25b8</span> ";a+='<select style="font-size: 60%;" class="target-elite"> ';for(b=0;b<=f;++b)a+='<option value="'+b+'"',b==f&&(a+=" selected"),a+=">"+b+"\ub2e8\uacc4</option> ";a+="</select><br> ";a+="<hr> ";a+='<button type="button" class="set-current-op-level-to-max-btn"> ';a+="MAX";a+="</button> ";a+="<span>\ub808\ubca8</span> ";a+='<button type="button" class="set-target-op-level-to-max-btn"> ';a+="MAX";a+="</button><br> ";a+='<input type="text" class="current-op-level" style="font-size: 60%;" value="1"> ';
a+="<span>\u25b8</span> ";a+='<input type="text" class="target-op-level" style="font-size: 60%;" value="1"><br> ';a+="<hr> ";a+="<span>\uc2a4\ud0ac \ub808\ubca8</span><br> ";a+='<div style="font-size: 85%; margin-top: 0.2em"> ';a+='<span style="font-size: 65%">1\uc2a4\ud0ac</span> ';a+='<select style="width: 20%" class="current-skill-level"> ';for(b=1;10>=b;++b)a+='<option value="'+b+'">'+b+"</option> ";a+="</select> ";a+='<span style="font-size: 65%">\u25b8</span> ';a+='<select style="width: 20%" class="target-skill-level"> ';
f=[4,7,7][f];for(b=1;10>=b;++b)a+='<option value="'+b+'"',b==f&&(a+=" selected"),a+=">"+b+"</option> ";a+="</select> ";a+="<br> ";a+='<span style="font-size: 65%">2\uc2a4\ud0ac</span> ';a+='<select style="width: 20%;" class="current-skill-level"> ';for(b=1;10>=b;++b)a+='<option value="'+b+'">'+b+"</option> ";a+="</select> ";a+='<span style="font-size: 65%">\u25b8</span> ';a+='<select style="width: 20%" class="target-skill-level"> ';for(b=1;10>=b;++b)a+='<option value="'+b+'"',b==f&&(a+=" selected"),
a+=">"+b+"</option> ";a+="</select> ";a+="<br> ";a+='<span style="font-size: 65%">3\uc2a4\ud0ac</span> ';a+='<select style="width: 20%;" class="current-skill-level"> ';for(b=1;10>=b;++b)a+='<option value="'+b+'">'+b+"</option> ";a+="</select> ";a+='<span style="font-size: 65%">\u25b8</span> ';a+='<select style="width: 20%" class="target-skill-level"> ';for(b=1;10>=b;++b)a+='<option value="'+b+'"',b==f&&(a+=" selected"),a+=">"+b+"</option> ";a+="</select> ";a+="<br> ";a+="</div> ";return a+="</form>"},
loadLocalStorage=function(){for(var a="current-elite target-elite current-op-level target-op-level current-skill-level target-skill-level".split(" "),b={IDs:[]},f=0;f<data.opData.length;++f){var g=f,c="optotal_"+g+"_";b[g]=[];for(var d=!1,m=0;m<a.length;++m){var l=c+a[m];null!==localStorage.getItem(l)&&(b[g].push(a[m]),d=!0)}d&&b.IDs.push(g)}doNotRefreshResult=!0;for(f=0;f<b.IDs.length;++f){g=b.IDs[f];c="optotal_"+g+"_";a={keys:[]};for(m=0;m<b[g].length;++m){var h=b[g][m];l=c+h;d=JSON.parse(localStorage.getItem(l));
a[h]=d;a.keys.push(h)}addOp(g,!1);g=$('form[name="op_'+g+'"].op');for(m=0;m<a.keys.length;++m)if(l=a.keys[m],d=a[l],"current-elite"===l)g.find(".current-elite").val(d);else if("target-elite"===l)g.find(".target-elite").val(d);else if("current-op-level"===l)g.find(".current-op-level").val(d);else if("target-op-level"===l)g.find(".target-op-level").val(d);else if("current-skill-level"===l)for(l=g.find(".current-skill-level"),c=0;c<d.length;++c)l.eq(c).val(d[c]);else if("target-skill-level"===l)for(l=
g.find(".target-skill-level"),c=0;c<d.length;++c)l.eq(c).val(d[c]);g.find(".current-elite").trigger("change")}doNotRefreshResult=!1;showResult()},addOp=function(a,b){b=void 0===b?!0:b;if(0>=$('#selected-op form[name|="op_'+a+'"]').length){$("#selected-op").append(makeOpForm(a));var f=$('form[name="op_'+a+'"].op');f.find(".remove-op-btn").off("click").on("click",function(){var a=Number($(this).parent().attr("name").split("_")[1]);if(Number.isNaN(a))console.log("\uc5d0\ub7ec: \uc624\ud37c\ub808\uc774\ud130 \uc544\uc774\ub514\uac00 \uc22b\uc790\ub85c \uc774\ub904\uc9c0\uc9c0 \uc54a\uc74c");
else{$(this).parent().remove();a="optotal_"+a+"_";for(var c="current-elite target-elite current-op-level target-op-level current-skill-level target-skill-level".split(" "),d=0;d<c.length;++d)localStorage.removeItem(a+c[d]);0===$('form[name*="op_"].op').length&&$("#selected-op-guide").css("display","block");showResult()}});f.find(".set-current-op-level-to-max-btn").off("click").on("click",function(){var a=$(this).parent(),c=Number(a.attr("name").split("_")[1]),d=a.find(".current-op-level");({})["current-op-level"]=
Number(d.val());Number.isNaN(c)?console.log("\uc5d0\ub7ec: \uc624\ud37c\ub808\uc774\ud130 \uc544\uc774\ub514\uac00 \uc22b\uc790\ub85c \uc774\ub904\uc9c0\uc9c0 \uc54a\uc74c"):(a=Number(a.find(".current-elite").val()),c=getMaxLevel(a,Number(data.opData[c].rarity)),d.val(c),d.trigger("change"))});f.find(".set-target-op-level-to-max-btn").off("click").on("click",function(){var a=$(this).parent(),c=Number(a.attr("name").split("_")[1]),d=a.find(".target-op-level");({})["target-op-level"]=Number(d.val());
Number.isNaN(c)?console.log("\uc5d0\ub7ec: \uc624\ud37c\ub808\uc774\ud130 \uc544\uc774\ub514\uac00 \uc22b\uc790\ub85c \uc774\ub904\uc9c0\uc9c0 \uc54a\uc74c"):(a=Number(a.find(".target-elite").val()),c=getMaxLevel(a,Number(data.opData[c].rarity)),d.val(c),d.trigger("change"))});f.find(".current-elite").off("change").on("change",function(){var a=$(this).parent(),c=Number(a.attr("name").split("_")[1]),d=a.find(".current-elite"),b=a.find(".target-elite"),f=a.find(".current-op-level");a=a.find(".current-skill-level");
var h={};h["target-elite"]=Number(b.val());h["current-op-level"]=Number(f.val());h["current-skill-level"]=[];for(var e=0;e<a.length;++e)h["current-skill-level"].push(Number(a.eq(e).val()));Number(d.val())>Number(b.val())&&b.val(d.val());h=b.find("option").length;for(e=0;e<h;++e)e<Number(d.val())?b.find('option[value="'+e+'"]').prop("disabled",!0):b.find('option[value="'+e+'"]').prop("disabled",!1);e=data.opData[c].rarity;e=getMaxLevel(Number(d.val()),e);Number(f.val())>e&&f.val(e);e=[0,0,1,2,2,3][Number(data.opData[c].rarity)-
1];"\uc544\ubbf8\uc57c"==data.opData[c].name.kr&&(e=3);h=[1,2,3][Number(d.val())];h>e&&(h=e);for(e=0;e<h;++e){var k=a.eq(e);k.prop("disabled",!1);var n={};n.currentElite=Number(d.val());validateCurrentSkillLevel(n,k)}d=a.length;for(e=h;e<d;++e)a.eq(e).val(1),a.eq(e).prop("disabled",!0);c="optotal_"+c+"_current-elite";d=Number($(this).val());d=Number.isNaN(d)?0:d;localStorage.setItem(c,d);b.trigger("change");f.trigger("change");a.trigger("change")});f.find(".target-elite").off("change").on("change",
function(){var a=$(this).parent(),c=Number(a.attr("name").split("_")[1]);a.find(".current-elite");var d=a.find(".target-elite"),b=a.find(".target-op-level"),f=a.find(".target-skill-level");a=a.find(".current-skill-level");var h={};h["target-op-level"]=Number(b.val());h["target-skill-level"]=[];for(var e=0;e<f.length;++e)h["target-skill-level"].push(Number(f.eq(e).val()));e=data.opData[c].rarity;e=getMaxLevel(Number(d.val()),e);b.val()>e&&b.val(e);e=[0,0,1,2,2,3][Number(data.opData[c].rarity)-1];"\uc544\ubbf8\uc57c"==
data.opData[c].name.kr&&(e=3);h=[1,2,3][Number(d.val())];h>e&&(h=e);for(e=0;e<h;++e){var k=f.eq(e),n=Number(d.val()),q=Number(a.eq(e).val());k.prop("disabled",!1);var p={};p.targetElite=n;p.currentSkillLevel=q;validateTargetSkillLevel(p,k)}d=f.length;for(e=h;e<d;++e)f.eq(e).val(1),f.eq(e).prop("disabled",!0);c="optotal_"+c+"_target-elite";d=Number($(this).val());d=Number.isNaN(d)?2:d;localStorage.setItem(c,d);b.trigger("change");f.trigger("change")});f.find(".current-op-level").off("change").on("change",
function(){var a=$(this).parent(),c=a.attr("name").split("_")[1];a=Number(a.find(".current-elite").val());a=getMaxLevel(a,Number(data.opData[c].rarity));var d=Number($(this).val());d=Number.isNaN(d)?1:d;d=1>d?1:d;d=d>a?a:d;$(this).val(d);localStorage.setItem("optotal_"+c+"_current-op-level",d);showResult()});f.find(".target-op-level").off("change").on("change",function(){var a=$(this).parent(),c=a.attr("name").split("_")[1];a=Number(a.find(".target-elite").val());a=getMaxLevel(a,Number(data.opData[c].rarity));
var d=Number($(this).val());d=Number.isNaN(d)?1:d;d=1>d?1:d;d=d>a?a:d;$(this).val(d);localStorage.setItem("optotal_"+c+"_target-op-level",d);showResult()});f.find(".current-skill-level").off("change").on("change",function(){if(!0!==$(this).prop("disabled")){for(var b=Number($(this).val()),c=$(this).parent().parent(),d=c.find(".target-skill-level:enabled").length,f=c.find(".current-skill-level"),l=c.find(".target-skill-level"),h={"target-skill-level":[]},e=0;e<l.length;++e)h["target-skill-level"].push(Number(l.eq(e).val()));
if(6>=b)for(e=0;e<d;++e){var k=f.eq(e);h=l.eq(e);var n=Number(c.find(".target-elite").val()),q=Number(k.val());k.val(b);k={};k.targetElite=n;k.currentSkillLevel=q;validateTargetSkillLevel(k,h)}else for(e=0;e<d;++e)k=f.eq(e),h=l.eq(e),n=Number(c.find(".target-elite").val()),q=Number(k.val()),7>q&&k.val(7),k={},k.targetElite=n,k.currentSkillLevel=q,validateTargetSkillLevel(k,h);b="optotal_"+a+"_current-skill-level";c=[];for(e=0;e<f.length;++e)c.push(Number(f.eq(e).val()));c=JSON.stringify(c);localStorage.setItem(b,
c);l.trigger("change")}});f.find(".target-skill-level").off("change").on("change",function(){if(!0!==$(this).prop("disabled")){var b=Number($(this).val()),c=$(this).parent().parent(),d=c.find(".target-skill-level:enabled").length,f=Number(c.find(".current-skill-level").eq(0).val()),l=c.find(".current-skill-level"),h=c.find(".target-skill-level");if(6>=b)for(var e=0;e<d;++e){var k=l.eq(e),n=h.eq(e),q=Number(c.find(".target-elite").val());k=Number(k.val());k<f&&(k=f);n.val(b);var p={};p.targetElite=
q;p.currentSkillLevel=k;validateTargetSkillLevel(p,n)}else for(e=0;e<d;++e)k=l.eq(e),n=h.eq(e),q=Number(c.find(".target-elite").val()),k=Number(k.val()),k<f&&(k=f),7>Number(n.val())&&n.val(7),p={},p.targetElite=q,p.currentSkillLevel=k,validateTargetSkillLevel(p,n);b="optotal_"+a+"_target-skill-level";c=[];for(e=0;e<h.length;++e)c.push(Number(h.eq(e).val()));c=JSON.stringify(c);localStorage.setItem(b,c);showResult()}});f.find(".current-elite").trigger("change");$("#selected-op-guide").css("display",
"none");b&&toastr.success(data.opData[a].name.kr,"\ucd94\uac00\ub428")}else b&&toastr.error(data.opData[a].name.kr,"\uc774\ubbf8 \ucd94\uac00\ub418\uc5b4 \uc788\uc74c"),console.log("\uc774\ubbf8 \ucd94\uac00\ub418\uc5b4 \uc788\uc74c",a,data.opData[a].name.kr)},searchingCondition={name:"",rarityArray:[],tagCode:0},getTagCodeByKRTagName=function(a){for(var b=0;b<data.tagData.length;++b)if(data.tagData[b].name.kr==a)return Number(data.tagData[b].tagCode)},showSearchResult=function(){searchingCondition.rarityArray.sort(function(a,
b){return a>b?-1:1});for(var a=searchOp(searchingCondition.name,searchingCondition.rarityArray,searchingCondition.tagCode),b=[],f=[],g=[],c=0;c<a.length;++c)b.push(a[c].name.kr),f.push(a[c].name.en),g.push(a[c].id);a="";for(c=0;c<f.length;++c)a+='<form class="search-result-op" name="op_'+g[c]+'">\t<img src="./images/op/thumb/'+f[c].toLowerCase()+'.png">\t<div>'+b[c]+"</div></form> ";""==a&&(a='<p style="font-size: 0.5em; text-align: center">\uac80\uc0c9 \uacb0\uacfc\uac00 \uc5ec\uae30\uc5d0 \ud45c\uc2dc\ub429\ub2c8\ub2e4.</p>');
$("div.modal-footer>div.search-result").html(a);$("form.search-result-op").off("click").on("click",function(){var a=$(this).attr("name").split("_")[1];addOp(a,!0)})},searchOp=function(a,b,f){var g=[];var c=JSON.parse(JSON.stringify(data.opData));0>=a.replace(/(\s*)/g,"").length&&(a=!1);for(var d=0;d<c.length;++d)0<=c[d].name.kr.indexOf(a)?(g.push(c[d]),c.splice(d,1),--d):0<=c[d].name.en.indexOf(a)?(g.push(c[d]),c.splice(d,1),--d):0<=c[d].name.cn.indexOf(a)?(g.push(c[d]),c.splice(d,1),--d):0<=c[d].name.jp.indexOf(a)&&
(g.push(c[d]),c.splice(d,1),--d);if(0<b.length)for(!1!==a&&(c=JSON.parse(JSON.stringify(g)),g=[]),d=0;d<b.length;++d)for(var m=0;m<c.length;++m)b[d]==c[m].rarity&&(g.push(c[m]),c.splice(m,1),--m);if(0!=f){if(!1!==a||0<b.length)c=JSON.parse(JSON.stringify(g)),g=[];for(d=0;d<c.length;++d)f&c[d].tagCode&&(g.push(c[d]),c.splice(d,1),--d)}return g};