var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(b){return b.raw=b};$jscomp.createTemplateTagFirstArgWithRaw=function(b,a){b.raw=a;return b};$jscomp.arrayIteratorImpl=function(b){var a=0;return function(){return a<b.length?{done:!1,value:b[a++]}:{done:!0}}};$jscomp.arrayIterator=function(b){return{next:$jscomp.arrayIteratorImpl(b)}};$jscomp.makeIterator=function(b){var a="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];return a?a.call(b):$jscomp.arrayIterator(b)};
$jscomp.arrayFromIterator=function(b){for(var a,d=[];!(a=b.next()).done;)d.push(a.value);return d};$jscomp.arrayFromIterable=function(b){return b instanceof Array?b:$jscomp.arrayFromIterator($jscomp.makeIterator(b))};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,a,d){if(b==Array.prototype||b==Object.prototype)return b;b[a]=d.value;return b};$jscomp.getGlobal=function(b){b=["object"==typeof globalThis&&globalThis,b,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var a=0;a<b.length;++a){var d=b[a];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(b,a){var d=$jscomp.propertyToPolyfillSymbol[a];if(null==d)return b[a];d=b[d];return void 0!==d?d:b[a]};
$jscomp.polyfill=function(b,a,d,e){a&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(b,a,d,e):$jscomp.polyfillUnisolated(b,a,d,e))};$jscomp.polyfillUnisolated=function(b,a,d,e){d=$jscomp.global;b=b.split(".");for(e=0;e<b.length-1;e++){var c=b[e];if(!(c in d))return;d=d[c]}b=b[b.length-1];e=d[b];a=a(e);a!=e&&null!=a&&$jscomp.defineProperty(d,b,{configurable:!0,writable:!0,value:a})};
$jscomp.polyfillIsolated=function(b,a,d,e){var c=b.split(".");b=1===c.length;e=c[0];e=!b&&e in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var g=0;g<c.length-1;g++){var f=c[g];if(!(f in e))return;e=e[f]}c=c[c.length-1];d=$jscomp.IS_SYMBOL_NATIVE&&"es6"===d?e[c]:null;a=a(d);null!=a&&(b?$jscomp.defineProperty($jscomp.polyfills,c,{configurable:!0,writable:!0,value:a}):a!==d&&($jscomp.propertyToPolyfillSymbol[c]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(c):$jscomp.POLYFILL_PREFIX+c,c=
$jscomp.propertyToPolyfillSymbol[c],$jscomp.defineProperty(e,c,{configurable:!0,writable:!0,value:a})))};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(b){if(b)return b;var a=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};a.prototype.toString=function(){return this.$jscomp$symbol$id_};var d=0,e=function(b){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new a("jscomp_symbol_"+(b||"")+"_"+d++,b)};return e},"es6","es3");$jscomp.initSymbolIterator=function(){};
$jscomp.polyfill("Symbol.iterator",function(b){if(b)return b;b=Symbol("Symbol.iterator");for(var a="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),d=0;d<a.length;d++){var e=$jscomp.global[a[d]];"function"===typeof e&&"function"!=typeof e.prototype[b]&&$jscomp.defineProperty(e.prototype,b,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return b},"es6",
"es3");$jscomp.initSymbolAsyncIterator=function(){};$jscomp.iteratorPrototype=function(b){b={next:b};b[Symbol.iterator]=function(){return this};return b};$jscomp.iteratorFromArray=function(b,a){b instanceof String&&(b+="");var d=0,e={next:function(){if(d<b.length){var c=d++;return{value:a(c,b[c]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e};
$jscomp.polyfill("Array.prototype.keys",function(b){return b?b:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");$jscomp.polyfill("Number.isFinite",function(b){return b?b:function(a){return"number"!==typeof a?!1:!isNaN(a)&&Infinity!==a&&-Infinity!==a}},"es6","es3");$jscomp.polyfill("Number.isInteger",function(b){return b?b:function(a){return Number.isFinite(a)?a===Math.floor(a):!1}},"es6","es3");$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(b){function a(){this.batch_=null}function d(a){return a instanceof c?a:new c(function(b,c){b(a)})}if(b&&!$jscomp.FORCE_POLYFILL_PROMISE)return b;a.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})}this.batch_.push(a)};var e=$jscomp.global.setTimeout;a.prototype.asyncExecuteFunction=function(a){e(a,0)};a.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];a[b]=null;try{c()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};a.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var c=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(k){b.reject(k)}};c.prototype.createResolveAndReject_=function(){function a(a){return function(d){c||(c=!0,a.call(b,d))}}var b=this,c=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};c.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof c)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};c.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(k){this.reject_(k);return}"function"==typeof b?
this.settleSameAsThenable_(b,a):this.fulfill_(a)};c.prototype.reject_=function(a){this.settle_(2,a)};c.prototype.fulfill_=function(a){this.settle_(1,a)};c.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};c.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)g.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var g=new a;c.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};c.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(l){c.reject(l)}};c.prototype.then=function(a,b){function d(a,b){return"function"==typeof a?function(b){try{e(a(b))}catch(p){f(p)}}:b}var e,f,g=new c(function(a,b){e=a;f=b});this.callWhenSettled_(d(a,e),d(b,f));return g};
c.prototype.catch=function(a){return this.then(void 0,a)};c.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?g.asyncExecute(c):this.onSettledCallbacks_.push(c)};c.resolve=d;c.reject=function(a){return new c(function(b,c){c(a)})};c.race=function(a){return new c(function(b,c){for(var e=$jscomp.makeIterator(a),f=e.next();!f.done;f=e.next())d(f.value).callWhenSettled_(b,
c)})};c.all=function(a){var b=$jscomp.makeIterator(a),e=b.next();return e.done?d([]):new c(function(a,c){function f(b){return function(c){g[b]=c;k--;0==k&&a(g)}}var g=[],k=0;do g.push(void 0),k++,d(e.value).callWhenSettled_(f(g.length-1),c),e=b.next();while(!e.done)})};return c},"es6","es3");
$jscomp.polyfill("Array.from",function(b){return b?b:function(a,b,e){b=null!=b?b:function(a){return a};var c=[],d="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if("function"==typeof d){a=d.call(a);for(var f=0;!(d=a.next()).done;)c.push(b.call(e,d.value,f++))}else for(d=a.length,f=0;f<d;f++)c.push(b.call(e,a[f],f));return c}},"es6","es3");var gtag_searchByNameUsed=!1,gtag_searchByRarityUsed=!1;gtag_searchByClassUsed=!1;
var openModalPrompt=function(){gtag("event","\ub300\uc6d0 \ucd94\uac00 \ud504\ub86c\ud504\ud2b8 \uc5f4\uae30",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"});var b=document.querySelector(".modal");b.style.display="block";b.style.opacity="1";doNotRefreshResult=!0;showSearchResult()},closeModalPrompt=function(){var b=document.querySelector(".modal");b.style.opacity="0";setTimeout(function(){b.style.display="none"},300);doNotRefreshResult=!1;showResult()},
getAllIDs=function(b){b=b.split("-")[0];for(var a=[],d=0;d<db.op.keys.length;++d)db.op.keys[d]===b?a.push(db.op.keys[d]):0===db.op.keys[d].indexOf(b+"-")&&a.push(db.op.keys[d]);a.sort(function(a,b){a=a.split("-");b=b.split("-");1===a.length&&a.push(0);1===b.length&&b.push(0);return a[0]<b[0]?-1:a[0]>b[0]?1:Number(a[1])<Number(b[1])?-1:1});return a},main=function(){document.querySelector(".add-btn").addEventListener("click",function(){openModalPrompt()});document.querySelector(".close-btn").addEventListener("click",
function(){gtag("event","\ub300\uc6d0 \ucd94\uac00 \ud504\ub86c\ud504\ud2b8 \ub2eb\uae30: \ubc84\ud2bc \ud074\ub9ad",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"});closeModalPrompt(!0)});window.addEventListener("mousedown",function(b){"modal"===b.target.getAttribute("id")&&(gtag("event","\ub300\uc6d0 \ucd94\uac00 \ud504\ub86c\ud504\ud2b8 \ub2eb\uae30: \uc678\ubd80 \ud074\ub9ad",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"}),
closeModalPrompt(!0))});document.getElementById("opname").addEventListener("keyup",function(b){gtag_searchByNameUsed||(gtag_searchByNameUsed=!0,gtag("event","\ub300\uc6d0 \uc774\ub984\uc73c\ub85c \ucd5c\ucd08 \uac80\uc0c9",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"}));if(13===b.keyCode){for(;0<document.querySelectorAll(".search-result-op").length;)document.querySelector(".search-result-op").click();this.value="";searchingCondition.name=""}else{b=
"";for(var a=this.value.split(" "),d=0,e=a.length;d<e;++d)0!==a[d].length&&(0<d&&(b+=" "),b+=a[d][0].toUpperCase()+a[d].slice(1).toLowerCase());searchingCondition.name=b;showSearchResult()}});document.querySelectorAll(".rarity-btn").forEach(function(b){b.addEventListener("click",function(){gtag_searchByRarityUsed||(gtag_searchByRarityUsed=!0,gtag("event","\ub300\uc6d0 \ub808\uc5b4\ub3c4\ub85c \ucd5c\ucd08 \uac80\uc0c9",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"}));
var a=Number(this.getAttribute("name")),b=searchingCondition.rarityArray.indexOf(a);0<=b?(searchingCondition.rarityArray.splice(b,1),this.classList.remove("selected")):(searchingCondition.rarityArray.push(a),this.classList.add("selected"));showSearchResult()})});document.querySelectorAll(".class-btn").forEach(function(b){b.addEventListener("click",function(){gtag_searchByClassUsed||(gtag_searchByClassUsed=!0,gtag("event","\ub300\uc6d0 \ud074\ub798\uc2a4\ub85c \ucd5c\ucd08 \uac80\uc0c9",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"}));
var a=getTagCodeByKRTagName(this.getAttribute("name"));a&searchingCondition.tagCode?this.classList.remove("selected"):this.classList.add("selected");searchingCondition.tagCode^=a;showSearchResult()})});loadLocalStorage()},getTextWidth=function(b){var a="font-size:"+b.css("font-size")+";";a+="font-family:"+b.css("font-family")+";";b=$('<span style="'+a+'">'+b.html()+"</span>").appendTo("body");a=b.width();b.remove();return a},centerCnt=0,centerCacheHit=0,centerCache={},csp=[],ncsp=[],centerTime=0,
doNotCenter=!1,centerSelect=function(b){if(!doNotCenter){centerTime=Date.now();var a=b.options[b.selectedIndex].innerText,d=centerCache[a];d?(b.style.textIndent=d,csp.push(Date.now()-centerTime)):(d=$(b),b=getTextWidth($(b.options[b.selectedIndex])),b=(d.width()-b)/2,d.css("text-indent",b),centerCache[a]=b+"px",ncsp.push(Date.now()-centerTime))}},makeOpForm=function(b,a){a=void 0===a?{}:a;var d={},e=!0;a||(a={});"object"===typeof a.values&&(d=a.values);"boolean"===typeof a.asElement&&(e=a.asElement);
var c=Number(db.op[b].rarity);a=[0,0,1,2,2,2][c-1];var g=getMaxLevel(a,c),f=[4,7,7][a];db.op[b].name.en.toLowerCase();var m=Number.isInteger(d["current-elite"])?d["current-elite"]:0,k=Number.isInteger(d["target-elite"])?d["target-elite"]:a,l=Number.isInteger(d["current-op-level"])?d["current-op-level"]:1,h=Number.isInteger(d["target-op-level"])?d["target-op-level"]:g,A=[];if(d["current-skill-level"]){d["current-skill-level"].forEach(function(a){A.push(1<=a&&10>=a?a:1)});g=0;for(var w=3-A.length;g<
w;++g)A.push(1)}else A=[1,1,1];var r=[];if(d["target-skill-level"])for(d["target-skill-level"].forEach(function(a){r.push(1<=a&&10>=a?a:f)}),g=0,w=3-r.length;g<w;++g)r.push(f);else r=[f,f,f];d='<div class="remove-op thumb rarity_'+c+'"><img alt='+db.op[b].releaseOrder+' src="./images/op/thumb/'+db.op[b].releaseOrder+'.png"></div><div class="elite"><span>\uc815\uc608\ud654</span><br><select class="current-elite">';for(g=0;g<=a;++g)d+='<option value="'+g+'"',g===m&&(d+=" selected"),d+=">"+g+"\ub2e8\uacc4</option>";
d+='</select><span> \u25b8 </span><select class="target-elite">';for(g=0;g<=a;++g)d+='<option value="'+g+'"',g===k&&(d+=" selected"),d+=">"+g+"\ub2e8\uacc4</option>";d=d+'</select></div><div class="opLevel"><hr><button type="button" class="set-current-op-level-to-max-btn">MAX</button><span> \ub808\ubca8 </span><button type="button" class="set-target-op-level-to-max-btn">MAX</button><br><input type="text" class="current-op-level" value="'+(l+'"><span> \u25b8 </span><input type="text" class="target-op-level" value="')+
(h+'"></div><hr>');a=getNumOfSkills(b);if(0<a)for(d+="<span>\uc2a4\ud0ac \ub808\ubca8</span><br>",d+='<div class="skill">',g=1;g<=a;++g){1<g&&(d+="<br>");d+="<span>"+g+"\uc2a4\ud0ac </span>";d+='<select class="current-skill-level" data-index="'+(g-1)+'">';for(m=1;10>=m;++m)d+='<option value="'+m+'"',m===A[g-1]&&(d+="selected"),d+=">"+m+"</option>";d+="</select>";d+="<span> \u25b8 </span>";d+='<select class="target-skill-level" data-index="'+(g-1)+'">';for(m=1;10>=m;++m)d+='<option value="'+m+'"',
m===r[g-1]&&(d+="selected"),d+=">"+m+"</option>";d+="</select>"}d+="</div></div>";return e?(e=document.createElement("div"),e.classList.add("op"),e.setAttribute("name","op_"+b),e.innerHTML=d,e):'<div class="op" name="op_'+b+'">'+d+"</div>"},convertOldIDToNewID=function(){gtag("event","ID \uccb4\uacc4 \uc804\ud658(\ubc84\uc804 1\uc5d0\uc11c 2\ub85c)",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"});var b={0:"LN02",1:"RL03",2:"LT77",3:"RE41",4:"LM04",5:"AZ01",
6:"JC01",7:"AA01",8:"FO03",9:"FO01",10:"PL03",11:"SS02",12:"LM20",13:"SR02",14:"RL06",15:"LM05",16:"NM01",17:"RL02",18:"GG01",19:"R001",20:"VC03",21:"SK01",22:"RR01",23:"SR27",24:"R137",25:"BS01",26:"GG03",27:"SR01",28:"RB01",29:"AA02",30:"LM08",31:"R132",32:"SS01",33:"RL04",34:"RL01",35:"R106",36:"AA03",37:"LT01",38:"ST01",39:"R110",40:"ST03",41:"KZ03",42:"SR03",43:"JC06",44:"YD01",45:"SG01",46:"SW01",47:"LM16",48:"LM12",49:"R130",50:"R128",51:"RL05",52:"JC05",53:"PL05",54:"USS2",55:"LM15",56:"PL04",
57:"LM19",58:"BS02",59:"FO02",60:"MN02",61:"VC05",62:"HT03",63:"PL02",64:"USS1",65:"SI01",66:"R119",67:"VC02",68:"US10",69:"R100",70:"IU04",71:"R123",72:"HK01",73:"VC04",74:"IU07",75:"R104",76:"MN03",77:"R107",78:"LT02",79:"BS03",80:"VC01",81:"ST02",82:"LM10",83:"R122",84:"KZ04",85:"RB02",86:"LM11",87:"AA04",88:"LN01",89:"IU05",90:"R124",91:"JC03",92:"USS3",93:"JC04",94:"R108",95:"SW02",96:"R105",97:"PA15",98:"PA42",99:"PA41",100:"PA62",101:"PA65",102:"PA43",103:"PA13",104:"PA44",105:"PA63",106:"PA12",
107:"PA61",108:"PA14",109:"PA45",110:"PA64",111:"PA11",112:"LT05",113:"BS04",114:"R303",115:"A44",116:"A43",117:"A41",118:"A42",119:"RCX3",120:"RCX2"},a=Object.keys(localStorage).filter(function(a){return 0<=a.indexOf("optotal_")}),d="",e="",c="";d="";for(var g=0,f=a.length;g<f;++g)c=a[g].split("_"),d=c[1],c[1]=b[d],c[1]?(c=c.join("_"),e=a[g],d=localStorage.getItem(e),localStorage.setItem(c,d),localStorage.removeItem(e)):console.error(d+": \uc624\ud37c\ub808\uc774\ud130 ID \uccb4\uacc4 \ucd5c\uc2e0\ud654 \uc2e4\ud328. \ub9e4\uce6d\ub418\ub294 ID\uac00 \uc874\uc7ac\ud558\uc9c0 \uc54a\uc74c.");
localStorage.setItem("version_optotal_localStorage",JSON.stringify(db.idVersion.op))},sleep=function(b){return new Promise(function(a,d){setTimeout(a,b)})},loadLocalStorage=function(){console.log("loadLocalStorage");JSON.parse(localStorage.getItem("version_optotal_localStorage")||"1")<db.idVersion.op&&(console.log("\uc624\ud37c\ub808\uc774\ud130 ID \uccb4\uacc4 \ucd5c\uc2e0\ud654 \uc218\ud589"),convertOldIDToNewID());for(var b="current-elite target-elite current-op-level target-op-level current-skill-level target-skill-level".split(" "),
a={IDs:[]},d=0;d<db.op.keys.length;++d){var e=db.op.keys[d],c="optotal_"+e+"_";a[e]=[];for(var g=!1,f=0;f<b.length;++f)null!==localStorage.getItem(c+b[f])&&(a[e].push(b[f]),g=!0);g&&a.IDs.push(e)}if(0===a.IDs.length)document.getElementById("content-body").style.opacity=1,console.log("loadComplete");else{document.getElementById("selected-op-guide").style.display="none";a.IDs.sort(function(a,b){if(Number(db.op[a].rarity)>Number(db.op[b].rarity))return-1;if(Number(db.op[a].rarity)<Number(db.op[b].rarity))return 1;
a=a.split("-");b=b.split("-");if(a[0]<b[0])return-1;if(a[0]>b[0])return 1;1===a.length&&a.push(0);1===b.length&&b.push(0);return Number(a[1])<Number(b[1])?-1:1});Date.now();doNotRefreshResult=!0;b="";d=0;for(e=a.IDs.length;d<e;++d)b+='<div class="op" name="'+a.IDs[d]+'" style="color:#bbb;text-align:center;"><pre>\n\n\n\nLoading...</pre></div>';document.getElementById("selected-op").innerHTML=b;document.getElementById("content-body").style.opacity=1;setTimeout(function(){for(var b="",c=0,d=a.IDs.length;c<
d;++c){for(var e=a.IDs[c],f="optotal_"+e+"_",g={keys:[]},r=0,z=a[e].length;r<z;++r){var p=a[e][r],x=JSON.parse(localStorage.getItem(f+p));g[p]=x;g.keys.push(p)}b+=makeOpForm(e,{values:g,asElement:!1})}c=document.getElementById("selected-op");c.innerHTML=b;doNotCenter=!0;c.querySelectorAll(".op").forEach(function(a){addOpEventListener(a,!0)});doNotRefreshResult=!1;showResult();console.log("loadComplete")},0)}},removeAllInputData=function(b){gtag("event","\ubaa8\ub4e0 \uc785\ub825 \ub370\uc774\ud130 \uc0ad\uc81c: \ubc84\ud2bc \ud074\ub9ad",
{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"});confirm("\uc8fc\uc758: \uc774 \uc791\uc5c5\uc740 \ub418\ub3cc\ub9b4 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4.\n\uc815\ub9d0 \uc774 \uc11c\ube44\uc2a4\uc758 \ubaa8\ub4e0 \ub370\uc774\ud130\ub97c \uc0ad\uc81c\ud558\uc2dc\uaca0\uc2b5\ub2c8\uae4c?")?(Object.keys(localStorage).filter(function(a){return 0<=a.indexOf("optotal_")}).forEach(function(a){return localStorage.removeItem(a)}),location.reload()):(gtag("event",
"\ubaa8\ub4e0 \uc785\ub825 \ub370\uc774\ud130 \uc0ad\uc81c: \ucde8\uc18c",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"}),alert("\ub370\uc774\ud130 \uc0ad\uc81c\uac00 \ucde8\uc18c\ub418\uc5c8\uc2b5\ub2c8\ub2e4."))},triggerEvent=function(b,a,d){d=void 0===d?null:d;null!==d?b.dispatchEvent(new CustomEvent(a,{detail:d})):b.dispatchEvent(new CustomEvent(a))},getMaxElite=function(b){return[0,0,1,2,2,2][b-1]},getNumOfSkills=function(b,a){a=void 0===a?null:
a;var d=db.op[b].rarity;null===a&&(a=getMaxElite(d));if(null===db.op[b].skill){var e=b.split("-")[0];if(e===b||null===db.op[e].skill)return console.error("\ub2e4\uc74c \uc6d0\ubcf8 \uc624\ud37c\ub808\uc774\ud130\uc758 skill \uac12\uc774 null\uc784:",b),0;b=e}b=2<=getMaxElite(d)?db.op[b].skill.mastery.length:[0,0,1,2,2,3][d-1];e=[1,2,3][a];void 0===e&&(console.error("elite \uac12\uc5d0 \ubb38\uc81c \uc788\uc74c:",a),e=[1,2,3][getMaxElite(d)]);e>b&&(e=b);return e},getMaxSkillLevel=function(b){return[4,
7,10][b]},opFormRecalcHandler=function(b){var a=this.getAttribute("name").split("_")[1],d=a.split("-")[0],e=a===d,c={};document.querySelectorAll('#selected-op [name^="op_'+d+'"]').forEach(function(a){var b=a.getAttribute("name").split("_")[1];c[b]={};c[b].form=a;c[b].currentEliteElem=a.querySelectorAll(".current-elite")[0];c[b].targetEliteElem=a.querySelectorAll(".target-elite")[0];c[b].currentLevelElem=a.querySelectorAll(".current-op-level")[0];c[b].targetLevelElem=a.querySelectorAll(".target-op-level")[0];
c[b].currentSkillLevelElems=a.querySelectorAll(".current-skill-level");c[b].targetSkillLevelElems=a.querySelectorAll(".target-skill-level");c[b].currentElite=Number(a.querySelector(".current-elite").value);c[b].targetElite=Number(a.querySelector(".target-elite").value);c[b].currentLevel=Number(a.querySelector(".current-op-level").value);c[b].targetLevel=Number(a.querySelector(".target-op-level").value);c[b].currentSkillLevels=Array.from(a.querySelectorAll(".current-skill-level"),function(a){return Number(a.value)});
c[b].targetSkillLevels=Array.from(a.querySelectorAll(".target-skill-level"),function(a){return Number(a.value)})});if(!e){var g=null===db.op[a].elite;var f=null===db.op[a].skill}g&&(c[a].currentElite=c[d].currentElite,c[a].targetElite=c[d].targetElite,c[a].currentLevel=c[d].currentLevel,c[a].targetLevel=c[d].targetLevel,c[a].currentEliteElem.disabled=!0,c[a].targetEliteElem.disabled=!0,c[a].currentLevelElem.disabled=!0,c[a].targetLevelElem.disabled=!0,this.querySelectorAll(".set-current-op-level-to-max-btn, .set-target-op-level-to-max-btn").forEach(function(a){return a.disabled=
!0}),this.querySelectorAll(".elite, .opLevel").forEach(function(a){return a.style.opacity=0}));f&&(c[a].currentSkillLevels=[].concat($jscomp.arrayFromIterable(c[d].currentSkillLevels)),c[a].targetSkillLevels=[].concat($jscomp.arrayFromIterable(c[d].targetSkillLevels)),c[a].currentSkillLevelElems.forEach(function(a){a.disabled=!0}),c[a].targetSkillLevelElems.forEach(function(a){a.disabled=!0}),this.querySelector(".skill").style.opacity=0);g=[c[a].currentElite,c[a].targetElite,c[a].currentLevel,c[a].targetLevel].concat($jscomp.arrayFromIterable(c[a].currentSkillLevels),
$jscomp.arrayFromIterable(c[a].targetSkillLevels));var m=this.dataset.inputValue;m=m?m.split(",").map(Number):[];var k=!1;d=0;for(var l=g.length;d<l;++d)if(g[d]!==m[d]){k=!0;break}if(k){g=Number(db.op[a].rarity);k=getNumOfSkills(a);l=null;l=b.detail&&b.detail.from?b.detail.from:{type:"all"};if("all"===l.type)d=b=m=!0;else{if("elite"===l.type)d=b=m=!0;else if("level"===l.type)m=!1,b=!0,d=!1;else if("skill"===l.type){if(b=m=!1,d=!0,!Number.isInteger(l.index)||0>l.index||3<=l.index){console.error("\uc778\ub371\uc2a4 \uc624\ub958:",
l.index);return}}else{console.error("\ud0c0\uc785 \uc624\ub958:",l.type);return}if("current"!==l.position&&"target"!==l.position){console.error("\ud3ec\uc9c0\uc158 \uc624\ub958:",l.position);return}}f&&(d=!1);m&&(f=getMaxElite(g),c[a].currentElite>f&&(c[a].currentElite=f),c[a].targetElite>f&&(c[a].targetElite=f),c[a].targetElite<c[a].currentElite&&(c[a].targetElite=c[a].currentElite));if(d){f=getMaxSkillLevel(c[a].currentElite);for(var h=0;h<k;++h)c[a].currentSkillLevels[h]>f&&(c[a].currentSkillLevels[h]=
f);if("skill"===l.type&&"current"===l.position){var A=c[a].currentSkillLevels[l.index];if(7>A)for(var w in c)c[w].currentSkillLevels=c[w].currentSkillLevels.map(function(a){return A});else for(var r in c)c[r].currentSkillLevels=c[r].currentSkillLevels.map(function(a){return 7>a?7:a})}else{var z=-Infinity;for(x in c){w=getNumOfSkills(x,c[x].currentElite);for(r=0;r<w&&(z=c[x].currentSkillLevels[r]>z?c[x].currentSkillLevels[r]:z,z=7<z?7:z,7!==z);++r);if(7===z)break}for(var p in c)c[p].currentSkillLevels=
c[p].currentSkillLevels.map(function(a){return a<z?z:a})}var x=getMaxSkillLevel(c[a].targetElite);for(p=0;p<k;++p)c[a].targetSkillLevels[p]<c[a].currentSkillLevels[p]?c[a].targetSkillLevels[p]=c[a].currentSkillLevels[p]:c[a].targetSkillLevels[p]>x&&(c[a].targetSkillLevels[p]=x);if("skill"===l.type&&"target"===l.position){var E=c[a].targetSkillLevels[l.index];if(7>E)for(var u in c)c[u].targetSkillLevels=c[u].targetSkillLevels.map(function(a){return E});else for(var q in c)c[q].targetSkillLevels=c[q].targetSkillLevels.map(function(a){return 7>
a?7:a})}else{var C=-Infinity;for(v in c){u=getNumOfSkills(v,c[v].targetElite);for(q=0;q<u&&(C=c[v].targetSkillLevels[q]>C?c[v].targetSkillLevels[q]:C,C=7<C?7:C,7!==C);++q);if(7===C)break}for(var t in c)c[t].targetSkillLevels=c[t].targetSkillLevels.map(function(a){return a<C?C:a})}}if(b){var v=getMaxLevel(c[a].currentElite,g);c[a].currentLevel>v&&(c[a].currentLevel=v);1>c[a].currentLevel&&(c[a].currentLevel=1);v=getMaxLevel(c[a].targetElite,g);c[a].targetLevel>v&&(c[a].targetLevel=v);c[a].currentElite===
c[a].targetElite&&c[a].targetLevel<c[a].currentLevel?c[a].targetLevel=c[a].currentLevel:1>c[a].targetLevel&&(c[a].targetLevel=1)}if(m){v=null;for(var B in c){t=getMaxElite(db.op[B].rarity);v=c[B].currentEliteElem.options;u=0;for(q=t;u<q;++u)v[u].disabled=u>t?!0:!1;c[B].currentEliteElem.value=c[B].currentElite;v=c[B].targetEliteElem.options;u=0;for(q=v.length;u<q;++u)v[u].disabled=u<c[B].currentElite||u>t?!0:!1;c[B].targetEliteElem.value=c[B].targetElite}}if(d)for(var n in c){B=getNumOfSkills(n);t=
getNumOfSkills(n,c[n].currentElite);d=getNumOfSkills(n,c[n].targetElite);u=getMaxSkillLevel(c[n].currentElite);v=getMaxSkillLevel(c[n].targetElite);for(q=0;q<t;++q){c[n].currentSkillLevelElems[q].disabled=!1;x=c[n].currentSkillLevelElems[q].options;p=0;for(g=x.length;p<g;++p)x[p].disabled=p>=u?!0:!1;c[n].currentSkillLevelElems[q].value=c[n].currentSkillLevels[q]}for(;t<B;++t)c[n].currentSkillLevelElems[t].disabled=!0,c[n].currentSkillLevelElems[t].value=c[n].currentSkillLevels[t];for(t=0;t<d;++t){c[n].targetSkillLevelElems[t].disabled=
!1;u=c[n].targetSkillLevelElems[t].options;q=0;x=u.length;for(p=c[n].currentSkillLevels[t]-1;q<x;++q)u[q].disabled=q<p||q>=v?!0:!1;c[n].targetSkillLevelElems[t].value=c[n].targetSkillLevels[t]}for(;d<B;++d)c[n].targetSkillLevelElems[d].disabled=!0,c[n].targetSkillLevelElems[d].value=c[n].targetSkillLevels[d]}if(b)for(var D in c)c[D].currentLevelElem.value=c[D].currentLevel,c[D].targetLevelElem.value=c[D].targetLevel;for(var y in c)c[y].form.dataset.inputValue=[c[y].currentElite,c[y].targetElite,c[y].currentLevel,
c[y].targetLevel].concat($jscomp.arrayFromIterable(c[y].currentSkillLevels),$jscomp.arrayFromIterable(c[y].targetSkillLevels)).join(","),n="optotal_"+y+"_",localStorage.setItem(n+"current-elite",JSON.stringify(c[y].currentElite)),localStorage.setItem(n+"current-op-level",JSON.stringify(c[y].currentLevel)),localStorage.setItem(n+"current-skill-level",JSON.stringify(c[y].currentSkillLevels)),localStorage.setItem(n+"target-elite",JSON.stringify(c[y].targetElite)),localStorage.setItem(n+"target-op-level",
JSON.stringify(c[y].targetLevel)),localStorage.setItem(n+"target-skill-level",JSON.stringify(c[y].targetSkillLevels));if(e)for(a=document.querySelectorAll('#selected-op [name^="op_'+a+'-"]'),d=0;d<a.length;++d)triggerEvent(a[d],"recalc");showResult()}else console.log("return")},removeOpMousedownHandler=function(){var b=this.closest(".op").getAttribute("name").split("_")[1].split("-")[0];document.querySelectorAll('#selected-op [name^="op_'+b+'"]').forEach(function(a){return a.style.opacity=.4})},removeOpMouseoverHandler=
function(){var b=this.closest(".op").getAttribute("name").split("_")[1].split("-")[0];document.querySelectorAll('#selected-op [name^="op_'+b+'"]').forEach(function(a){return a.style.opacity=.7})},removeOpMouseoutHandler=function(){var b=this.closest(".op").getAttribute("name").split("_")[1].split("-")[0];document.querySelectorAll('#selected-op [name^="op_'+b+'"]').forEach(function(a){return a.style.opacity=1})},removeOpClickHandler=function(){gtag("event","\uc624\ud37c\ub808\uc774\ud130 \uc0ad\uc81c: \ubc84\ud2bc \ud074\ub9ad",
{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"});this.closest(".op");var b=this.closest(".op").getAttribute("name").split("_")[1];b=getAllIDs(b);for(var a=0;a<b.length;++a){document.querySelector('#selected-op [name="op_'+b[a]+'"]').remove();for(var d="optotal_"+b[a]+"_",e="current-elite target-elite current-op-level target-op-level current-skill-level target-skill-level".split(" "),c=0;c<e.length;++c)localStorage.removeItem(d+e[c])}null===document.querySelector('div[name*="op_"].op')&&
(document.getElementById("selected-op-guide").style.display="block");showResult()},setCurrentOpLevelToMaxHandler=function(){gtag("event","\ud604\uc7ac \ub808\ubca8 \ucd5c\ub300 \uc124\uc815",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"});if(!this.disabled){var b=this.closest(".op"),a=b.getAttribute("name").split("_")[1],d=b.querySelector(".current-op-level");if(a in db.op){var e=Number(b.querySelector(".current-elite").value);a=getMaxLevel(e,Number(db.op[a].rarity));
d.value=a;triggerEvent(b,"recalc",{from:{type:"level",position:"current"}})}else console.error("\uc5d0\ub7ec: \ucde8\ub4dd\ud55c \uc624\ud37c\ub808\uc774\ud130 \uc544\uc774\ub514("+a+")\ub97c DB\uc5d0\uc11c \ucc3e\uc744 \uc218 \uc5c6\uc74c")}},setTargetOpLevelToMaxHandler=function(){gtag("event","\ubaa9\ud45c \ub808\ubca8 \ucd5c\ub300 \uc124\uc815",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"});if(!this.disabled){var b=this.closest(".op"),a=b.getAttribute("name").split("_")[1],
d=b.querySelector(".target-op-level");if(a in db.op){var e=Number(b.querySelector(".target-elite").value);a=getMaxLevel(e,Number(db.op[a].rarity));d.value=a;triggerEvent(b,"recalc",{from:{type:"level",position:"target"}})}else console.error("\uc5d0\ub7ec: \ucde8\ub4dd\ud55c \uc624\ud37c\ub808\uc774\ud130 \uc544\uc774\ub514("+a+")\ub97c DB\uc5d0\uc11c \ucc3e\uc744 \uc218 \uc5c6\uc74c")}},currentEliteChangeHandler=function(){this.disabled||triggerEvent(this.closest(".op"),"recalc",{from:{type:"elite",
position:"current"}})},targetEliteChangeHandler=function(){this.disabled||triggerEvent(this.closest(".op"),"recalc",{from:{type:"elite",position:"target"}})},currentOpLevelChangeHandler=function(){this.disabled||triggerEvent(this.closest(".op"),"recalc",{from:{type:"level",position:"current"}})},targetOpLevelChangeHandler=function(){this.disabled||triggerEvent(this.closest(".op"),"recalc",{from:{type:"level",position:"target"}})},currentSkillLevelChangeHandler=function(b){this.disabled||triggerEvent(this.closest(".op"),
"recalc",{from:{type:"skill",position:"current",index:Number(b.target.dataset.index)}})},targetSkillLevelChangeHandler=function(){this.disabled||triggerEvent(this.closest(".op"),"recalc",{from:{type:"skill",position:"target",index:Number(event.target.dataset.index)}})},addOpEventListener=function(b,a){a=void 0===a?!1:a;b.addEventListener("recalc",opFormRecalcHandler);b.querySelector(".remove-op").addEventListener("mousedown",removeOpMousedownHandler);b.querySelector(".remove-op").addEventListener("mouseover",
removeOpMouseoverHandler);b.querySelector(".remove-op").addEventListener("mouseout",removeOpMouseoutHandler);b.querySelector(".remove-op").addEventListener("click",removeOpClickHandler);b.querySelector(".set-current-op-level-to-max-btn").addEventListener("click",setCurrentOpLevelToMaxHandler);b.querySelector(".set-target-op-level-to-max-btn").addEventListener("click",setTargetOpLevelToMaxHandler);b.querySelector(".current-elite").addEventListener("change",currentEliteChangeHandler);b.querySelector(".target-elite").addEventListener("change",
targetEliteChangeHandler);b.querySelector(".current-op-level").addEventListener("change",currentOpLevelChangeHandler);b.querySelector(".target-op-level").addEventListener("change",targetOpLevelChangeHandler);b.querySelectorAll(".current-skill-level").forEach(function(a){a.addEventListener("change",currentSkillLevelChangeHandler)});b.querySelectorAll(".target-skill-level").forEach(function(a){a.addEventListener("change",targetSkillLevelChangeHandler)});a&&triggerEvent(b,"recalc",{from:{type:"all"}})},
searchingCondition={name:"",rarityArray:[],tagCode:0},getTagCodeByKRTagName=function(b){for(var a=0;a<db.tag.keys.length;++a)if(db.tag[db.tag.keys[a]].name.kr==b)return Number(db.tag[db.tag.keys[a]].tagCode)},showSearchResult=function(){searchingCondition.rarityArray.sort(function(a,b){return a>b?-1:1});for(var b=searchOp(searchingCondition.name,searchingCondition.rarityArray,searchingCondition.tagCode),a=[],d=0,e=b.keys.length,c="";d<e;++d)c=b.keys[d],a.push([b[c].name.kr,c]);a.sort(function(a,b){return a[0].localeCompare(b[0])});
b="";for(d=0;d<a.length;++d)b+='<div class="search-result-op" name="op_'+a[d][1]+'"><img src="./images/op/thumb/'+db.op[a[d][1]].releaseOrder+'.png"><div><span>'+a[d][0]+"</span></div></div>";""==b&&(b='<p style="font-size: 0.5em; text-align: center">\uac80\uc0c9 \uacb0\uacfc\uac00 \uc874\uc7ac\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.</p>');document.querySelector(".modal-footer>.search-result").innerHTML=b;document.querySelectorAll(".search-result-op").forEach(function(a){a.addEventListener("click",
function(){for(var a=this.getAttribute("name").split("_")[1],b=a.split("-")[0],c=getAllIDs(a),d=0;d<c.length;++d)if(console.log(c[d],"\ucd94\uac00"),"optotal_"+c[d]+"_current-elite"in localStorage)console.error(a+": \uc774\ubbf8 \ucd94\uac00\ub41c \uc624\ud37c\ub808\uc774\ud130");else{var e=makeOpForm(c[d],{values:{},asElement:!0});document.getElementById("selected-op").appendChild(e);addOpEventListener(e,!0);document.getElementById("selected-op-guide").style.display="none";gtag("event","\uc624\ud37c\ub808\uc774\ud130 \ucd94\uac00",
{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"})}a=document.querySelectorAll('.search-result-op[name^="op_'+b+'"]');for(d=0;d<a.length;++d)a[d].remove();0===document.querySelectorAll(".modal-footer>.search-result>.search-result-op").length&&(document.querySelector(".modal-footer>.search-result").innerHTML='<p style="font-size: 0.5em; text-align: center">\uac80\uc0c9 \uacb0\uacfc\uac00 \uc874\uc7ac\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.</p>')})});document.querySelectorAll(".search-result-op div").forEach(function(a){$(a).textfill()})};
(function(b){b.fn.textfill=function(a){a=parseInt(a,10);return this.each(function(){function d(){var b=e.parent(),d=b.height(),f=b.width();b=parseInt(e.css("font-size"),10);f/=e.width();var m=b*(f-.1);f=d/e.height();a=b*(f-.1);e.css("fontSize",0<a&&m>a?a:m)}var e=b("span",this);b(window).resize(function(){"block"===document.querySelector(".modal").style.display&&d()});d()})}})(jQuery);
var searchOp=function(b,a,d){b=b.replace(/(\s*)/g,"").toLowerCase();var e=0<b.length,c=0<a.length,g=0!=d;if(!(e||c||g))return{keys:[]};for(var f={},m=Object.keys(localStorage).filter(function(a){return 0===a.indexOf("optotal_")}),k=0,l=db.op.keys.length,h="",A="";k<l;++k){h=db.op.keys[k];A="optotal_"+h;for(var w=0,r=m.length;w<r&&0!==m[w].indexOf(A);++w);w<r||(f[h]={},f[h].rarity=db.op[h].rarity,f[h].tagCode=db.op[h].tagCode,f[h].name={},f[h].name.kr=db.op[h].name.kr,f[h].name.en=db.op[h].name.en,
f[h].name.jp=db.op[h].name.jp,f[h].name.cn=db.op[h].name.cn)}f.keys=Object.keys(f);if(e)for(k=0,l=f.keys.length,h="";k<l;++k)h=f.keys[k],0>f[h].name.kr.replace(/(\s*)/g,"").toLowerCase().indexOf(b)&&0>f[h].name.en.replace(/(\s*)/g,"").toLowerCase().indexOf(b)&&0>f[h].name.jp.replace(/(\s*)/g,"").toLowerCase().indexOf(b)&&0>f[h].name.cn.replace(/(\s*)/g,"").toLowerCase().indexOf(b)&&(delete f[h],f.keys.splice(k,1),--k,--l);if(c)for(b=!1,k=0,e=f.keys.length,h="";k<e;++k){h=f.keys[k];b=!1;w=0;for(r=
a.length;w<r;++w)if(rarity=a[w],f[h].rarity==rarity){b=!0;break}b||(delete f[h],f.keys.splice(k,1),--k,--e)}if(g)for(k=0,l=f.keys.length,h="";k<l;++k)h=f.keys[k],d&f[h].tagCode||(delete f[h],f.keys.splice(k,1),--k,--l);return f},addResultToMcalc=function(b){var a=fetchInputData();if(!1===a)showTooltip("\uc804\uc1a1\ud560 \ub370\uc774\ud130\uac00 \uc874\uc7ac\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4",b.target,"error");else if(gtag("event","\uc7ac\ub8cc \uacc4\uc0b0\uae30\ub85c \uc804\uc1a1 \uc2dc\uc791",
{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"}),confirm("\uacb0\uacfc \ub370\uc774\ud130\ub97c \uc804\uc1a1\ud558\uc2dc\ub824\uba74 \ud655\uc778 \ubc84\ud2bc\uc744 \ub20c\ub7ec\uc8fc\uc2ed\uc2dc\uc624.")){a=sortResultData(calc(a));for(var d=0;d<a.total.IDs.length;++d){var e=Number(a.total.IDs[d]),c=Number(a.total[e]);c+=JSON.parse(localStorage.getItem("mcalc_item-need_"+e));localStorage.setItem("mcalc_item-need_"+e,JSON.stringify(c))}showTooltip("\uc131\uacf5\uc801\uc73c\ub85c \uacb0\uacfc \ub370\uc774\ud130\ub97c \uc804\uc1a1\ud558\uc600\uc2b5\ub2c8\ub2e4",
b.target,"success");confirm("\uc131\uacf5\uc801\uc73c\ub85c \uacb0\uacfc \ub370\uc774\ud130\ub97c \uc804\uc1a1\ud558\uc600\uc2b5\ub2c8\ub2e4.\n\ubc14\ub85c \uc7ac\ub8cc \uacc4\uc0b0\uae30\ub85c \uc774\ub3d9\ud558\uc2dc\uaca0\uc2b5\ub2c8\uae4c?")&&("1"==localStorage.getItem("preferred-version_mcalc")?location.href="mcalc-legacy.html":location.href="mcalc.html")}else gtag("event","\uc7ac\ub8cc \uacc4\uc0b0\uae30\ub85c \uc804\uc1a1 \ucde8\uc18c",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"}),
showTooltip("\ub370\uc774\ud130 \uc804\uc1a1\uc774 \ucde8\uc18c\ub418\uc5c8\uc2b5\ub2c8\ub2e4",b.target,"error")};main();
