var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};
$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var e=a.split(".");a=1===e.length;d=e[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<e.length-1;f++){var g=e[f];if(!(g in d))return;d=d[g]}e=e[e.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[e]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+e,e=
$jscomp.propertyToPolyfillSymbol[e],$jscomp.defineProperty(d,e,{configurable:!0,writable:!0,value:b})))};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var c=0,d=function(a){if(this instanceof d)throw new TypeError("Symbol is not a constructor");return new b("jscomp_symbol_"+(a||"")+"_"+c++,a)};return d},"es6","es3");$jscomp.initSymbolIterator=function(){};
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=$jscomp.global[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&$jscomp.defineProperty(d.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.initSymbolAsyncIterator=function(){};$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,b){a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};
$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
var generateTagCodes=function(a,b,c,d,e,f,g){e="undefined"===typeof e?0:e;f="undefined"===typeof f?0:f;g="undefined"===typeof g?0:g;if(e>=c)return b[d]=g,d+1;for(;f<a.length;++f)d=generateTagCodes(a,b,c,d,e+1,f+1,g|a[f]);return d},getAvailableOperatorIDs=function(a){var b=[],c=0,d=function(a){for(var b=0;b<db.tag.keys.length;++b)if(a==db.tag[db.tag.keys[b]].name.kr)return db.tag[db.tag.keys[b]].tagCode;console.error("\uc8fc\uc5b4\uc9c4 \ud0dc\uadf8\uba85\uc744 DB\uc5d0\uc11c \ucc3e\uc9c0 \ubabb\ud568: ",
a);return!1},e=d("\uace0\uae09\ud2b9\ubcc4\ucc44\uc6a9");d=d("\ud2b9\ubcc4\ucc44\uc6a9");if(!1===e||!1===d)return!1;for(var f=0;f<db.op.keys.length;++f){var g=db.op[db.op.keys[f]];(a&g.tagCode)==a&&(0!=(e&a)?6===g.rarity&&(b[c++]=db.op.keys[f]):0!=(d&a)?5===g.rarity&&(b[c++]=db.op.keys[f]):6>g.rarity&&(b[c++]=db.op.keys[f]))}return b.filter(function(a){return 0<=recrWhiteList.kr.indexOf(a)})},getLowestRarity=function(a){for(var b=0,c=a.length-1;0<=c;--c){b=db.op[a[c]].rarity;if(3<=b)break;if(0===
c){b=db.op[a[a.length-1]].rarity;break}}return b},calc=function(a){if(0===a.length)return[];for(var b=0;b<a.length;++b)if(0>a[b]||a[b]>=db.tag.keys.length)return[];var c=[],d=[];for(b=0;b<a.length;++b)c[b]=db.tag[a[b]].tagCode;b=1;for(var e=0;b<=a.length;++b)e=generateTagCodes(c,d,b,e);a=[];c=function(a,b){var c=db.op[a].rarity,d=db.op[b].rarity;if(c>d)return-1;if(c<d)return 1;a=db.op[a].name[getLang()];b=db.op[b].name[getLang()];return a<b?-1:a>b?1:0};for(var f=e=b=0,g=[],h=null;b<d.length;++b)f=
d[b],g=getAvailableOperatorIDs(d[b]),0<g.length&&(g.sort(c),h={},h.tagCode=f,h.opIDs=g,h.lowestRarity=getLowestRarity(g),a[e++]=h);a.sort(function(a,b){var c=a.opIDs,d=b.opIDs;a=a.lowestRarity;b=b.lowestRarity;if(a>b)return-1;if(a<b)return 1;b=db.op[c[0]].rarity;a=db.op[d[0]].rarity;return b>a?-1:b<a?1:c.length<d.length?-1:c.length>d.length?1:0});return a};
