var LANG="kr",SERVER="kr",getLang=function(){return LANG},getServer=function(){return SERVER},recrWhiteList={kr:"RCX2 RCX3 A41 A43 A42 A44 R303 PA44 PA11 BS04 LT05 PA41 PA14 PA12 PA15 PA13 PA43 PA42 PA61 IU04 VC02 SI01 BS03 ST02 LM10 SW02 R105 R100 HK01 R123 VC04 KZ04 RB02 R104 MN03 JC03 IU05 USS3 LN01 LM11 GG03 MN02 RL04 USS1 PL02 AA02 AA03 KZ03 ST03 RL05 RL01 R106 FO02 SW01 BS02 PL04 SR03 ST01 JC06 JC05 USS2 SG01 YD01 PL03 GG01 RL03 FO01 FO03 LM05 RL02 JC01".split(" ")};
recrWhiteList.en=recrWhiteList.jp=recrWhiteList.kr;recrWhiteList.cn=[];
var displayImg="none",displayName=!0,displayRarity=!0,filterRarity=[1,2,3,4,5,6],useBatchSelector=!0,loadConfig=function(){displayImg=JSON.parse(localStorage.getItem("recr_display_img"));displayName=JSON.parse(localStorage.getItem("recr_display_name"));displayRarity=JSON.parse(localStorage.getItem("recr_display_rarity"));filterRarity=JSON.parse(localStorage.getItem("recr_filter_rarity"));useBatchSelector=JSON.parse(localStorage.getItem("recr_use_batchSelector"));displayImg="string"!==typeof displayImg?
"none":displayImg;displayImg=displayImg.toLowerCase();displayImg=0>"tiny|small|medium|large".indexOf(displayImg)?"none":displayImg;displayName="boolean"!==typeof displayName?!0:displayName;displayRarity="boolean"!==typeof displayRarity?!0:displayRarity;useBatchSelector="boolean"!==typeof useBatchSelector?!0:useBatchSelector;filterRarity=Array.isArray(filterRarity)?filterRarity:[];selectConfig()},selectConfig=function(){$("#display_img_"+displayImg).prop("checked",!0);$("#display_name_"+String(displayName)).prop("checked",
!0);$("#display_rarity_"+String(displayRarity)).prop("checked",!0);$("#use_batchSelector_"+String(useBatchSelector)).prop("checked",!0);for(var a=1;6>=a;++a)0<=filterRarity.indexOf(a)?$("#filter_rarity_"+String(a)).prop("checked",!1):$("#filter_rarity_"+String(a)).prop("checked",!0)},fetchConfig=function(){displayImg=$('#config-modal [name="display_img"]:checked').attr("id").split("_")[2];displayName=JSON.parse($('#config-modal [name="display_name"]:checked').attr("id").split("_")[2]);displayRarity=
JSON.parse($('#config-modal [name="display_rarity"]:checked').attr("id").split("_")[2]);useBatchSelector=JSON.parse($('#config-modal [name="use_batchSelector"]:checked').attr("id").split("_")[2]);filterRarity=[];$filterRarityList=$('#config-modal [name="filter_rarity"]:not(:checked)');for(var a=0;a<$filterRarityList.length;++a)filterRarity.push(Number($filterRarityList.eq(a).attr("id").split("_")[2]));localStorage.setItem("recr_display_img",JSON.stringify(displayImg));localStorage.setItem("recr_display_name",
JSON.stringify(displayName));localStorage.setItem("recr_display_rarity",JSON.stringify(displayRarity));localStorage.setItem("recr_use_batchSelector",JSON.stringify(useBatchSelector));localStorage.setItem("recr_filter_rarity",JSON.stringify(filterRarity))},openConfigModal=function(){selectConfig();$("#config-modal").css("display","block");$("#config-modal").css("opacity","1")},closeConfigModal=function(){fetchConfig();var a=document.getElementById("tagBatchSelector-container");!0===useBatchSelector?
a.style.display="block":!1===useBatchSelector&&(a.style.display="none");showResult();$("#config-modal").css("opacity","0");setTimeout(function(){$("#config-modal").css("display","none")},300)};
$(document).ready(function(){loadConfig();var a=document.getElementById("tagBatchSelector-container");!0===useBatchSelector?a.style.display="block":!1===useBatchSelector&&(a.style.display="none");$(".menu-btn").click(function(){openConfigModal()});$(".close-btn").click(function(){closeConfigModal()});$(window).click(function(a){$(a.target).is($("#config-modal"))&&closeConfigModal()})});
