var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,d){a.raw=d;return a};
var e={leftDay:0,leftHour:0},t={doWork:0,doLive:0},f={live:{dif2m:{},dif2mp:{},dif4m:{},dif6m:{},difmm:{}},eventLive:{dif2m:{},dif2mp:{},dif4m:{},dif6m:{},difmm:{}},promotion:{dif2m:{},dif2mp:{},dif4m:{},dif6m:{},difmm:{}},work:{dif15:{},dif20:{},dif25:{},dif30:{}},elegant:{}},p={},playInfo={routine:{live:0,work:0},promotion:{dif:0,mul:0},elegant:{dif:0,mul:0}},playCnt={live:0,work:0,elegant:0},targetPoint=0,getEventData=function(){e.leftDay=Number(document.getElementById("left_day").value);e.leftHour=
Number(document.getElementById("left_hour").value)},getTimeData=function(){t.doWork=Number(document.getElementById("timeData_doWork").value);t.doLive=Number(document.getElementById("timeData_doLive").value)},getTargetPoint=function(){targetPoint=Number(document.getElementById("playerData_target").value)},getPlayInfo=function(){playInfo.routine.work=Number(document.getElementById("promotionRoutine").value);playInfo.routine.live=3-playInfo.routine.work;playInfo.promotion.dif=document.getElementById("promotionDif").value;
playInfo.promotion.mul=1;playInfo.elegant.dif=document.getElementById("elegantDif").value;playInfo.elegant.mul=1},setFundamentalData=function(){f.live.dif2m.cons=15;f.live.dif2m.fan=60;f.live.dif2m.money=630;f.live.dif2m.affection=12;f.live.dif2m.exp=150;f.live.dif2mp.cons=25;f.live.dif2mp.fan=100;f.live.dif2mp.money=1200;f.live.dif2mp.affection=24;f.live.dif2mp.exp=260;f.live.dif4m.cons=20;f.live.dif4m.fan=78;f.live.dif4m.money=900;f.live.dif4m.affection=18;f.live.dif4m.exp=204;f.live.dif6m.cons=
25;f.live.dif6m.fan=97;f.live.dif6m.money=1200;f.live.dif6m.affection=24;f.live.dif6m.exp=260;f.live.difmm.cons=30;f.live.difmm.fan=120;f.live.difmm.money=1350;f.live.difmm.affection=30;f.live.difmm.exp=306;f.eventLive=JSON.parse(JSON.stringify(f.live));f.work.dif15.cons=15;f.work.dif15.point=0;f.work.dif15.fan=30;f.work.dif15.money=473;f.work.dif15.affection=7;f.work.dif15.exp=108;f.work.dif20.cons=20;f.work.dif20.point=0;f.work.dif20.fan=40;f.work.dif20.money=630;f.work.dif20.affection=9;f.work.dif20.exp=
143;f.work.dif25.cons=25;f.work.dif25.point=0;f.work.dif25.fan=50;f.work.dif25.money=788;f.work.dif25.affection=11;f.work.dif25.exp=179;f.work.dif30.cons=30;f.work.dif30.point=0;f.work.dif30.fan=60;f.work.dif30.money=945;f.work.dif30.affection=15;f.work.dif30.exp=215;f.live.dif2m.point=142;f.live.dif2mp.point=180;f.live.dif4m.point=161;f.live.dif6m.point=180;f.live.difmm.point=200;f.eventLive.dif2m.cons=20;f.eventLive.dif2mp.cons=20;f.eventLive.dif4m.cons=20;f.eventLive.dif6m.cons=20;f.eventLive.difmm.cons=
20;f.eventLive.dif2m.point=720;f.eventLive.dif2mp.point=720;f.eventLive.dif4m.point=720;f.eventLive.dif6m.point=720;f.eventLive.difmm.point=720;f.work.dif15.point=50;f.work.dif20.point=57;f.work.dif25.point=74;f.work.dif30.point=82;f.promotion.dif2m.item=20;f.promotion.dif2mp.item=40;f.promotion.dif4m.item=30;f.promotion.dif6m.item=40;f.promotion.difmm.item=50;f.elegant.cons_stamina=20;f.elegant.cons_item=100;f.elegant.point=3E3},getPlayerData=function(){"level exp stamina drink10 drink20 drink30 mdrink jwl point item staminaUsage".split(" ").forEach(function(a){p[a]=
Number(document.getElementById("playerData_"+a).value)});["fan","money","affection"].forEach(function(a){p[a]=0})},getMaxStamina=function(a){a=a||p.level;return 60>a?60+parseInt(a/2,10):150>a?90+parseInt((a-60)/3,10):426>a?120+parseInt((a-150)/4,10):586>a?189+parseInt((a-426)/5,10):700>a?221+parseInt((a-586)/6,10):240},getMaxExp=function(a){return 100*p.level-50},checkExp=function(){for(var a;;)if(a=getMaxExp(p.level),p.exp>=a)p.exp-=a,p.level+=1,p.stamina+=getMaxStamina();else break},r={live:{cons:0,
point:0,fan:0,money:0,affection:0},work:{cons:0,point:0,fan:0,money:0,affection:0},promotion:{item:0},elegant:{cons_stamina:0,cons_item:0,point:0}},setRealData=function(){var a=playInfo.promotion,d=playInfo.elegant,b="dif"+a.dif,c=a.mul;r.live.cons=c*f.live[b].cons;r.live.point=c*f.live[b].point;r.live.fan=f.live[b].fan;r.live.money=f.live[b].money;r.live.affection=f.live[b].affection;r.live.exp=f.live[b].exp;r.promotion.item=c*f.promotion[b].item;b="dif"+d.dif;r.elegant.cons_item=f.elegant.cons_item;
r.elegant.cons_stamina=f.elegant.cons_stamina;r.elegant.point=f.elegant.point;r.elegant.fan=f.live[b].fan;r.elegant.money=f.live[b].money;r.elegant.affection=f.live[b].affection;r.elegant.exp=f.live[b].exp;b="dif"+{"2m":15,"4m":20,"2mp":25,"6m":25,mm:30}[a.dif];r.work.cons=c*f.work[b].cons;r.work.point=c*f.work[b].point;r.work.fan=f.work[b].fan;r.work.money=f.work[b].money;r.work.affection=f.work[b].affection;r.work.exp=f.work[b].exp};
function fetch(){getEventData();getTimeData();getTargetPoint();getPlayInfo();getPlayerData();setFundamentalData();setRealData();var a=document.getElementById("recvDrink").checked;p.stamina+=parseInt(parseInt((1440*e.leftDay+60*e.leftHour)/5,10)*p.staminaUsage/100,10);p.stamina+=120*e.leftDay;a||(p.stamina+=120);21<=e.leftHour&&(p.stamina+=120);playCnt={live:0,work:0,elegant:0}}
function calc(){for(fetch();p.point<targetPoint;){for(;p.item<r.elegant.cons_item;)doPromotion();for(;p.item>=r.elegant.cons_item;)doElegant()}}
function rechargeStamina(){if(0>p.stamina){if(0<p.drink30||0<p.drink20||0<p.drink10){var a=[30,20,10],d;for(d=0;d<a.length;++d){var b=a[d];if(0<p["drink"+b]){var c=Math.ceil(-p.stamina/b);p["drink"+b]<c&&(c=p["drink"+b]);p.stamina+=b*c;p["drink"+b]-=c}if(0<=p.stamina)break}}a=getMaxStamina(p.level);0<p.mdrink&&(c=Math.ceil(-p.stamina/a),p.mdrink<c&&(c=p.mdrink),p.stamina+=a*c,p.mdrink-=c);c=Math.ceil(-p.stamina/a);p.stamina+=a*c;p.jwl-=50*c}}
function doPromotion(){p.stamina-=playInfo.routine.live*r.live.cons;p.point+=playInfo.routine.live*r.live.point;p.fan+=playInfo.routine.live*r.live.fan;p.money+=playInfo.routine.live*r.live.money;p.affection+=playInfo.routine.live*r.live.affection;p.exp+=playInfo.routine.live*r.live.exp;playCnt.live+=playInfo.routine.live;p.stamina-=playInfo.routine.work*r.work.cons;p.point+=playInfo.routine.work*r.work.point;p.fan+=playInfo.routine.work*r.work.fan;p.money+=playInfo.routine.work*r.work.money;p.affection+=
playInfo.routine.work*r.work.affection;p.exp+=playInfo.routine.work*r.work.exp;playCnt.work+=playInfo.routine.work;p.item+=r.promotion.item;checkExp();rechargeStamina()}function doElegant(){p.item-=r.elegant.cons_item;p.stamina-=r.elegant.cons_stamina;p.point+=r.elegant.point;p.fan+=r.elegant.fan;p.money+=r.elegant.money;p.affection+=r.elegant.affection;p.exp+=r.elegant.exp;playCnt.elegant++;checkExp();rechargeStamina()};