var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
var providedConfigs=[{title:"\uc9c0\uc5ed \uc124\uc815",id:"locale",configs:[{title:"\uc11c\ubc84",id:"region",exclusive:!0,options:[{title:"\ud55c\uad6d",value:"kr","default":!0},{title:"\uc911\uad6d",value:"cn"},{title:"\uc77c\ubcf8",value:"jp"},{title:"\uae00\ub85c\ubc8c",value:"en"}]},{title:"\uc5b8\uc5b4",id:"lang",exclusive:!0,options:[{title:"\ud55c\uad6d\uc5b4",value:"kr","default":!0},{title:"\uc911\uad6d\uc5b4",value:"cn"},{title:"\uc77c\ubcf8\uc5b4",value:"jp"},{title:"\uc601\uc5b4",value:"en"}]}]},
{title:"\uc785\ub825 \uc124\uc815",id:"input",configs:[{title:"\ud0dc\uadf8 \uc785\ub825\uae30",id:"batchSelector",exclusive:!0,options:[{title:"\uc0ac\uc6a9",value:!0,"default":!0},{title:"\ubbf8\uc0ac\uc6a9",value:!1}]},{title:"\ud0dc\uadf8 \ucd08\uae30\ud654 \ud6c4 \uc790\ub3d9 \ud3ec\ucee4\uc2a4",id:"autoFocusBatchSelector",exclusive:!0,options:[{title:"\uc0ac\uc6a9",value:!0},{title:"\ubbf8\uc0ac\uc6a9",value:!1,"default":!0}]}]},{title:"\ud45c\uc2dc \uc124\uc815",id:"display",configs:[{title:"\uc774\ubbf8\uc9c0",
id:"image",exclusive:!0,options:[{title:"\uc5c6\uc74c",value:"none","default":!0},{title:"\ub9e4\uc6b0 \uc791\uac8c",value:"tiny"},{title:"\uc791\uac8c",value:"small"},{title:"\uc911\uac04",value:"medium"},{title:"\ud06c\uac8c",value:"large"}]},{title:"\uc774\ub984",id:"name",exclusive:!0,options:[{title:"\ud45c\uc2dc",value:!0,"default":!0},{title:"\ube44\ud45c\uc2dc",value:!1}]},{title:"\ub808\uc5b4\ub3c4",id:"rarity",exclusive:!0,options:[{title:"\ud45c\uc2dc",value:!0,"default":!0},{title:"\ube44\ud45c\uc2dc",
value:!1}]},{title:"\uac00\uc774\ub4dc \ud328\ub110",id:"guidePanel",exclusive:!0,options:[{title:"\ud45c\uc2dc",value:!0,"default":!0},{title:"\ube44\ud45c\uc2dc",value:!1}]}]},{title:"\ud544\ud130 \uc124\uc815",id:"filter",configs:[{title:"\ud5c8\uc6a9 \ub808\uc5b4\ub3c4",id:"rarity",exclusive:!1,options:[{title:"1\uc131",value:1,"default":!0},{title:"2\uc131",value:2,"default":!0},{title:"3\uc131",value:3,"default":!0},{title:"4\uc131",value:4,"default":!0},{title:"5\uc131",value:5,"default":!0},
{title:"6\uc131",value:6,"default":!0}]}]}],saveToStorage=function(a,b){localStorage.setItem("recr_"+a,JSON.stringify(b))},loadFromStorage=function(a,b){b=void 0===b?null:b;var e=localStorage.getItem("recr_"+a)||b;return null!==e?JSON.parse(e):{}},userConfig={},saveUserConfig=function(){saveToStorage("userConfig",userConfig)},loadUserConfig=function(){userConfig=loadFromStorage("userConfig");for(var a=0,b=providedConfigs.length;a<b;++a){var e=providedConfigs[a];userConfig[e.id]||(userConfig[e.id]=
{});for(var f=0,d=e.configs.length;f<d;++f){var c=e.configs[f];if(void 0===userConfig[e.id][c.id]||void 0===userConfig[e.id][c.id].value){userConfig[e.id][c.id]={};!0===c.exclusive?userConfig[e.id][c.id].exclusive=!0:(userConfig[e.id][c.id].exclusive=!1,userConfig[e.id][c.id].value=[]);for(var g=0,h=c.options.length;g<h;++g)if(!0===c.options[g]["default"])if(!0===c.exclusive){userConfig[e.id][c.id].value=c.options[g].value;break}else userConfig[e.id][c.id].value.push(c.options[g].value)}}}},setConfigModal=
function(){for(var a=document.createDocumentFragment(),b=0,e=providedConfigs.length;b<e;++b){var f=providedConfigs[b],d=document.createElement("div");d.style.fontSize="90%";d.classList.add("user-config-category");d.dataset.id=f.id;d.innerHTML+='<hr style="border-color:#444;display:inline-block"><span style="font-size: 0.9em">'+f.title+"</span><br><br>";for(var c=0,g=f.configs.length;c<g;++c){var h=f.configs[c],k=document.createElement("div");k.classList.add("user-config-config");k.dataset.id=h.id;
k.innerHTML+='<span style="font-size: 0.75em;color:#eee">'+h.title+"</span><br>";for(var m=0,r=h.options.length;m<r;++m){var p=h.options[m],q=["user-config-",f.id,h.id,m.toString()].join("-"),l=document.createElement("input");l.classList.add("checkboxButton","user-config-option");l.dataset.value=JSON.stringify(p.value);l.setAttribute("id",q);l.setAttribute("name",h.id);!0===h.exclusive?l.setAttribute("type","radio"):l.setAttribute("type","checkbox");var n=document.createElement("label");n.className=
"tag";n.innerText=p.title;n.setAttribute("for",q);k.appendChild(l);k.appendChild(n)}d.appendChild(k)}a.appendChild(d)}document.querySelector(".modal-body").appendChild(a)},selectUserConfig=function(){Object.keys(userConfig);for(var a=document.querySelectorAll(".user-config-option"),b=0;b<a.length;++b){var e=a[b],f=$jscomp.makeIterator(e.getAttribute("id").split("--")[1].split("-")),d=f.next().value,c=f.next().value;f=JSON.parse(e.dataset.value);if(userConfig[d]&&userConfig[d][c])if(!0===userConfig[d][c].exclusive&&
f===userConfig[d][c].value)e.checked=!0;else{d=userConfig[d][c].value;c=0;for(var g=d.length;c<g;++c)if(d[c]===f){e.checked=!0;break}}}},fetchUserConfig=function(){for(var a=Object.keys(userConfig),b=0,e=a.length;b<e;++b)for(var f=Object.keys(userConfig[a[b]]),d=0,c=f.length;d<c;++d)!1===userConfig[a[b]][f[d]].exclusive&&(userConfig[a[b]][f[d]].value=[]);a=document.querySelectorAll(".user-config-option:checked");b=0;for(e=a.length;b<e;++b)d=a[b],c=$jscomp.makeIterator(d.getAttribute("id").split("--")[1].split("-")),
f=c.next().value,c=c.next().value,d=JSON.parse(d.dataset.value),void 0===userConfig[f]&&(userConfig[f]={}),!0===userConfig[f][c].exclusive?userConfig[f][c].value=d:userConfig[f][c].value.push(d);saveUserConfig();loadUserConfig()},openConfigModal=function(){gtag("event","\uc124\uc815 \ud504\ub86c\ud504\ud2b8 \uc5f4\uae30",{event_category:"\uacf5\uac1c\ubaa8\uc9d1 \uacc4\uc0b0\uae30"});selectUserConfig();document.getElementById("config-modal").style.display="block";document.getElementById("config-modal").style.opacity=
"1"},checkBatchSelectorOption=function(){var a=document.getElementById("tagBatchSelector-container"),b=userConfig.input.batchSelector.value;console.log(b);a.style.display=!1===b?"none":"block"},checkGuidePanelOption=function(){var a=document.querySelectorAll(".guide-panel");!1===userConfig.display.guidePanel.value?(a.forEach(function(b){b.style.display="none"}),$("#result-panel").prepend('<div class="panel"></div>')):a.forEach(function(b){b.style.display="block"})},closeConfigModal=function(){fetchUserConfig();
checkBatchSelectorOption();checkGuidePanelOption();document.getElementById("tag-top").dataset.lang!=userConfig.locale.region.value&&configSelectionPanel();showResult();document.getElementById("config-modal").style.opacity="0";setTimeout(function(){document.getElementById("config-modal").style.display="none"},300)};document.querySelector(".menu-btn").addEventListener("click",openConfigModal);
document.querySelector(".close-btn").addEventListener("click",function(){gtag("event","\uc124\uc815 \ud504\ub86c\ud504\ud2b8 \ub2eb\uae30: \ubc84\ud2bc \ud074\ub9ad",{event_category:"\uacf5\uac1c\ubaa8\uc9d1 \uacc4\uc0b0\uae30"});closeConfigModal()});
window.addEventListener("click",function(a){a.target.isSameNode(document.getElementById("config-modal"))&&(gtag("event","\uc124\uc815 \ud504\ub86c\ud504\ud2b8 \ub2eb\uae30: \uc678\ubd80 \ud074\ub9ad",{event_category:"\uacf5\uac1c\ubaa8\uc9d1 \uacc4\uc0b0\uae30"}),closeConfigModal())});setConfigModal();loadUserConfig();checkBatchSelectorOption();checkGuidePanelOption();gtag("event","\uc124\uc815\ub41c \uc11c\ubc84: "+userConfig.locale.region.value,{event_category:"\uacf5\uac1c\ubaa8\uc9d1 \uacc4\uc0b0\uae30"});
gtag("event","\uc124\uc815\ub41c \uc5b8\uc5b4: "+userConfig.locale.lang.value,{event_category:"\uacf5\uac1c\ubaa8\uc9d1 \uacc4\uc0b0\uae30"});