var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,c){a.raw=c;return a};$jscomp.arrayIteratorImpl=function(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return c?c.call(a):$jscomp.arrayIterator(a)};
$jscomp.arrayFromIterator=function(a){for(var c,f=[];!(c=a.next()).done;)f.push(c.value);return f};$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};
var refreshTargetInput=function(){for(var a="",c,f=0,d=6;3<=d;--d){c=Number(document.querySelectorAll("#star-"+d+" input")[3].value);for(var b=0;b<c;++b)a+=' <div class="tag">'+d+'\u2605<input placeholder="\ub300\uc6d0_'+f+'">:<input style="width: 1em; text-align: right" value="1">\ud68c</div><br>',++f}document.querySelector("#target-input").innerHTML=a},fetchData=function(){var a={};a.stack=Number(document.getElementById("stack").value);a.prob={total:{},pickup:{}};a.numOfChar={nonPickup:{},pickup:{}};
a.target={nonPickup:{},pickup:{}};for(var c=0,f=[].concat($jscomp.arrayFromIterable(document.querySelectorAll("#target-input .tag"))).map(function(a){return Number(a.querySelectorAll("input")[1].value)}),d=6;3<=d;--d){var b=[].concat($jscomp.arrayFromIterable(document.querySelectorAll("#star-"+d+" input"))).map(function(a){return Number(a.value)});a.prob.total[d]=b[0]/100;a.prob.pickup[d]=b[1]/100;a.numOfChar.pickup[d]=b[2];a.target.nonPickup[d]=[];a.target.pickup[d]=[];for(var g=0;g<b[3];++g)a.target.pickup[d].push(f[c++])}return a},
simulationResult=[],simulate=function(a,c){a=void 0===a?1E3:a;c=void 0===c?5E4:c;for(var f=Date.now(),d=fetchData(),b=0,g=6;3<=g;--g)b+=d.target.nonPickup[g].length+d.target.pickup[g].length;if(!(0>=b)){b=0;var n=d.prob,m=d.numOfChar,k=d.target,u=0>document.getElementById("five-star-guarantee").className.indexOf("off"),p=[],q=[];simulationResult=[];var e=0,l=0,r=0;b=0;for(var h in k)for(b=50;99>=b;++b)for(l=0,p[b]=[],g=6;3<=g;--g)for(r=0;r<k[h][g].length;++r)e=n.total[g],e=6==g?e+.02*(b-50):(1-(n.total[6]+
.02*(b-50)))/(1-n.total[6])*e,e="pickup"==h?e*n.pickup[g]/m.pickup[g]:e*(1-n.pickup[g])/(m.total[g]-m.pickup[g]),0<l&&(e+=p[b][l-1]),p[b][l]=e,50==b&&(q[l]=-k[h][g][r]),++l;m=b=e=h=g=0;l=k.nonPickup[6].length+k.pickup[6].length;k=k.nonPickup[5].length+k.pickup[5].length;r=[].concat($jscomp.arrayFromIterable(q));var t=!1;for(m=d.stack;;)if(++g,b=++m,b=50<b?b:50,h=Math.random(),99<b)console.log(b),m=0;else{if(u&&!t&&10===g)h<n.total[6]+.02*(b-50)?(h=Math.floor(Math.random()*l*2),h<l&&++q[h],m=0):(h=
Math.floor(Math.random()*k*2),h<k&&++q[l+h],t=!0);else{for(e=0;e<p[b].length;++e)if(h<p[b][e]){e<l?m=0:0<k&&e<l+k&&(t=!0);++q[e];break}e===p[b].length&&(e=p[b][p[b].length-1]+n.total[6]+.02*(b-50)-(0<l?p[b][l-1]:0),h<e?m=0:t||h<e+(1-(n.total[6]+.02*(b-50)))/(1-n.total[6])*n.total[5]-(0<k?p[b][k-1]:0)&&(t=!0))}for(e=0;e<q.length&&!(0>q[e]);++e);if(e==q.length&&(simulationResult.push(g),g=0,m=d.stack,t=!1,q=[].concat($jscomp.arrayFromIterable(r)),0===simulationResult.length%1E3&&(simulationResult.length>=
c||Date.now()-f>=a)))break}simulationResult=simulationResult.sort(function(a,b){return Number(a)<Number(b)?-1:1});showResult()}},getQuantile=function(a,c){if(0===a.length)return 0;c=Math.ceil(a.length*c);c=c>=a.length?a.length-1:c;return a[c]},getPercentile=function(a,c){if(0===a.length)return 0;for(var f=0,d=a.length-1,b;;){b=Math.floor((f+d)/2);if(f>=d)break;if(a[b]<c)f=b+1;else if(a[b]===c)break;else d=b-1}for(f=b;f<a.length;++f)if(a[f]>c){b=f-1;break}return(b+1)/a.length},showResult=function(a){for(var c=
[].concat($jscomp.arrayFromIterable(document.querySelectorAll(".result-panel table input"))).map(function(a){return Number(a.value)/100}),f=document.querySelectorAll(".result-panel tr")[1].querySelectorAll("td"),d=0;d<c.length;++d)f[d].innerText=getQuantile(simulationResult,c[d]);c=document.getElementById("draw");f=document.getElementById("prob");void 0!==a?"draw"==a.target.id?f.value=Math.round(1E3*getPercentile(simulationResult,Number(c.value)))/10:"prob"==a.target.id&&(c.value=getQuantile(simulationResult,
Number(f.value)/100)):f.value=Math.round(1E3*getPercentile(simulationResult,Number(c.value)))/10},toggleFiveStarGuarantee=function(a){0>a.className.indexOf("off")?a.className="off":a.className=""},main=function(){for(var a=6;3<=a;--a)document.querySelectorAll("#star-"+a+" input")[3].addEventListener("keyup",refreshTargetInput);a=document.querySelectorAll(".result-panel input");for(var c=0;c<a.length;++c)a[c].addEventListener("keyup",showResult)};main();
