var displayName=!0,displayInputField=!0,displayGuide=!0,breakdownGrade=0,filterGrade=[],filterCategory=[],filterOnlyLack=!1;
const loadConfig=function(){displayName=JSON.parse(localStorage.getItem("mcalc_display_name"));displayInputField=JSON.parse(localStorage.getItem("mcalc_display_inputField"));displayGuide=JSON.parse(localStorage.getItem("mcalc_display_guide"));breakdownGrade=JSON.parse(localStorage.getItem("mcalc_breakdown_grade"));filterGrade=JSON.parse(localStorage.getItem("mcalc_filter_grade"));filterCategory=JSON.parse(localStorage.getItem("mcalc_filter_category"));filterOnlyLack=JSON.parse(localStorage.getItem("mcalc_filter_onlyLack"));
displayName="boolean"!==typeof displayName?!0:displayName;displayInputField="boolean"!==typeof displayInputField?!0:displayInputField;displayGuide="boolean"!==typeof displayGuide?!0:displayGuide;breakdownGrade="number"!==typeof breakdownGrade?0:breakdownGrade;filterGrade=Array.isArray(filterGrade)?filterGrade:[];filterCategory=Array.isArray(filterCategory)?filterCategory:[];filterOnlyLack="boolean"!==typeof filterOnlyLack?!1:filterOnlyLack;selectConfig()},selectConfig=function(){displayName?$("#display_name").prop("checked",
!0):$("#display_name").prop("checked",!1);displayInputField?$("#display_inputField").prop("checked",!0):$("#display_inputField").prop("checked",!1);displayGuide?$("#display_guide").prop("checked",!0):$("#display_guide").prop("checked",!1);document.getElementById("breakdown_grade").value=breakdownGrade;refreshBtnFilterOnlyLack();for(var a=1;5>=a;++a)0>filterGrade.indexOf(a)?$("#filter_grade_"+String(a)).prop("checked",!0):$("#filter_grade_"+String(a)).prop("checked",!1);for(a=0;3>=a;++a)0>filterCategory.indexOf(a)?
$("#filter_category_"+String(a)).prop("checked",!0):$("#filter_category_"+String(a)).prop("checked",!1)},fetchConfig=function(){displayName=JSON.parse($("#display_name").prop("checked"));displayInputField=JSON.parse($("#display_inputField").prop("checked"));displayGuide=JSON.parse($("#display_guide").prop("checked"));breakdownGrade=Number($("#breakdown_grade").val());filterGrade=[];$filterGradeList=$('#config-modal [name="filter_grade"]:not(:checked)');for(var a=0;a<$filterGradeList.length;++a)filterGrade.push(Number($filterGradeList.eq(a).attr("id").split("_")[2]));
filterCategory=[];$filterCategoryList=$('#config-modal [name="filter_category"]:not(:checked)');for(a=0;a<$filterCategoryList.length;++a)filterCategory.push(Number($filterCategoryList.eq(a).attr("id").split("_")[2]));localStorage.setItem("mcalc_display_name",JSON.stringify(displayName));localStorage.setItem("mcalc_display_inputField",JSON.stringify(displayInputField));localStorage.setItem("mcalc_display_guide",JSON.stringify(displayGuide));localStorage.setItem("mcalc_breakdown_grade",JSON.stringify(breakdownGrade));
localStorage.setItem("mcalc_filter_grade",JSON.stringify(filterGrade));localStorage.setItem("mcalc_filter_category",JSON.stringify(filterCategory));localStorage.setItem("mcalc_filter_onlyLack",JSON.stringify(filterOnlyLack))},openConfigModal=function(){gtag("event","\uc124\uc815 \ud504\ub86c\ud504\ud2b8 \uc5f4\uae30",{event_category:"\uc7ac\ub8cc \uacc4\uc0b0\uae30 2.0"});$("#config-modal").css("display","block").css("opacity","1");selectConfig()},closeConfigModal=function(){$("#config-modal").css("opacity",
"0");setTimeout(function(){$("#config-modal").css("display","none")},300);fetchConfig();applyConfig()};
$(document).ready(function(){loadConfig();applyConfig();$(".menu-btn").click(function(){openConfigModal()});$(".close-btn").click(function(){gtag("event","\uc124\uc815 \ud504\ub86c\ud504\ud2b8 \ub2eb\uae30: \ubc84\ud2bc \ud074\ub9ad",{event_category:"\uc7ac\ub8cc \uacc4\uc0b0\uae30 2.0"});closeConfigModal()});$(window).click(function(a){$(a.target).is($("#config-modal"))&&(gtag("event","\uc124\uc815 \ud504\ub86c\ud504\ud2b8 \ub2eb\uae30: \uc678\ubd80 \ud074\ub9ad",{event_category:"\uc7ac\ub8cc \uacc4\uc0b0\uae30 2.0"}),
closeConfigModal())});$("#config-modal").find("[name*=display_], [name*=filter_]").change(function(){fetchConfig();applyConfig()})});
