var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.arrayFromIterator=function(a){for(var b,h=[];!(b=a.next()).done;)h.push(b.value);return h};$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};var glob=glob||{namespace:"gacha",ga_event_category:"\uac00\ucc60 \uc2dc\ubbac\ub808\uc774\ud130"};window[glob.namespace]=window[glob.namespace]||{};
window[glob.namespace].refreshTargetInput=function(){for(var a="",b,h=0,d=6;3<=d;--d){b=Number(document.querySelectorAll("#star-"+d+" input")[3].value);for(var c=0;c<b;++c)a+=' <div class="tag">'+d+'\u2605<input placeholder="\ub300\uc6d0_'+h+'">:<input style="width: 1em; text-align: right" value="1">\ud68c</div><br>',++h}document.querySelector("#target-input").innerHTML=a};
window[glob.namespace].fetchData=function(){var a={};a.stack=Number(document.getElementById("stack").value);a.prob={total:{},pickup:{}};a.numOfChar={nonPickup:{},pickup:{}};a.target={nonPickup:{},pickup:{}};for(var b=0,h=[].concat($jscomp.arrayFromIterable(document.querySelectorAll("#target-input .tag"))).map(function(a){return Number(a.querySelectorAll("input")[1].value)}),d=6;3<=d;--d){var c=[].concat($jscomp.arrayFromIterable(document.querySelectorAll("#star-"+d+" input"))).map(function(a){return Number(a.value)});
a.prob.total[d]=c[0]/100;a.prob.pickup[d]=c[1]/100;a.numOfChar.pickup[d]=c[2];a.target.nonPickup[d]=[];a.target.pickup[d]=[];for(var g=0;g<c[3];++g)a.target.pickup[d].push(h[b++])}return a};window[glob.namespace].simulationResult=[];
window[glob.namespace].simulate=function(a,b){a=void 0===a?1E3:a;b=void 0===b?5E4:b;gtag("event","\uc2dc\ubbac\ub808\uc774\uc158 \uc2e4\ud589",{event_category:glob.ga_event_category});for(var h=Date.now(),d=fetchData(),c=0,g=6;3<=g;--g)c+=d.target.nonPickup[g].length+d.target.pickup[g].length;if(!(0>=c)){var e=0;c=d.prob;var m=d.numOfChar,l=d.target,u=0>document.getElementById("five-star-guarantee").className.indexOf("off"),v=0>document.getElementById("limited-pickup-list-price").className.indexOf("off"),
p=[],q=[];simulationResult=[];var f=0,k=0,r=0;e=0;for(var n in l)for(e=50;99>=e;++e)for(k=0,p[e]=[],g=6;3<=g;--g)for(r=0;r<l[n][g].length;++r)f=c.total[g],f=6==g?f+.02*(e-50):(1-(c.total[6]+.02*(e-50)))/(1-c.total[6])*f,f="pickup"==n?f*c.pickup[g]/m.pickup[g]:f*(1-c.pickup[g])/(m.total[g]-m.pickup[g]),0<k&&(f+=p[e][k-1]),p[e][k]=f,50==e&&(q[k]=-l[n][g][r]),++k;n=e=f=k=g=0;m=l.nonPickup[6].length+l.pickup[6].length;l=l.nonPickup[5].length+l.pickup[5].length;r=[].concat($jscomp.arrayFromIterable(q));
var t=!1;for(n=d.stack;;)if(++g,e=++n,e=50<e?e:50,k=Math.random(),99<e)console.log(e),n=0;else{if(u&&!t&&10===g)k<c.total[6]+.02*(e-50)?(k=Math.floor(Math.random()*m*2),k<m&&++q[k],n=0):(k=Math.floor(Math.random()*l*2),k<l&&++q[m+k],t=!0);else{for(f=0;f<p[e].length;++f)if(k<p[e][f]){f<m?n=0:0<l&&f<m+l&&(t=!0);++q[f];break}f===p[e].length&&(f=p[e][p[e].length-1]+c.total[6]+.02*(e-50)-(0<m?p[e][m-1]:0),k<f?n=0:t||k<f+(1-(c.total[6]+.02*(e-50)))/(1-c.total[6])*c.total[5]-(0<l?p[e][l-1]:0)&&(t=!0))}e=
v?Math.floor(g/300):0;for(f=0;f<q.length;++f)if(0>q[f]){if(f<m&&(e+=q[f],0<=e))continue;break}if(f==q.length&&(simulationResult.push(g),g=0,n=d.stack,t=!1,q=[].concat($jscomp.arrayFromIterable(r)),0===simulationResult.length%1E3&&(simulationResult.length>=b||Date.now()-h>=a)))break}simulationResult=simulationResult.sort(function(a,b){return Number(a)<Number(b)?-1:1});showResult()}};
window[glob.namespace].getQuantile=function(a,b){if(0===a.length)return 0;b=Math.ceil(a.length*b);b=b>=a.length?a.length-1:b;return a[b]};window[glob.namespace].getPercentile=function(a,b){if(0===a.length)return 0;for(var h=0,d=a.length-1,c;;){c=Math.floor((h+d)/2);if(h>=d)break;if(a[c]<b)h=c+1;else if(a[c]===b)break;else d=c-1}for(;c<a.length;++c)if(a[c]>b){--c;break}return(c+1)/a.length};
window[glob.namespace].showResult=function(a){gtag("event","\uacb0\uacfc \ucd9c\ub825",{event_category:glob.ga_event_category});for(var b=[].concat($jscomp.arrayFromIterable(document.querySelectorAll(".result-panel table input"))).map(function(a){return Number(a.value)/100}),h=document.querySelectorAll(".result-panel tr")[1].querySelectorAll("td"),d=0;d<b.length;++d)h[d].innerText=getQuantile(simulationResult,b[d]);b=document.getElementById("draw");h=document.getElementById("prob");void 0!==a?"draw"==
a.target.id?h.value=Math.round(1E3*getPercentile(simulationResult,Number(b.value)))/10:"prob"==a.target.id&&(b.value=getQuantile(simulationResult,Number(h.value)/100)):h.value=Math.round(1E3*getPercentile(simulationResult,Number(b.value)))/10};window[glob.namespace].toggleButton=function(a){0>a.className.indexOf("off")?a.className="off":a.className=""};
window[glob.namespace].main=function(){for(var a=6;3<=a;--a)document.querySelectorAll("#star-"+a+" input")[3].addEventListener("keyup",refreshTargetInput);a=document.querySelectorAll(".result-panel input");for(var b=0;b<a.length;++b)a[b].addEventListener("keyup",showResult)};window.errorCatcherExec=window.errorCatcherExec||[];try{window.errorCatcherExec.push("main")}catch(a){window.errorCatcherExec=[],window.errorCatcherExec.push("main")};
