const providedConfigs=[{title:"\uc9c0\uc5ed \uc124\uc815",id:"locale",configs:[{title:"\uc11c\ubc84",id:"region",exclusive:!0,options:[{title:"\ud55c\uad6d",value:"kr",default:!0},{title:"\uc911\uad6d",value:"cn"},{title:"\uc77c\ubcf8",value:"jp"},{title:"\uae00\ub85c\ubc8c",value:"en"}]},{title:"\uc5b8\uc5b4",id:"lang",exclusive:!0,options:[{title:"\ud55c\uad6d\uc5b4",value:"kr",default:!0},{title:"\uc911\uad6d\uc5b4",value:"cn"},{title:"\uc77c\ubcf8\uc5b4",value:"jp"},{title:"\uc601\uc5b4",value:"en"}]}]},
{title:"\uc785\ub825 \uc124\uc815",id:"input",configs:[{title:"\ud0dc\uadf8 \uc785\ub825\uae30",id:"batchSelector",exclusive:!0,options:[{title:"\uc0ac\uc6a9",value:!0,default:!0},{title:"\ubbf8\uc0ac\uc6a9",value:!1}]},{title:"\ud0dc\uadf8 \uc785\ub825\uae30 \uc790\ub3d9 \ud3ec\ucee4\uc2a4",id:"autoFocusBatchSelector",exclusive:!0,options:[{title:"\uc0ac\uc6a9",value:!0},{title:"\ubbf8\uc0ac\uc6a9",value:!1,default:!0}]}]},{title:"\ud45c\uc2dc \uc124\uc815",id:"display",configs:[{title:"\uc774\ubbf8\uc9c0",
id:"image",exclusive:!0,options:[{title:"\uc5c6\uc74c",value:"none",default:!0},{title:"\ub9e4\uc6b0 \uc791\uac8c",value:"tiny"},{title:"\uc791\uac8c",value:"small"},{title:"\uc911\uac04",value:"medium"},{title:"\ud06c\uac8c",value:"large"}]},{title:"\uc774\ub984",id:"name",exclusive:!0,options:[{title:"\ud45c\uc2dc",value:!0,default:!0},{title:"\ube44\ud45c\uc2dc",value:!1}]},{title:"\ub808\uc5b4\ub3c4",id:"rarity",exclusive:!0,options:[{title:"\ud45c\uc2dc",value:!0,default:!0},{title:"\ube44\ud45c\uc2dc",
value:!1}]},{title:"\uc0ac\uc6a9 \ubc29\ubc95",id:"guidePanel",exclusive:!0,options:[{title:"\ud45c\uc2dc",value:!0,default:!0},{title:"\ube44\ud45c\uc2dc",value:!1}]}]},{title:"\ud544\ud130 \uc124\uc815",id:"filter",configs:[{title:"\uace0\ub4f1\uae09 \ud655\uc815\uc2dd\ub9cc \ud45c\uc2dc",id:"onlyHighRarity",exclusive:!0,options:[{title:"\ucf1c\uae30",value:!0},{title:"\ub044\uae30",value:!1,default:!0}]},{title:"\ud5c8\uc6a9 \ub808\uc5b4\ub3c4",id:"rarity",exclusive:!1,options:[{title:"1\uc131",
value:1,default:!0},{title:"2\uc131",value:2,default:!0},{title:"3\uc131",value:3,default:!0},{title:"4\uc131",value:4,default:!0},{title:"5\uc131",value:5,default:!0},{title:"6\uc131",value:6,default:!0}]}]}];
var saveToStorage=function(a,b){localStorage.setItem("recr_"+a,JSON.stringify(b))},loadFromStorage=function(a,b=null){a=localStorage.getItem("recr_"+a)||b;return null!==a?JSON.parse(a):{}},userConfig={},saveUserConfig=function(){saveToStorage("userConfig",userConfig)},loadUserConfig=function(){userConfig=loadFromStorage("userConfig");for(var a=0,b=providedConfigs.length;a<b;++a){var d=providedConfigs[a];userConfig[d.id]||(userConfig[d.id]={});for(var c=0,f=d.configs.length;c<f;++c){var e=d.configs[c];
if(void 0===userConfig[d.id][e.id]||void 0===userConfig[d.id][e.id].value){userConfig[d.id][e.id]={};!0===e.exclusive?userConfig[d.id][e.id].exclusive=!0:(userConfig[d.id][e.id].exclusive=!1,userConfig[d.id][e.id].value=[]);for(var h=0,g=e.options.length;h<g;++h)if(!0===e.options[h].default)if(!0===e.exclusive){userConfig[d.id][e.id].value=e.options[h].value;break}else userConfig[d.id][e.id].value.push(e.options[h].value)}}}},setConfigModal=function(){for(var a=document.createDocumentFragment(),b=
0,d=providedConfigs.length;b<d;++b){var c=providedConfigs[b],f=document.createElement("div");f.style.fontSize="90%";f.classList.add("user-config-category");f.dataset.id=c.id;f.innerHTML+=`<hr style="border-color:#444;display:inline-block"><span style="font-size: 0.9em">${c.title}</span><br><br>`;for(var e=0,h=c.configs.length;e<h;++e){var g=c.configs[e],k=document.createElement("div");k.classList.add("user-config-config");k.dataset.id=g.id;k.innerHTML+='<span style="font-size: 0.75em;color:#eee">'+
g.title+"</span><br>";for(var m=0,r=g.options.length;m<r;++m){var p=g.options[m],q=["user-config-",c.id,g.id,m.toString()].join("-"),l=document.createElement("input");l.classList.add("checkboxButton","user-config-option");l.dataset.value=JSON.stringify(p.value);l.setAttribute("id",q);l.setAttribute("name",g.id);!0===g.exclusive?l.setAttribute("type","radio"):l.setAttribute("type","checkbox");var n=document.createElement("label");n.className="tag";n.innerText=p.title;n.setAttribute("for",q);k.appendChild(l);
k.appendChild(n)}f.appendChild(k)}a.appendChild(f)}document.querySelector(".modal-body").appendChild(a)},selectUserConfig=function(){Object.keys(userConfig);for(var a=document.querySelectorAll(".user-config-option"),b=0;b<a.length;++b){var d=a[b],[c,f]=d.getAttribute("id").split("--")[1].split("-"),e=JSON.parse(d.dataset.value);if(userConfig[c]&&userConfig[c][f])if(!0===userConfig[c][f].exclusive&&e===userConfig[c][f].value)d.checked=!0;else for(var h=userConfig[c][f].value,g=0,k=h.length;g<k;++g)if(h[g]===
e){d.checked=!0;break}}},fetchUserConfig=function(){for(var a=Object.keys(userConfig),b=0,d=a.length;b<d;++b)for(var c=Object.keys(userConfig[a[b]]),f=0,e=c.length;f<e;++f)!1===userConfig[a[b]][c[f]].exclusive&&(userConfig[a[b]][c[f]].value=[]);a=document.querySelectorAll(".user-config-option:checked");b=0;for(d=a.length;b<d;++b){c=a[b];var [h,g]=c.getAttribute("id").split("--")[1].split("-");c=JSON.parse(c.dataset.value);void 0===userConfig[h]&&(userConfig[h]={});!0===userConfig[h][g].exclusive?
userConfig[h][g].value=c:userConfig[h][g].value.push(c)}saveUserConfig();loadUserConfig();syncButtons()};
const openConfigModal=function(){gtag("event","\uc124\uc815 \ud504\ub86c\ud504\ud2b8 \uc5f4\uae30",{event_category:"\uacf5\uac1c\ubaa8\uc9d1 \uacc4\uc0b0\uae30"});selectUserConfig();document.getElementById("config-modal").style.display="block";document.getElementById("config-modal").style.opacity="1"},checkBatchSelectorOption=function(){var a=document.getElementById("tagBatchSelector-container"),b=userConfig.input.batchSelector.value;console.log(b);a.style.display=!1===b?"none":"block"},checkGuidePanelOption=
function(){var a=document.querySelectorAll(".guide-panel");!1===userConfig.display.guidePanel.value?(a.forEach(function(b){b.style.display="none"}),$("#result-panel").prepend('<div class="panel"></div>')):a.forEach(function(b){b.style.display="block"})},closeConfigModal=function(){fetchUserConfig();checkBatchSelectorOption();checkGuidePanelOption();document.getElementById("tag-top").dataset.lang!=userConfig.locale.region.value&&configSelectionPanel();showResult();document.getElementById("config-modal").style.opacity=
"0";setTimeout(function(){document.getElementById("config-modal").style.display="none"},300)};document.querySelector(".menu-btn").addEventListener("click",openConfigModal);document.querySelector(".close-btn").addEventListener("click",function(){gtag("event","\uc124\uc815 \ud504\ub86c\ud504\ud2b8 \ub2eb\uae30: \ubc84\ud2bc \ud074\ub9ad",{event_category:"\uacf5\uac1c\ubaa8\uc9d1 \uacc4\uc0b0\uae30"});closeConfigModal()});
window.addEventListener("click",function(a){a.target.isSameNode(document.getElementById("config-modal"))&&(gtag("event","\uc124\uc815 \ud504\ub86c\ud504\ud2b8 \ub2eb\uae30: \uc678\ubd80 \ud074\ub9ad",{event_category:"\uacf5\uac1c\ubaa8\uc9d1 \uacc4\uc0b0\uae30"}),closeConfigModal())});setConfigModal();loadUserConfig();checkBatchSelectorOption();checkGuidePanelOption();
gtag("event","\uc124\uc815\ub41c \uc11c\ubc84: "+userConfig.locale.region.value,{event_category:"\uacf5\uac1c\ubaa8\uc9d1 \uacc4\uc0b0\uae30",non_interaction:!0});gtag("event","\uc124\uc815\ub41c \uc5b8\uc5b4: "+userConfig.locale.lang.value,{event_category:"\uacf5\uac1c\ubaa8\uc9d1 \uacc4\uc0b0\uae30",non_interaction:!0});
