var gtag_tagBatchSelectorUsed=!1,aliasMap={"\uc2a8":"\uc2a4\ub098\uc774\ud37c","\uc2be":"\uc2a4\ud398\uc15c\ub9ac\uc2a4\ud2b8","\ub52e":"\ub514\ud39c\ub354","\ub525":"\ub514\ubc84\ud504"};
const batchSelectEventHandler=function(a){if(!0===a.target.checked){var c=null;JSON.parse(a.target.dataset.cgroup).forEach(d=>{c=document.getElementById("tag_"+d);c.className="checkboxButton";c.removeEventListener("click",batchSelectEventHandler)});a.target.dataset.cgroup=""}},banRecommendation=function(a,c){if(0<=["autoFocusBatchSelector"].indexOf(c)){var d=JSON.parse(localStorage.getItem("recr_banned-recommendation"))||[];0>d.indexOf(c)&&(console.log(c),d.push(c),localStorage.setItem("recr_banned-recommendation",
JSON.stringify(d)));a.closest(".recommended").remove()}},createRecommendationPanel=function(a,c,d,k){return`<div class="panel guide-panel recommended">
            <span style="font-size:110%;font-weight:500">
            \ucd94\ucc9c\ud558\ub294 \uae30\ub2a5\uc774 \uc788\uc5b4\uc694!<br>
            <br>
            </span>
            <span style="font-size:95%">
            <a style="cursor:pointer;color:var(--color--skyBlue)" onclick="${`userConfig.${c}.${a}`}.value=true;saveUserConfig();location.reload()">[${d} \ucf1c\uae30]</a><br>
            <br>
            ${k}<br>
            <br>
            <a style="cursor:pointer;color:#999" onclick="banRecommendation(this, '${a}')">[\uc55e\uc73c\ub85c \uc774 \ucd94\ucc9c \ud45c\uc2dc\ud558\uc9c0 \uc54a\uae30]</a>
            </span>
        </div>`},tagBatchSelectorGuide=function(){document.querySelectorAll(".recommended").forEach(c=>c.remove());var a=JSON.parse(localStorage.getItem("recr_banned-recommendation"))||[];console.log(a);0>a.indexOf("autoFocusBatchSelector")&&!userConfig.input.autoFocusBatchSelector.value&&document.getElementById("result-panel").insertAdjacentHTML("afterbegin",createRecommendationPanel("autoFocusBatchSelector","input","\ud0dc\uadf8 \uc785\ub825\uae30 \uc790\ub3d9 \ud3ec\ucee4\uc2a4",'\ub4e4\uc5b4\uc624\uc790\ub9c8\uc790, \ub610\ub294 \ud0dc\uadf8\ub97c \ucd08\uae30\ud654\ud55c \ub4a4,<br>\uace7\ubc14\ub85c \ud0dc\uadf8\ub97c \uc785\ub825\ud560 \uc218 \uc788\uc5b4\uc694.<br><br><span style="color:#999">*\ubaa8\ubc14\uc77c \uae30\uae30\uc5d0\uc120 \uc77c\ubd80 \uae30\ub2a5\uc774 \uc81c\ud55c\ub420 \uc218 \uc788\uc2b5\ub2c8\ub2e4*</span>'))};
$("#tagBatchSelector").keyup(function(a){gtag_tagBatchSelectorUsed||(gtag_tagBatchSelectorUsed=!0,gtag("event","\ud0dc\uadf8 \uc120\ud0dd\uae30 \ucd5c\ucd08 \uc0ac\uc6a9",{event_category:"\uacf5\uac1c\ubaa8\uc9d1 \uacc4\uc0b0\uae30"}));if(13===a.keyCode){if(1==$(a.target).data("typo"))$(a.target).addClass("typo"),gtag("event","\ud0dc\uadf8 \uc120\ud0dd\uae30 \uc624\ud0c0 \uacbd\uace0 \uae30\ub2a5 \uc791\ub3d9",{event_category:"\uacf5\uac1c\ubaa8\uc9d1 \uacc4\uc0b0\uae30"});else{tagBatchSelectorGuide();
$(a.target).blur();var c=0;c=0<$(".blink+label").length?$(".selection-panel").offset().top:$("#selection-panel-footer-btn").offset().top;$("html,body").animate({scrollTop:c},200)}return!1}$(a.target).removeClass("typo");$(a.target).data("typo",!1);if(0===this.value.replace(/(\s*)/g,"").length)return!1;var d=0,k=db.tag.keys.length,g=[],e={},f=[];this.value.split("").forEach(b=>{b=aliasMap[b]||b;d=0;for(f=[];d<k;++d)"sex"!==db.tag[d].type&&0===db.tag[d].name.kr.slice(0,b.length).indexOf(b)&&f.push(d);
0===f.length&&/[\u3131-\u314e|\u314f-\u3163|\uac00-\ud7a3]/.test(b)&&$(a.target).data("typo",!0);1===f.length?g.push(f[0]):1<f.length&&(e[b]?++e[b].cnt:e[b]={cnt:1,tags:[...f]})});clearSelection(!1,!1);var h=null;Object.keys(e).forEach(b=>{e[b].cnt>=e[b].tags.length?g=[...g,...e[b].tags]:e[b].tags.forEach(m=>{h=document.getElementById("tag_"+m);h.className+=" blink";h.dataset.cgroup=JSON.stringify(e[b].tags);h.addEventListener("click",batchSelectEventHandler)})});5<g.length&&$(a.target).data("typo",
!0);if(0<g.length){var l=null;g.forEach(b=>{l=document.getElementById("tag_"+b);l.checked=!0;tagClicked(l,!1)});showResult()}});
