var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var e=a.length,d=0;d<e;d++){var f=a[d];if(b.call(c,f,d,a))return{i:d,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};
$jscomp.polyfill=function(a,b,c,e){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,e):$jscomp.polyfillUnisolated(a,b,c,e))};$jscomp.polyfillUnisolated=function(a,b,c,e){c=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var d=a[e];if(!(d in c))return;c=c[d]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,e){var d=a.split(".");a=1===d.length;e=d[0];e=!a&&e in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<d.length-1;f++){var g=d[f];if(!(g in e))return;e=e[g]}d=d[d.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?e[d]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,d,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[d]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(d):$jscomp.POLYFILL_PREFIX+d,d=
$jscomp.propertyToPolyfillSymbol[d],$jscomp.defineProperty(e,d,{configurable:!0,writable:!0,value:b})))};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");
var cutdownInput=function(a){var b=$(a);a=b.find(".item_body_have_input");b=b.find(".item_body_need_input");var c=a.val(),e=b.val(),d=Number(c),f=Number(e);d=isNaN(d)?0:d;f=isNaN(f)?0:f;d>f?(d-=f,f=0):(f-=d,d=0);f=0===f?"":f;a.val(0===d?"":d);b.val(f);c!=a.val()&&a.trigger("change");e!=b.val()&&b.trigger("change")},cutdownAllInputs=function(){for(var a=$(".item-container .item"),b=0;b<a.length;++b)cutdownInput(a.eq(b))},clearInputData=function(){confirm("\uc8fc\uc758: \uc774 \uc791\uc5c5\uc740 \ub418\ub3cc\ub9b4 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4.\n\uc815\ub9d0\ub85c \ud574\ub2f9 \uc11c\ube44\uc2a4\uc640 \uad00\ub828\ub41c \ubaa8\ub4e0 \ub370\uc774\ud130\ub97c \ucd08\uae30\ud654\ud558\uc2dc\uaca0\uc2b5\ub2c8\uae4c?")&&
($(".item_body_have_input, .item_body_need_input").val(""),clearLocalStorage(),location.reload())},toggleFilterOnlyLack=function(){filterOnlyLack=!filterOnlyLack;localStorage.setItem("mcalc_filter_onlyLack",JSON.stringify(filterOnlyLack));refreshBtnFilterOnlyLack();applyConfig()},refreshBtnFilterOnlyLack=function(){for(var a=$('[name="toggleFilterOnlyLack"]'),b=0;b<a.length;++b)filterOnlyLack?a.eq(b).html('\ubd80\uc871\ud55c \uc544\uc774\ud15c\ub9cc \ud45c\uc2dc <span style="color:#187dc9">ON</span>'):
a.eq(b).html('\ubd80\uc871\ud55c \uc544\uc774\ud15c\ub9cc \ud45c\uc2dc <span style="color:#de0d0d">OFF</span>')},applyConfig=function(){$('.item-container [id*="category_"]').css("display","block");var a=$(".item-container .item");a.css("display","inline-block");for(var b=0;b<filterCategory.length;++b)$(".item-container #category_"+filterCategory[b]).css("display","none");for(b=0;b<filterGrade.length;++b)for(var c=0;c<a.length;++c){var e=Number(a.eq(c).attr("id").split("_")[1]);db.item[e].grade==
filterGrade[b]&&a.eq(c).css("display","none")}if(filterOnlyLack)for(b=0;b<a.length;++b)0<=Number(a.eq(b).find(".item_thumb_quantity").text())&&a.eq(b).css("display","none");displayName?$(".item-container .item_thumb_name").css("display","inline-block"):$(".item-container .item_thumb_name").css("display","none");displayInputField?$(".item-container .item_body").css("display","inline-block"):$(".item-container .item_body").css("display","none")};
