var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.arrayFromIterator=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};
$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};
$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var e=a.split(".");a=1===e.length;d=e[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<e.length-1;f++){var g=e[f];if(!(g in d))return;d=d[g]}e=e[e.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[e]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+e,e=
$jscomp.propertyToPolyfillSymbol[e],$jscomp.defineProperty(d,e,{configurable:!0,writable:!0,value:b})))};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");
var cutdownInput=function(a){var b=$(a);a=b.find(".item_body_have_input");b=b.find(".item_body_need_input");var c=a.val(),d=b.val(),e=Number(c),f=Number(d);e=isNaN(e)?0:e;f=isNaN(f)?0:f;e>f?(e-=f,f=0):(f-=e,e=0);f=0===f?"":f;a.val(0===e?"":e);b.val(f);c!=a.val()&&a.trigger("change");d!=b.val()&&b.trigger("change")},cutdownAllInputs=function(){for(var a=$(".item-container .item"),b=0;b<a.length;++b)cutdownInput(a.eq(b))},clearAllData=function(){confirm("\uc8fc\uc758: \uc774 \uc791\uc5c5\uc740 \ub418\ub3cc\ub9b4 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4.\n\uc815\ub9d0\ub85c \ud574\ub2f9 \uc11c\ube44\uc2a4\uc640 \uad00\ub828\ub41c \ubaa8\ub4e0 \ub370\uc774\ud130\ub97c \ucd08\uae30\ud654\ud558\uc2dc\uaca0\uc2b5\ub2c8\uae4c?")&&
($(".item_body_have_input, .item_body_need_input").val(""),clearStorageData(),location.reload())},clearCalcData=function(){confirm("\uc8fc\uc758: \uc774 \uc791\uc5c5\uc740 \ub418\ub3cc\ub9b4 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4.\n\uc815\ub9d0\ub85c \uacc4\uc0b0 \ud0ed\uc758 \ub370\uc774\ud130\ub97c \ubaa8\ub450 \ucd08\uae30\ud654\ud558\uc2dc\uaca0\uc2b5\ub2c8\uae4c?\n(\uc778\ubca4\ud1a0\ub9ac \ud0ed\uc758 \ub370\uc774\ud130\ub294 \ucd08\uae30\ud654\ub418\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.)")&&($(".item_body_craft_input").val(""),
clearStorageCalcData(),location.reload())},toggleFilterOnlyLack=function(){filterOnlyLack=!filterOnlyLack;localStorage.setItem("mcalc_filter_onlyLack",JSON.stringify(filterOnlyLack));refreshBtnFilterOnlyLack();applyConfig()},refreshBtnFilterOnlyLack=function(){for(var a=$('[name="toggleFilterOnlyLack"]'),b=0;b<a.length;++b)filterOnlyLack?a.eq(b).html('\ubd80\uc871\ud55c \uc544\uc774\ud15c\ub9cc \ud45c\uc2dc <span style="color:#187dc9">ON</span>'):a.eq(b).html('\ubd80\uc871\ud55c \uc544\uc774\ud15c\ub9cc \ud45c\uc2dc <span style="color:#de0d0d">OFF</span>')},
checkBreakdownValue=function(a){0===Number(a.value)&&(clearStorageCalcData(),refreshAllCalcItems(),fetchConfig(),applyConfig())},applyConfig=function(){var a=$(".item-container");a.find('[class*="category_"]').css("display","block");var b=a.find(".item");b.css("display","inline-block");for(var c=0;c<filterCategory.length;++c)a.find(".category_"+filterCategory[c]).css("display","none");for(c=0;c<filterGrade.length;++c)for(var d=0;d<b.length;++d){var e=Number(b.eq(d).attr("id").split("_")[1]);db.item[e].grade==
filterGrade[c]&&b.eq(d).css("display","none")}0<breakdownGrade&&"none"!==document.querySelector(".calc").style.display?(console.log("breakdown"),document.querySelector(".calc").classList.add("auto-breakdown"),breakdownByGrade(breakdownGrade)):document.querySelector(".calc").classList.remove("auto-breakdown");if(filterOnlyLack)for(c=0;c<b.length;++c)0<=Number(b.eq(c).find(".item_thumb_quantity").text())&&b.eq(c).css("display","none");displayName?a.find(".item_thumb_name").css("display","inline-block"):
a.find(".item_thumb_name").css("display","none");displayInputField?a.find(".item_body_have, .item_body_need, .item_body_craft").css("display","inline-block"):a.find(".item_body_have, .item_body_need, .item_body_craft").css("display","none");displayGuide?$(".guide").css("display","inline-block"):$(".guide").css("display","none")},hideGuide=function(){displayGuide=!1;localStorage.setItem("mcalc_display_guide",JSON.stringify(displayGuide));applyConfig()},setSurplus=function(a,b){a=a.querySelector(".item_thumb_quantity");
a.innerText=b;a=a.classList;0>b?(a.add("minus"),a.remove("plus")):(0<b?a.add("plus"):a.remove("plus"),a.remove("minus"))},getSurplus=function(a){var b=getItem_need(a),c=getItem_have(a),d=getItem_craft(a);a=getItem_totalDemand(a);return c+d-(b+a)},refreshDemand=function(a,b){var c=db.item[a].craft[0];if(void 0!==c){var d=getItem_craft(a);if(b){b=0;for(var e=c.length;b<e;++b){var f=c[b][0];setItem_demand(f,a,c[b][1]*d);$(document.getElementById("calc-item_"+f)).trigger("refresh")}}else for(b=0,e=c.length;b<
e;++b)setItem_demand(c[b][0],a,c[b][1]*d)}},refreshAllCalcItems=function(){for(var a=document.querySelectorAll(".calc .item"),b=0,c=a.length;b<c;++b){var d=a[b].getAttribute("id").split("_")[1],e=a[b].querySelector("input");if(e){var f=getItem_craft(d);e.value=f}setSurplus(a[b],getSurplus(d))}},breakdownByGrade=function(a){clearStorageCalcData();var b=[];for(a+=1;5>=a;++a)b.push.apply(b,$jscomp.arrayFromIterable(document.querySelectorAll(".calc .item.grade_"+a+":not(.uncraftable")));var c=[];a=0;
for(var d=b.length;a<d;++a)c.push(b[a].getAttribute("id").split("_")[1]);a=0;for(d=b.length;a<d;++a)6<=c[a]&&8>=c[a]&&(c.splice(a,1),b.splice(a,1),--d,--a);for(var e=0;;){a=0;for(d=b.length;a<d;++a){var f=c[a],g=getSurplus(f);if(!(0===g||0<g&&0===h))break}if(a===d)break;++e;a=0;for(d=b.length;a<d;++a){f=c[a];var h=getItem_craft(f);g=getSurplus(f);setItem_craft(f,h<g?0:h-g);refreshDemand(f,!1)}}0<e&&refreshAllCalcItems()};
