var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var e=a.length,g=0;g<e;g++){var d=a[g];if(b.call(c,d,g,a))return{i:g,v:d}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};
$jscomp.polyfill=function(a,b,c,e){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,e):$jscomp.polyfillUnisolated(a,b,c,e))};$jscomp.polyfillUnisolated=function(a,b,c,e){c=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var g=a[e];if(!(g in c))return;c=c[g]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,e){var g=a.split(".");a=1===g.length;e=g[0];e=!a&&e in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var d=0;d<g.length-1;d++){var l=g[d];if(!(l in e))return;e=e[l]}g=g[g.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?e[g]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,g,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[g]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(g):$jscomp.POLYFILL_PREFIX+g,g=
$jscomp.propertyToPolyfillSymbol[g],$jscomp.defineProperty(e,g,{configurable:!0,writable:!0,value:b})))};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(a,e){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:e})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var c=0,e=function(a){if(this instanceof e)throw new TypeError("Symbol is not a constructor");return new b("jscomp_symbol_"+(a||"")+"_"+c++,a)};return e},"es6","es3");$jscomp.initSymbolIterator=function(){};
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var e=$jscomp.global[b[c]];"function"===typeof e&&"function"!=typeof e.prototype[a]&&$jscomp.defineProperty(e.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.initSymbolAsyncIterator=function(){};$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,b){a instanceof String&&(a+="");var c=0,e={next:function(){if(c<a.length){var g=c++;return{value:b(g,a[g]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e};
$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");$jscomp.polyfill("Number.isNaN",function(a){return a?a:function(a){return"number"===typeof a&&isNaN(a)}},"es6","es3");
var setSkillLevelBound=function(a,b,c){c=$(c);var e=Number(c.val());e<a&&c.val(a);e>b&&c.val(b);c=c.find("option");for(e=0;e<c.length;++e){var g=c.eq(e),d=Number(g.val());d<a||d>b?g.prop("disabled",!0):g.prop("disabled",!1)}},validateTargetSkillLevel=function(a,b){b=$(b);var c=a.currentSkillLevel,e=[4,7,10][a.targetElite];c>e&&console.log("\uc5d0\ub7ec: \ud558\ud55c\uc774 \uc0c1\ud55c\ubcf4\ub2e4 \ud07d\ub2c8\ub2e4.",c,e,a,b);setSkillLevelBound(c,e,b)},validateCurrentSkillLevel=function(a,b){b=$(b);
var c=[4,7,10][a.currentElite];1>c&&console.log("\uc5d0\ub7ec: \ud558\ud55c\uc774 \uc0c1\ud55c\ubcf4\ub2e4 \ud07d\ub2c8\ub2e4.",1,c,a,b);setSkillLevelBound(1,c,b)},openModalPrompt=function(){$(".modal").css("display","block");doNotRefreshResult=!0},closeModalPrompt=function(){$("#modal").css("display","none");doNotRefreshResult=!1;showResult()};
$(document).ready(function(){toastr.options={closeButton:!1,debug:!1,newestOnTop:!1,progressBar:!1,positionClass:"toast-top-full-width",preventDuplicates:!1,onclick:null,showDuration:"200",hideDuration:"500",timeOut:"1000",extendedTimeOut:"500",showEasing:"swing",hideEasing:"linear",showMethod:"fadeIn",hideMethod:"fadeOut"};$(".add-btn").click(function(){openModalPrompt()});$(".close-btn").click(function(){closeModalPrompt()});$(window).click(function(a){$(a.target).is($("#modal"))&&closeModalPrompt()});
$("#opname").keyup(function(){for(var a="",b=$(this).val().split(" "),c=0;c<b.length;++c)0<c&&(a+=" "),a+=b[c].charAt(0).toUpperCase()+b[c].slice(1).toLowerCase();searchingCondition.name=a;showSearchResult()});$(".rarity-btn").click(function(){var a=Number($(this).attr("name")),b=searchingCondition.rarityArray.indexOf(a);0<=b?(searchingCondition.rarityArray.splice(b,1),$(this).removeClass("selected")):(searchingCondition.rarityArray.push(a),$(this).addClass("selected"));showSearchResult()});$(".class-btn").click(function(){var a=
getTagCodeByKRTagName($(this).attr("name"));a&searchingCondition.tagCode?$(this).removeClass("selected"):$(this).addClass("selected");searchingCondition.tagCode^=a;showSearchResult()});loadLocalStorage()});
var makeOpForm=function(a){var b=data.opData[a].name.en,c=Number(data.opData[a].rarity);b=b.toLowerCase();a='<form class="op" align="center" name="op_'+a+'"> <span class="remove-op-btn">\u00d7</span> <img class="op" src="./images/op/thumb/'+(b+'.png"><br>');a+="<span>\uc815\uc608\ud654</span><br> ";a+='<select style="font-size: 60%;" class="current-elite"> ';c=[0,0,1,2,2,2][c-1];for(b=0;b<=c;++b)a+='<option value="'+b+'"',0==b&&(a+=" selected"),a+=">"+b+"\ub2e8\uacc4</option> ";a+="</select> ";a+=
"<span>\u25b8</span> ";a+='<select style="font-size: 60%;" class="target-elite"> ';for(b=0;b<=c;++b)a+='<option value="'+b+'"',b==c&&(a+=" selected"),a+=">"+b+"\ub2e8\uacc4</option> ";a+="</select><br> ";a+="<hr> ";a+='<button type="button" class="set-current-op-level-to-max-btn"> ';a+="MAX";a+="</button> ";a+="<span>\ub808\ubca8</span> ";a+='<button type="button" class="set-target-op-level-to-max-btn"> ';a+="MAX";a+="</button><br> ";a+='<input type="text" class="current-op-level" style="font-size: 60%;" value="1"> ';
a+="<span>\u25b8</span> ";a+='<input type="text" class="target-op-level" style="font-size: 60%;" value="1"><br> ';a+="<hr> ";a+="<span>\uc2a4\ud0ac \ub808\ubca8</span><br> ";a+='<div style="font-size: 85%; margin-top: 0.2em"> ';a+='<span style="font-size: 65%">1\uc2a4\ud0ac</span> ';a+='<select style="width: 20%" class="current-skill-level"> ';for(b=1;10>=b;++b)a+='<option value="'+b+'">'+b+"</option> ";a+="</select> ";a+='<span style="font-size: 65%">\u25b8</span> ';a+='<select style="width: 20%" class="target-skill-level"> ';
c=[4,7,7][c];for(b=1;10>=b;++b)a+='<option value="'+b+'"',b==c&&(a+=" selected"),a+=">"+b+"</option> ";a+="</select> ";a+="<br> ";a+='<span style="font-size: 65%">2\uc2a4\ud0ac</span> ';a+='<select style="width: 20%;" class="current-skill-level"> ';for(b=1;10>=b;++b)a+='<option value="'+b+'">'+b+"</option> ";a+="</select> ";a+='<span style="font-size: 65%">\u25b8</span> ';a+='<select style="width: 20%" class="target-skill-level"> ';for(b=1;10>=b;++b)a+='<option value="'+b+'"',b==c&&(a+=" selected"),
a+=">"+b+"</option> ";a+="</select> ";a+="<br> ";a+='<span style="font-size: 65%">3\uc2a4\ud0ac</span> ';a+='<select style="width: 20%;" class="current-skill-level"> ';for(b=1;10>=b;++b)a+='<option value="'+b+'">'+b+"</option> ";a+="</select> ";a+='<span style="font-size: 65%">\u25b8</span> ';a+='<select style="width: 20%" class="target-skill-level"> ';for(b=1;10>=b;++b)a+='<option value="'+b+'"',b==c&&(a+=" selected"),a+=">"+b+"</option> ";a+="</select> ";a+="<br> ";a+="</div> ";return a+="</form>"},
loadLocalStorage=function(){for(var a="current-elite target-elite current-op-level target-op-level current-skill-level target-skill-level".split(" "),b={IDs:[]},c=0;c<data.opData.length;++c){var e=c,g="optotal_"+e+"_";b[e]=[];for(var d=!1,l=0;l<a.length;++l){var h=g+a[l];null!==localStorage.getItem(h)&&(b[e].push(a[l]),d=!0)}d&&b.IDs.push(e)}if(0!==b.IDs.length){doNotRefreshResult=!0;for(c=0;c<b.IDs.length;++c){e=b.IDs[c];g="optotal_"+e+"_";a={keys:[]};for(l=0;l<b[e].length;++l){var k=b[e][l];h=g+
k;d=JSON.parse(localStorage.getItem(h));a[k]=d;a.keys.push(k)}addOp(e,!1);e=$('form[name="op_'+e+'"].op');for(l=0;l<a.keys.length;++l)if(h=a.keys[l],d=a[h],"current-elite"===h)e.find(".current-elite").val(d),e.find(".current-elite").trigger("change");else if("target-elite"===h)e.find(".target-elite").val(d);else if("current-op-level"===h)e.find(".current-op-level").val(d);else if("target-op-level"===h)e.find(".target-op-level").val(d);else if("current-skill-level"===h)for(h=e.find(".current-skill-level"),
g=0;g<d.length;++g)h.eq(g).val(d[g]);else if("target-skill-level"===h)for(h=e.find(".target-skill-level"),g=0;g<d.length;++g)h.eq(g).val(d[g]);e.find(".current-elite").trigger("change")}doNotRefreshResult=!1;showResult()}},addOp=function(a,b){b=void 0===b?!0:b;if(0>=$('#selected-op form[name|="op_'+a+'"]').length){$("#selected-op").append(makeOpForm(a));var c=$('form[name="op_'+a+'"].op');c.find(".remove-op-btn").off("click").on("click",function(){var a=Number($(this).parent().attr("name").split("_")[1]);
if(Number.isNaN(a))console.log("\uc5d0\ub7ec: \uc624\ud37c\ub808\uc774\ud130 \uc544\uc774\ub514\uac00 \uc22b\uc790\ub85c \uc774\ub904\uc9c0\uc9c0 \uc54a\uc74c");else{$(this).parent().remove();a="optotal_"+a+"_";for(var b="current-elite target-elite current-op-level target-op-level current-skill-level target-skill-level".split(" "),d=0;d<b.length;++d)localStorage.removeItem(a+b[d]);0===$('form[name*="op_"].op').length&&$("#selected-op-guide").css("display","block");showResult()}});c.find(".set-current-op-level-to-max-btn").off("click").on("click",
function(){var a=$(this).parent(),b=Number(a.attr("name").split("_")[1]),d=a.find(".current-op-level");({})["current-op-level"]=Number(d.val());Number.isNaN(b)?console.log("\uc5d0\ub7ec: \uc624\ud37c\ub808\uc774\ud130 \uc544\uc774\ub514\uac00 \uc22b\uc790\ub85c \uc774\ub904\uc9c0\uc9c0 \uc54a\uc74c"):(a=Number(a.find(".current-elite").val()),b=getMaxLevel(a,Number(data.opData[b].rarity)),d.val(b),d.trigger("change"))});c.find(".set-target-op-level-to-max-btn").off("click").on("click",function(){var a=
$(this).parent(),b=Number(a.attr("name").split("_")[1]),d=a.find(".target-op-level");({})["target-op-level"]=Number(d.val());Number.isNaN(b)?console.log("\uc5d0\ub7ec: \uc624\ud37c\ub808\uc774\ud130 \uc544\uc774\ub514\uac00 \uc22b\uc790\ub85c \uc774\ub904\uc9c0\uc9c0 \uc54a\uc74c"):(a=Number(a.find(".target-elite").val()),b=getMaxLevel(a,Number(data.opData[b].rarity)),d.val(b),d.trigger("change"))});c.find(".current-elite").off("change").on("change",function(){var a=$(this).parent(),b=Number(a.attr("name").split("_")[1]),
d=a.find(".current-elite"),c=a.find(".target-elite"),h=a.find(".current-op-level");a=a.find(".current-skill-level");var k={};k["target-elite"]=Number(c.val());k["current-op-level"]=Number(h.val());k["current-skill-level"]=[];for(var f=0;f<a.length;++f)k["current-skill-level"].push(Number(a.eq(f).val()));Number(d.val())>Number(c.val())&&c.val(d.val());k=c.find("option").length;for(f=0;f<k;++f)f<Number(d.val())?c.find('option[value="'+f+'"]').prop("disabled",!0):c.find('option[value="'+f+'"]').prop("disabled",
!1);f=data.opData[b].rarity;f=getMaxLevel(Number(d.val()),f);Number(h.val())>f&&h.val(f);f=[0,0,1,2,2,3][Number(data.opData[b].rarity)-1];"\uc544\ubbf8\uc57c"==data.opData[b].name.kr&&(f=3);k=[1,2,3][Number(d.val())];k>f&&(k=f);for(f=0;f<k;++f){var m=a.eq(f);m.prop("disabled",!1);var n={};n.currentElite=Number(d.val());validateCurrentSkillLevel(n,m)}d=a.length;for(f=k;f<d;++f)a.eq(f).val(1),a.eq(f).prop("disabled",!0);b="optotal_"+b+"_current-elite";d=Number($(this).val());d=Number.isNaN(d)?0:d;localStorage.setItem(b,
d);c.trigger("change");h.trigger("change");a.trigger("change")});c.find(".target-elite").off("change").on("change",function(){var a=$(this).parent(),b=Number(a.attr("name").split("_")[1]);a.find(".current-elite");var d=a.find(".target-elite"),c=a.find(".target-op-level"),h=a.find(".target-skill-level");a=a.find(".current-skill-level");var k={};k["target-op-level"]=Number(c.val());k["target-skill-level"]=[];for(var f=0;f<h.length;++f)k["target-skill-level"].push(Number(h.eq(f).val()));f=data.opData[b].rarity;
f=getMaxLevel(Number(d.val()),f);c.val()>f&&c.val(f);f=[0,0,1,2,2,3][Number(data.opData[b].rarity)-1];"\uc544\ubbf8\uc57c"==data.opData[b].name.kr&&(f=3);k=[1,2,3][Number(d.val())];k>f&&(k=f);for(f=0;f<k;++f){var m=h.eq(f),n=Number(d.val()),q=Number(a.eq(f).val());m.prop("disabled",!1);var p={};p.targetElite=n;p.currentSkillLevel=q;validateTargetSkillLevel(p,m)}d=h.length;for(f=k;f<d;++f)h.eq(f).val(1),h.eq(f).prop("disabled",!0);b="optotal_"+b+"_target-elite";d=Number($(this).val());d=Number.isNaN(d)?
2:d;localStorage.setItem(b,d);c.trigger("change");h.trigger("change")});c.find(".current-op-level").off("change").on("change",function(){var a=$(this).parent(),b=a.attr("name").split("_")[1];a=Number(a.find(".current-elite").val());a=getMaxLevel(a,Number(data.opData[b].rarity));var d=Number($(this).val());d=Number.isNaN(d)?1:d;d=1>d?1:d;d=d>a?a:d;$(this).val(d);localStorage.setItem("optotal_"+b+"_current-op-level",d);showResult()});c.find(".target-op-level").off("change").on("change",function(){var a=
$(this).parent(),b=a.attr("name").split("_")[1];a=Number(a.find(".target-elite").val());a=getMaxLevel(a,Number(data.opData[b].rarity));var d=Number($(this).val());d=Number.isNaN(d)?1:d;d=1>d?1:d;d=d>a?a:d;$(this).val(d);localStorage.setItem("optotal_"+b+"_target-op-level",d);showResult()});c.find(".current-skill-level").off("change").on("change",function(){if(!0!==$(this).prop("disabled")){for(var b=Number($(this).val()),c=$(this).parent().parent(),d=c.find(".target-skill-level:enabled").length,l=
c.find(".current-skill-level"),h=c.find(".target-skill-level"),k={"target-skill-level":[]},f=0;f<h.length;++f)k["target-skill-level"].push(Number(h.eq(f).val()));if(6>=b)for(f=0;f<d;++f){var m=l.eq(f);k=h.eq(f);var n=Number(c.find(".target-elite").val()),q=Number(m.val());m.val(b);m={};m.targetElite=n;m.currentSkillLevel=q;validateTargetSkillLevel(m,k)}else for(f=0;f<d;++f)m=l.eq(f),k=h.eq(f),n=Number(c.find(".target-elite").val()),q=Number(m.val()),7>q&&m.val(7),m={},m.targetElite=n,m.currentSkillLevel=
q,validateTargetSkillLevel(m,k);b="optotal_"+a+"_current-skill-level";c=[];for(f=0;f<l.length;++f)c.push(Number(l.eq(f).val()));c=JSON.stringify(c);localStorage.setItem(b,c);h.trigger("change")}});c.find(".target-skill-level").off("change").on("change",function(){if(!0!==$(this).prop("disabled")){var b=Number($(this).val()),c=$(this).parent().parent(),d=c.find(".target-skill-level:enabled").length,l=Number(c.find(".current-skill-level").eq(0).val());7<l&&(l=7);var h=c.find(".current-skill-level"),
k=c.find(".target-skill-level");if(6>=b)for(var f=0;f<d;++f){var m=h.eq(f),n=k.eq(f),q=Number(c.find(".target-elite").val());m=Number(m.val());m<l&&(m=l);n.val(b);var p={};p.targetElite=q;p.currentSkillLevel=m;validateTargetSkillLevel(p,n)}else for(f=0;f<d;++f)m=h.eq(f),n=k.eq(f),q=Number(c.find(".target-elite").val()),m=Number(m.val()),m<l&&(m=l),7>Number(n.val())&&n.val(7),p={},p.targetElite=q,p.currentSkillLevel=m,validateTargetSkillLevel(p,n);b="optotal_"+a+"_target-skill-level";c=[];for(f=0;f<
k.length;++f)c.push(Number(k.eq(f).val()));c=JSON.stringify(c);localStorage.setItem(b,c);showResult()}});c.find(".current-elite").trigger("change");$("#selected-op-guide").css("display","none");b&&toastr.success(data.opData[a].name.kr,"\ucd94\uac00\ub428")}else b&&toastr.error(data.opData[a].name.kr,"\uc774\ubbf8 \ucd94\uac00\ub418\uc5b4 \uc788\uc74c"),console.log("\uc774\ubbf8 \ucd94\uac00\ub418\uc5b4 \uc788\uc74c",a,data.opData[a].name.kr)},searchingCondition={name:"",rarityArray:[],tagCode:0},
getTagCodeByKRTagName=function(a){for(var b=0;b<data.tagData.length;++b)if(data.tagData[b].name.kr==a)return Number(data.tagData[b].tagCode)},showSearchResult=function(){searchingCondition.rarityArray.sort(function(a,b){return a>b?-1:1});for(var a=searchOp(searchingCondition.name,searchingCondition.rarityArray,searchingCondition.tagCode),b=[],c=[],e=[],g=0;g<a.length;++g)b.push(a[g].name.kr),c.push(a[g].name.en),e.push(a[g].id);a="";for(g=0;g<c.length;++g)a+='<form class="search-result-op" name="op_'+
e[g]+'">\t<img src="./images/op/thumb/'+c[g].toLowerCase()+'.png">\t<div>'+b[g]+"</div></form> ";""==a&&(a='<p style="font-size: 0.5em; text-align: center">\uac80\uc0c9 \uacb0\uacfc\uac00 \uc5ec\uae30\uc5d0 \ud45c\uc2dc\ub429\ub2c8\ub2e4.</p>');$("div.modal-footer>div.search-result").html(a);$("form.search-result-op").off("click").on("click",function(){var a=$(this).attr("name").split("_")[1];addOp(a,!0)})},searchOp=function(a,b,c){var e=[];var g=JSON.parse(JSON.stringify(data.opData));0>=a.replace(/(\s*)/g,
"").length&&(a=!1);for(var d=0;d<g.length;++d)0<=g[d].name.kr.indexOf(a)?(e.push(g[d]),g.splice(d,1),--d):0<=g[d].name.en.indexOf(a)?(e.push(g[d]),g.splice(d,1),--d):0<=g[d].name.cn.indexOf(a)?(e.push(g[d]),g.splice(d,1),--d):0<=g[d].name.jp.indexOf(a)&&(e.push(g[d]),g.splice(d,1),--d);if(0<b.length)for(!1!==a&&(g=JSON.parse(JSON.stringify(e)),e=[]),d=0;d<b.length;++d)for(var l=0;l<g.length;++l)b[d]==g[l].rarity&&(e.push(g[l]),g.splice(l,1),--l);if(0!=c){if(!1!==a||0<b.length)g=JSON.parse(JSON.stringify(e)),
e=[];for(d=0;d<g.length;++d)c&g[d].tagCode&&(e.push(g[d]),g.splice(d,1),--d)}return e},addResultToMcalc=function(){var a=fetchInputData();if(!1===a)toastr.error("\uc804\uc1a1\ud560 \ub370\uc774\ud130\uac00 \uc874\uc7ac\ud558\uc9c0 \uc54a\uc74c","\uc7ac\ub8cc \uacc4\uc0b0\uae30\ub85c \uacb0\uacfc \ubcf4\ub0b4\uae30");else if(confirm("\uc8fc\uc758: \uc774 \uc791\uc5c5\uc740 \ub418\ub3cc\ub9b4 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4.\n\uacb0\uacfc \ub370\uc774\ud130\ub97c \uc804\uc1a1\ud558\uc2dc\ub824\uba74 \ud655\uc778 \ubc84\ud2bc\uc744 \ub20c\ub7ec\uc8fc\uc2ed\uc2dc\uc624.")){a=
sortResultData(calc(a));for(var b=0;b<a.total.IDs.length;++b){var c=Number(a.total.IDs[b]),e=Number(a.total[c]);e+=JSON.parse(localStorage.getItem("mcalc_item-need_"+c));localStorage.setItem("mcalc_item-need_"+c,JSON.stringify(e))}toastr.success("\uc131\uacf5\uc801\uc73c\ub85c \uacb0\uacfc \ub370\uc774\ud130\ub97c \uc804\uc1a1\ud568","\uc7ac\ub8cc \uacc4\uc0b0\uae30\ub85c \uacb0\uacfc \ubcf4\ub0b4\uae30");confirm("\uc131\uacf5\uc801\uc73c\ub85c \uacb0\uacfc \ub370\uc774\ud130\ub97c \uc804\uc1a1\ud558\uc600\uc2b5\ub2c8\ub2e4.\n\ubc14\ub85c \uc7ac\ub8cc \uacc4\uc0b0\uae30\ub85c \uc774\ub3d9\ud558\uc2dc\uaca0\uc2b5\ub2c8\uae4c?")&&
(location.href="mcalc.html")}else toastr.error("\ucde8\uc18c\ub428","\uc7ac\ub8cc \uacc4\uc0b0\uae30\ub85c \uacb0\uacfc \ubcf4\ub0b4\uae30")};
