var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,e){if(a==Array.prototype||a==Object.prototype)return a;a[b]=e.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var e=a[b];if(e&&e.Math==Math)return e}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var e=$jscomp.propertyToPolyfillSymbol[b];if(null==e)return a[b];e=a[e];return void 0!==e?e:a[b]};$jscomp.polyfill=function(a,b,e,c){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,e,c):$jscomp.polyfillUnisolated(a,b,e,c))};
$jscomp.polyfillUnisolated=function(a,b,e,c){e=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var d=a[c];if(!(d in e))return;e=e[d]}a=a[a.length-1];c=e[a];b=b(c);b!=c&&null!=b&&$jscomp.defineProperty(e,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,e,c){var d=a.split(".");a=1===d.length;c=d[0];c=!a&&c in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<d.length-1;f++){var h=d[f];if(!(h in c))return;c=c[h]}d=d[d.length-1];e=$jscomp.IS_SYMBOL_NATIVE&&"es6"===e?c[d]:null;b=b(e);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,d,{configurable:!0,writable:!0,value:b}):b!==e&&($jscomp.propertyToPolyfillSymbol[d]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(d):$jscomp.POLYFILL_PREFIX+d,d=
$jscomp.propertyToPolyfillSymbol[d],$jscomp.defineProperty(c,d,{configurable:!0,writable:!0,value:b})))};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(e){}return!1};$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;
$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.generator={};
$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};
$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};
$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype["return"]=function(a){this.abruptCompletion_={"return":a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};
$jscomp.generator.Context.prototype.yieldAll=function(a,b){var e=$jscomp.makeIterator(a),c=e.next();$jscomp.generator.ensureIteratorResultIsObject_(c);if(c.done)this.yieldResult=c.value,this.nextAddress=b;else return this.yieldAllIterator_=e,this.yield(c.value,b)};$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};
$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,e){e?this.finallyContexts_[e]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){var e=this.finallyContexts_.splice(b||0)[0];if(e=this.abruptCompletion_=this.abruptCompletion_||e){if(e.isException)return this.jumpToErrorHandler_();void 0!=e.jumpTo&&this.finallyAddress_<e.jumpTo?(this.nextAddress=e.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(e){return{value:e,done:!0}},a,this.context_["return"]);this.context_["return"](a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,e){try{var c=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(c);if(!c.done)return this.context_.stop_(),c;var d=c.value}catch(f){return this.context_.yieldAllIterator_=null,this.context_.throw_(f),this.nextStep_()}this.context_.yieldAllIterator_=null;e.call(this.context_,d);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a["return"],done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this["throw"]=function(b){return a.throw_(b)};this["return"]=function(b){return a.return_(b)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){var e=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&a.prototype&&$jscomp.setPrototypeOf(e,a.prototype);return e};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(c){return a.next(c)}function e(c){return a["throw"](c)}return new Promise(function(c,d){function f(h){h.done?c(h.value):Promise.resolve(h.value).then(b,e).then(f,d)}f(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
var setSkillLevelBound=function(a,b,e){e=$(e);var c=Number(e.val());c<a&&e.val(a);c>b&&e.val(b);e=e.find("option");for(c=0;c<e.length;++c){var d=e.eq(c),f=Number(d.val());f<a||f>b?d.prop("disabled",!0):d.prop("disabled",!1)}},validateTargetSkillLevel=function(a,b){var e=$(b),c=a.currentSkillLevel,d=[4,7,10][a.targetElite];c>d&&console.log("\uc5d0\ub7ec: \ud558\ud55c\uc774 \uc0c1\ud55c\ubcf4\ub2e4 \ud07d\ub2c8\ub2e4.",c,d,a,e);setSkillLevelBound(c,d,e)},validateCurrentSkillLevel=function(a,b){var e=
$(b),c=[4,7,10][a.currentElite];1>c&&console.log("\uc5d0\ub7ec: \ud558\ud55c\uc774 \uc0c1\ud55c\ubcf4\ub2e4 \ud07d\ub2c8\ub2e4.",1,c,a,e);setSkillLevelBound(1,c,e)},openModalPrompt=function(){$(".modal").css("display","block");$(".modal").css("opacity","1");doNotRefreshResult=!0},closeModalPrompt=function(){$(".modal").css("opacity","0");setTimeout(function(){$(".modal").css("display","none")},300);doNotRefreshResult=!1;showResult()};
$(document).ready(function(){$(".add-btn").click(function(){openModalPrompt()});$(".close-btn").click(function(){closeModalPrompt(!0)});$(window).mousedown(function(a){$(a.target).is($("#modal"))&&closeModalPrompt(!0)});$("#opname").keyup(function(){for(var a="",b=$(this).val().split(" "),e=0;e<b.length;++e)0<e&&(a+=" "),a+=b[e].charAt(0).toUpperCase()+b[e].slice(1).toLowerCase();searchingCondition.name=a;showSearchResult()});$(".rarity-btn").click(function(){var a=Number($(this).attr("name")),b=
searchingCondition.rarityArray.indexOf(a);0<=b?(searchingCondition.rarityArray.splice(b,1),$(this).removeClass("selected")):(searchingCondition.rarityArray.push(a),$(this).addClass("selected"));showSearchResult()});$(".class-btn").click(function(){var a=getTagCodeByKRTagName($(this).attr("name"));a&searchingCondition.tagCode?$(this).removeClass("selected"):$(this).addClass("selected");searchingCondition.tagCode^=a;showSearchResult()});loadLocalStorage()});
var getTextWidth=function(a){var b="font-size:"+a.css("font-size")+";";b+="font-family:"+a.css("font-family")+";";a=$('<span style="'+b+'">'+a.html()+"</span>").appendTo("body");b=a.width();a.remove();return b},centercnt=0,centerSelect=function(a){++centercnt;var b=getTextWidth(a.children(":selected"));b=a.width()-b;a.css("text-indent",b/2)},makeOpForm=function(a){var b=db.op[a].name.en,e=Number(db.op[a].rarity);b=b.toLowerCase();var c=document.createElement("div");c.className="op";c.setAttribute("name",
"op_"+a);a=document.createElement("img");a.className="remove-op thumb rarity_"+e;a.src="./images/op/thumb/"+b+".png";c.appendChild(a);b=document.createElement("span");b.innerText=" \uc815\uc608\ud654 ";c.appendChild(b);b=document.createElement("br");c.appendChild(b);b=document.createElement("select");b.className="current-elite";e=[0,0,1,2,2,2][e-1];for(a=0;a<=e;++a){var d=document.createElement("option");d.value=a;d.innerText=a+"\ub2e8\uacc4";0==a&&(d.selected=!0);b.appendChild(d)}c.appendChild(b);
b=document.createElement("span");b.innerText=" \u25b8 ";c.appendChild(b);b=document.createElement("select");b.className="target-elite";for(a=0;a<=e;++a)d=document.createElement("option"),d.value=a,d.innerText=a+"\ub2e8\uacc4",a==e&&(d.selected=!0),b.appendChild(d);c.appendChild(b);b=document.createElement("br");c.appendChild(b);b=document.createElement("hr");c.appendChild(b);b=document.createElement("button");b.type="button";b.className="set-current-op-level-to-max-btn";b.innerText="MAX";c.appendChild(b);
b=document.createElement("span");b.innerText=" \ub808\ubca8 ";c.appendChild(b);b=document.createElement("button");b.type="button";b.className="set-target-op-level-to-max-btn";b.innerText="MAX";c.appendChild(b);b=document.createElement("br");c.appendChild(b);b=document.createElement("input");b.type="text";b.className="current-op-level";b.value="1";c.appendChild(b);b=document.createElement("span");b.innerText=" \u25b8 ";c.appendChild(b);b=document.createElement("input");b.type="text";b.className="target-op-level";
b.value="1";c.appendChild(b);b=document.createElement("br");c.appendChild(b);b=document.createElement("hr");c.appendChild(b);b=document.createElement("span");b.innerText="\uc2a4\ud0ac \ub808\ubca8";c.appendChild(b);b=document.createElement("br");c.appendChild(b);a=document.createElement("div");a.className="skill";e=[4,7,7][e];for(var f=1;3>=f;++f){1<f&&(b=document.createElement("br"),a.appendChild(b));b=document.createElement("span");b.innerText=f+"\uc2a4\ud0ac ";a.appendChild(b);b=document.createElement("select");
b.className="current-skill-level";for(var h=1;10>=h;++h)d=document.createElement("option"),d.value=h,d.innerText=h,b.appendChild(d);a.appendChild(b);b=document.createElement("span");b.innerText=" \u25b8 ";a.appendChild(b);b=document.createElement("select");b.className="target-skill-level";for(h=1;10>=h;++h)d=document.createElement("option"),d.value=h,d.innerText=h,h==e&&(d.selected=!0),b.appendChild(d);a.appendChild(b)}c.appendChild(a);return c},convertOldIDToNewID=function(){var a={0:"LN02",1:"RL03",
2:"LT77",3:"RE41",4:"LM04",5:"AZ01",6:"JC01",7:"AA01",8:"FO03",9:"FO01",10:"PL03",11:"SS02",12:"LM20",13:"SR02",14:"RL06",15:"LM05",16:"NM01",17:"RL02",18:"GG01",19:"R001",20:"VC03",21:"SK01",22:"RR01",23:"SR27",24:"R137",25:"BS01",26:"GG03",27:"SR01",28:"RB01",29:"AA02",30:"LM08",31:"R132",32:"SS01",33:"RL04",34:"RL01",35:"R106",36:"AA03",37:"LT01",38:"ST01",39:"R110",40:"ST03",41:"KZ03",42:"SR03",43:"JC06",44:"YD01",45:"SG01",46:"SW01",47:"LM16",48:"LM12",49:"R130",50:"R128",51:"RL05",52:"JC05",
53:"PL05",54:"USS2",55:"LM15",56:"PL04",57:"LM19",58:"BS02",59:"FO02",60:"MN02",61:"VC05",62:"HT03",63:"PL02",64:"USS1",65:"SI01",66:"R119",67:"VC02",68:"US10",69:"R100",70:"IU04",71:"R123",72:"HK01",73:"VC04",74:"IU07",75:"R104",76:"MN03",77:"R107",78:"LT02",79:"BS03",80:"VC01",81:"ST02",82:"LM10",83:"R122",84:"KZ04",85:"RB02",86:"LM11",87:"AA04",88:"LN01",89:"IU05",90:"R124",91:"JC03",92:"USS3",93:"JC04",94:"R108",95:"SW02",96:"R105",97:"PA15",98:"PA42",99:"PA41",100:"PA62",101:"PA65",102:"PA43",
103:"PA13",104:"PA44",105:"PA63",106:"PA12",107:"PA61",108:"PA14",109:"PA45",110:"PA64",111:"PA11",112:"LT05",113:"BS04",114:"R303",115:"A44",116:"A43",117:"A41",118:"A42",119:"RCX3",120:"RCX2"},b=Object.keys(localStorage).filter(function(k){return 0<=k.indexOf("optotal_")}),e="",c="",d="";e="";for(var f=0,h=b.length;f<h;++f)d=b[f].split("_"),e=d[1],d[1]=a[e],d[1]?(d=d.join("_"),c=b[f],e=localStorage.getItem(c),localStorage.setItem(d,e),localStorage.removeItem(c)):console.error(e+": \uc624\ud37c\ub808\uc774\ud130 ID \uccb4\uacc4 \ucd5c\uc2e0\ud654 \uc2e4\ud328. \ub9e4\uce6d\ub418\ub294 ID\uac00 \uc874\uc7ac\ud558\uc9c0 \uc54a\uc74c.");
localStorage.setItem("version_optotal_localStorage",JSON.stringify(db.idVersion.op))},sleep=function(a){return new Promise(function(b,e){setTimeout(b,a)})},loadLocalStorage=function(){var a,b,e,c,d,f,h,k,m,g,l,n,q,p;return $jscomp.asyncExecutePromiseGeneratorProgram(function(r){switch(r.nextAddress){case 1:JSON.parse(localStorage.getItem("version_optotal_localStorage")||"1")<db.idVersion.op&&(console.log("\uc624\ud37c\ub808\uc774\ud130 ID \uccb4\uacc4 \ucd5c\uc2e0\ud654 \uc218\ud589"),convertOldIDToNewID());
a="current-elite target-elite current-op-level target-op-level current-skill-level target-skill-level".split(" ");b={IDs:[]};for(e=0;e<db.op.keys.length;++e){c=db.op.keys[e];d="optotal_"+c+"_";b[c]=[];f=!1;for(h=0;h<a.length;++h)k=d+a[h],null!==localStorage.getItem(k)&&(b[c].push(a[h]),f=!0);f&&b.IDs.push(c)}if(0===b.IDs.length)return r["return"]();doNotRefreshResult=!0;e=0;case 2:if(!(e<b.IDs.length)){r.jumpTo(4);break}c=b.IDs[e];d="optotal_"+c+"_";m={keys:[]};for(h=0;h<b[c].length;++h)g=b[c][h],
k=d+g,l=JSON.parse(localStorage.getItem(k)),m[g]=l,m.keys.push(g);addOp(c,!1);n=$('div[name="op_'+c+'"].op');for(h=0;h<m.keys.length;++h)if(k=m.keys[h],l=m[k],"current-elite"===k)n.find(".current-elite").val(l),n.find(".current-elite").trigger("change");else if("target-elite"===k)n.find(".target-elite").val(l);else if("current-op-level"===k)n.find(".current-op-level").val(l);else if("target-op-level"===k)n.find(".target-op-level").val(l);else if("current-skill-level"===k)for(q=n.find(".current-skill-level"),
p=0;p<l.length;++p)q.eq(p).val(l[p]);else if("target-skill-level"===k)for(q=n.find(".target-skill-level"),p=0;p<l.length;++p)q.eq(p).val(l[p]);n.find(".current-elite").trigger("change");return r.yield(sleep(20),3);case 3:++e;r.jumpTo(2);break;case 4:doNotRefreshResult=!1,showResult(),r.jumpToEnd()}})},removeAllOperators=function(a){confirm("\uc8fc\uc758: \uc774 \uc791\uc5c5\uc740 \ub418\ub3cc\ub9b4 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4.\n\uc815\ub9d0 \uc774 \uc11c\ube44\uc2a4\uc758 \ubaa8\ub4e0 \ub370\uc774\ud130\ub97c \uc0ad\uc81c\ud558\uc2dc\uaca0\uc2b5\ub2c8\uae4c?")?
(Object.keys(localStorage).filter(function(b){return 0<=b.indexOf("optotal_")}).forEach(function(b){return localStorage.removeItem(b)}),location.reload()):alert("\ub370\uc774\ud130 \uc0ad\uc81c\uac00 \ucde8\uc18c\ub418\uc5c8\uc2b5\ub2c8\ub2e4.")},addOp=function(a,b){if(0>=$('#selected-op div[name|="op_'+a+'"]').length){$("#selected-op").append(makeOpForm(a));var e=$('div[name="op_'+a+'"].op');e.find(".remove-op").off("mousedown").on("mousedown",function(){$(this).parent().css("opacity",.5)});e.find(".remove-op").off("mouseout").on("mouseout",
function(){$(this).parent().css("opacity",1)});e.find(".remove-op").off("click").on("click",function(){var c=$(this).parent(),d=$(this).parent().attr("name").split("_")[1];d in db.op?(c.css("opacity",0),setTimeout(function(){c.remove();for(var f="optotal_"+d+"_",h="current-elite target-elite current-op-level target-op-level current-skill-level target-skill-level".split(" "),k=0;k<h.length;++k)localStorage.removeItem(f+h[k]);0===$('div[name*="op_"].op').length&&$("#selected-op-guide").css("display",
"block");showResult()},100)):console.error("\uc5d0\ub7ec: \ucde8\ub4dd\ud55c \uc624\ud37c\ub808\uc774\ud130 \uc544\uc774\ub514("+d+")\ub97c DB\uc5d0\uc11c \ucc3e\uc744 \uc218 \uc5c6\uc74c")});e.find(".set-current-op-level-to-max-btn").off("click").on("click",function(){var c=$(this).parent(),d=c.attr("name").split("_")[1],f=c.find(".current-op-level");({})["current-op-level"]=Number(f.val());d in db.op?(c=Number(c.find(".current-elite").val()),d=getMaxLevel(c,Number(db.op[d].rarity)),f.val(d),f.trigger("change")):
console.error("\uc5d0\ub7ec: \ucde8\ub4dd\ud55c \uc624\ud37c\ub808\uc774\ud130 \uc544\uc774\ub514("+d+")\ub97c DB\uc5d0\uc11c \ucc3e\uc744 \uc218 \uc5c6\uc74c")});e.find(".set-target-op-level-to-max-btn").off("click").on("click",function(){var c=$(this).parent(),d=c.attr("name").split("_")[1],f=c.find(".target-op-level");({})["target-op-level"]=Number(f.val());d in db.op?(c=Number(c.find(".target-elite").val()),d=getMaxLevel(c,Number(db.op[d].rarity)),f.val(d),f.trigger("change")):console.error("\uc5d0\ub7ec: \ucde8\ub4dd\ud55c \uc624\ud37c\ub808\uc774\ud130 \uc544\uc774\ub514("+
d+")\ub97c DB\uc5d0\uc11c \ucc3e\uc744 \uc218 \uc5c6\uc74c")});e.find(".current-elite").off("change").on("change",function(){var c=$(this).parent(),d=c.attr("name").split("_")[1];if(d in db.op){var f=c.find(".current-elite"),h=c.find(".target-elite"),k=c.find(".current-op-level");c=c.find(".current-skill-level");var m={};m["target-elite"]=Number(h.val());m["current-op-level"]=Number(k.val());m["current-skill-level"]=[];for(var g=0;g<c.length;++g)m["current-skill-level"].push(Number(c.eq(g).val()));
Number(f.val())>Number(h.val())&&h.val(f.val());m=h.find("option").length;for(g=0;g<m;++g)g<Number(f.val())?h.find('option[value="'+g+'"]').prop("disabled",!0):h.find('option[value="'+g+'"]').prop("disabled",!1);g=Number(db.op[d].rarity);m=getMaxLevel(Number(f.val()),g);Number(k.val())>m&&k.val(m);g=[0,0,1,2,2,3][g-1];"\uc544\ubbf8\uc57c"==db.op[d].name.kr&&(g=3);m=[1,2,3][Number(f.val())];m>g&&(m=g);for(g=0;g<m;++g){var l=c.eq(g);l.prop("disabled",!1);var n={};n.currentElite=Number(f.val());validateCurrentSkillLevel(n,
l)}f=c.length;for(g=m;g<f;++g)c.eq(g).val(1),c.eq(g).prop("disabled",!0);d="optotal_"+d+"_current-elite";f=Number($(this).val());f=Number.isNaN(f)?0:f;localStorage.setItem(d,f);centerSelect($(this));h.trigger("change");k.trigger("change");c.trigger("change")}else console.error("\uc5d0\ub7ec: \ucde8\ub4dd\ud55c \uc624\ud37c\ub808\uc774\ud130 \uc544\uc774\ub514("+d+")\ub97c DB\uc5d0\uc11c \ucc3e\uc744 \uc218 \uc5c6\uc74c")});e.find(".target-elite").off("change").on("change",function(){var c=$(this).parent(),
d=c.attr("name").split("_")[1];if(d in db.op){c.find(".current-elite");var f=c.find(".target-elite"),h=c.find(".target-op-level"),k=c.find(".target-skill-level");c=c.find(".current-skill-level");var m={};m["target-op-level"]=Number(h.val());m["target-skill-level"]=[];for(var g=0;g<k.length;++g)m["target-skill-level"].push(Number(k.eq(g).val()));g=Number(db.op[d].rarity);m=getMaxLevel(Number(f.val()),g);h.val()>m&&h.val(m);g=[0,0,1,2,2,3][g-1];"\uc544\ubbf8\uc57c"==db.op[d].name.kr&&(g=3);m=[1,2,3][Number(f.val())];
m>g&&(m=g);for(g=0;g<m;++g){var l=k.eq(g),n=Number(f.val()),q=Number(c.eq(g).val());l.prop("disabled",!1);var p={};p.targetElite=n;p.currentSkillLevel=q;validateTargetSkillLevel(p,l)}f=k.length;for(g=m;g<f;++g)k.eq(g).val(1),k.eq(g).prop("disabled",!0);d="optotal_"+d+"_target-elite";f=Number($(this).val());f=Number.isNaN(f)?2:f;localStorage.setItem(d,f);centerSelect($(this));h.trigger("change");k.trigger("change")}else console.error("\uc5d0\ub7ec: \ucde8\ub4dd\ud55c \uc624\ud37c\ub808\uc774\ud130 \uc544\uc774\ub514("+
d+")\ub97c DB\uc5d0\uc11c \ucc3e\uc744 \uc218 \uc5c6\uc74c")});e.find(".current-op-level").off("change").on("change",function(){var c=$(this).parent(),d=c.attr("name").split("_")[1];if(d in db.op){c=Number(c.find(".current-elite").val());c=getMaxLevel(c,Number(db.op[d].rarity));var f=Number($(this).val());f=Number.isNaN(f)?1:f;f=1>f?1:f;f=f>c?c:f;$(this).val(f);localStorage.setItem("optotal_"+d+"_current-op-level",f);showResult()}else console.error("\uc5d0\ub7ec: \ucde8\ub4dd\ud55c \uc624\ud37c\ub808\uc774\ud130 \uc544\uc774\ub514("+
d+")\ub97c DB\uc5d0\uc11c \ucc3e\uc744 \uc218 \uc5c6\uc74c")});e.find(".target-op-level").off("change").on("change",function(){var c=$(this).parent(),d=c.attr("name").split("_")[1];if(d in db.op){c=Number(c.find(".target-elite").val());c=getMaxLevel(c,Number(db.op[d].rarity));var f=Number($(this).val());f=Number.isNaN(f)?1:f;f=1>f?1:f;f=f>c?c:f;$(this).val(f);localStorage.setItem("optotal_"+d+"_target-op-level",f);showResult()}else console.error("\uc5d0\ub7ec: \ucde8\ub4dd\ud55c \uc624\ud37c\ub808\uc774\ud130 \uc544\uc774\ub514("+
d+")\ub97c DB\uc5d0\uc11c \ucc3e\uc744 \uc218 \uc5c6\uc74c")});e.find(".current-skill-level").off("change").on("change",function(){if(!0!==$(this).prop("disabled")){for(var c=Number($(this).val()),d=$(this).parent().parent(),f=d.find(".target-skill-level:enabled").length,h=d.find(".current-skill-level"),k=d.find(".target-skill-level"),m={"target-skill-level":[]},g=0;g<k.length;++g)m["target-skill-level"].push(Number(k.eq(g).val()));if(6>=c)for(g=0;g<f;++g){var l=h.eq(g);m=k.eq(g);var n=Number(d.find(".target-elite").val()),
q=Number(l.val());l.val(c);l={};l.targetElite=n;l.currentSkillLevel=q;validateTargetSkillLevel(l,m)}else for(g=0;g<f;++g)l=h.eq(g),m=k.eq(g),n=Number(d.find(".target-elite").val()),q=Number(l.val()),7>q&&l.val(7),l={},l.targetElite=n,l.currentSkillLevel=q,validateTargetSkillLevel(l,m);g=d.attr("name").split("_")[1];if(g in db.op){c="optotal_"+g+"_current-skill-level";d=[];for(g=0;g<h.length;++g)d.push(Number(h.eq(g).val()));d=JSON.stringify(d);localStorage.setItem(c,d);centerSelect($(this));k.trigger("change")}else console.error("\uc5d0\ub7ec: \ucde8\ub4dd\ud55c \uc624\ud37c\ub808\uc774\ud130 \uc544\uc774\ub514("+
g+")\ub97c DB\uc5d0\uc11c \ucc3e\uc744 \uc218 \uc5c6\uc74c")}});e.find(".target-skill-level").off("change").on("change",function(){if(!0!==$(this).prop("disabled")){var c=Number($(this).val()),d=$(this).parent().parent(),f=d.find(".target-skill-level:enabled").length,h=Number(d.find(".current-skill-level").eq(0).val());7<h&&(h=7);var k=d.find(".current-skill-level"),m=d.find(".target-skill-level");if(6>=c)for(var g=0;g<f;++g){var l=k.eq(g),n=m.eq(g),q=Number(d.find(".target-elite").val());l=Number(l.val());
l<h&&(l=h);n.val(c);var p={};p.targetElite=q;p.currentSkillLevel=l;validateTargetSkillLevel(p,n)}else for(g=0;g<f;++g)l=k.eq(g),n=m.eq(g),q=Number(d.find(".target-elite").val()),l=Number(l.val()),l<h&&(l=h),7>Number(n.val())&&n.val(7),p={},p.targetElite=q,p.currentSkillLevel=l,validateTargetSkillLevel(p,n);g=d.attr("name").split("_")[1];if(g in db.op){c="optotal_"+g+"_target-skill-level";d=[];for(g=0;g<m.length;++g)d.push(Number(m.eq(g).val()));d=JSON.stringify(d);localStorage.setItem(c,d);centerSelect($(this));
showResult()}else console.error("\uc5d0\ub7ec: \ucde8\ub4dd\ud55c \uc624\ud37c\ub808\uc774\ud130 \uc544\uc774\ub514("+g+")\ub97c DB\uc5d0\uc11c \ucc3e\uc744 \uc218 \uc5c6\uc74c")}});e.find(".current-elite").trigger("change");$("#selected-op-guide").css("display","none")}else console.log("\uc774\ubbf8 \ucd94\uac00\ub418\uc5b4 \uc788\uc74c",a,db.op[a].name.kr)},searchingCondition={name:"",rarityArray:[],tagCode:0},getTagCodeByKRTagName=function(a){for(var b=0;b<db.tag.keys.length;++b)if(db.tag[db.tag.keys[b]].name.kr==
a)return Number(db.tag[db.tag.keys[b]].tagCode)},showSearchResult=function(){searchingCondition.rarityArray.sort(function(f,h){return f>h?-1:1});for(var a=searchOp(searchingCondition.name,searchingCondition.rarityArray,searchingCondition.tagCode),b=[],e=0,c=a.keys.length,d="";e<c;++e)d=a.keys[e],b.push([a[d].name.kr,a[d].name.en,d]);b.sort(function(f,h){return f[0].localeCompare(h[0])});a="";for(e=0;e<b.length;++e)a+='<div class="search-result-op" name="op_'+b[e][2]+'"><img src="./images/op/thumb/'+
b[e][1].toLowerCase()+'.png"><div><span>'+b[e][0]+"</span></div></div>";""==a&&(a='<p style="font-size: 0.5em; text-align: center">\uac80\uc0c9 \uacb0\uacfc\uac00 \uc5ec\uae30\uc5d0 \ud45c\uc2dc\ub429\ub2c8\ub2e4.</p>');$("div.modal-footer>div.search-result").html(a);$(".search-result-op").off("click").on("click",function(){var f=$(this).attr("name").split("_")[1];addOp(f,!0);this.style.opacity=0;setTimeout(function(){this.remove()},200)});$(".search-result-op div").each(function(){$(this).textfill()})};
(function(a){a.fn.textfill=function(b){b=parseInt(b,10);return this.each(function(){function e(){var d=c.parent(),f=d.height(),h=d.width();d=parseInt(c.css("font-size"),10);h/=c.width();var k=d*(h-.1);h=f/c.height();b=d*h;c.css("fontSize",0<b&&k>b?b:k)}var c=a("span",this);a(window).resize(function(){"block"===document.querySelector(".modal").style.display&&e()});e()})}})(jQuery);
var searchOp=function(a,b,e){for(var c={},d=Object.keys(localStorage).filter(function(n){return 0===n.indexOf("optotal_")}),f=0,h=db.op.keys.length,k="",m="";f<h;++f){k=db.op.keys[f];m="optotal_"+k;for(var g=0,l=d.length;g<l&&0!==d[g].indexOf(m);++g);g<l||(c[k]={},c[k].rarity=db.op[k].rarity,c[k].tagCode=db.op[k].tagCode,c[k].name={},c[k].name.kr=db.op[k].name.kr,c[k].name.en=db.op[k].name.en,c[k].name.jp=db.op[k].name.jp,c[k].name.cn=db.op[k].name.cn)}c.keys=Object.keys(c);a=a.replace(/(\s*)/g,"").toLowerCase();
if(0<a.replace(/(\s*)/g,"").length)for(f=0,h=c.keys.length,k="";f<h;++f)k=c.keys[f],0>c[k].name.kr.replace(/(\s*)/g,"").toLowerCase().indexOf(a)&&0>c[k].name.en.replace(/(\s*)/g,"").toLowerCase().indexOf(a)&&0>c[k].name.jp.replace(/(\s*)/g,"").toLowerCase().indexOf(a)&&0>c[k].name.cn.replace(/(\s*)/g,"").toLowerCase().indexOf(a)&&(delete c[k],c.keys.splice(f,1),--f,--h);if(0<b.length)for(a=!1,f=0,d=c.keys.length,k="";f<d;++f){k=c.keys[f];a=!1;g=0;for(l=b.length;g<l;++g)if(rarity=b[g],c[k].rarity==
rarity){a=!0;break}a||(delete c[k],c.keys.splice(f,1),--f,--d)}if(0!=e)for(f=0,h=c.keys.length,k="";f<h;++f)k=c.keys[f],e&c[k].tagCode||(delete c[k],c.keys.splice(f,1),--f,--h);return c},addResultToMcalc=function(a){var b=fetchInputData();if(!1===b)showTooltip("\uc804\uc1a1\ud560 \ub370\uc774\ud130\uac00 \uc874\uc7ac\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4",a.target,"error");else if(confirm("\uc8fc\uc758: \uc774 \uc791\uc5c5\uc740 \ub418\ub3cc\ub9b4 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4.\n\uacb0\uacfc \ub370\uc774\ud130\ub97c \uc804\uc1a1\ud558\uc2dc\ub824\uba74 \ud655\uc778 \ubc84\ud2bc\uc744 \ub20c\ub7ec\uc8fc\uc2ed\uc2dc\uc624.")){b=
sortResultData(calc(b));for(var e=0;e<b.total.IDs.length;++e){var c=Number(b.total.IDs[e]),d=Number(b.total[c]);d+=JSON.parse(localStorage.getItem("mcalc_item-need_"+c));localStorage.setItem("mcalc_item-need_"+c,JSON.stringify(d))}showTooltip("\uc131\uacf5\uc801\uc73c\ub85c \uacb0\uacfc \ub370\uc774\ud130\ub97c \uc804\uc1a1\ud558\uc600\uc2b5\ub2c8\ub2e4",a.target,"success");confirm("\uc131\uacf5\uc801\uc73c\ub85c \uacb0\uacfc \ub370\uc774\ud130\ub97c \uc804\uc1a1\ud558\uc600\uc2b5\ub2c8\ub2e4.\n\ubc14\ub85c \uc7ac\ub8cc \uacc4\uc0b0\uae30\ub85c \uc774\ub3d9\ud558\uc2dc\uaca0\uc2b5\ub2c8\uae4c?")&&
(location.href="mcalc.html")}else showTooltip("\ub370\uc774\ud130 \uc804\uc1a1\uc774 \ucde8\uc18c\ub418\uc5c8\uc2b5\ub2c8\ub2e4",a.target,"error")};