var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,e){if(a==Array.prototype||a==Object.prototype)return a;a[b]=e.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var e=a[b];if(e&&e.Math==Math)return e}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var e=$jscomp.propertyToPolyfillSymbol[b];if(null==e)return a[b];e=a[e];return void 0!==e?e:a[b]};$jscomp.polyfill=function(a,b,e,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,e,d):$jscomp.polyfillUnisolated(a,b,e,d))};
$jscomp.polyfillUnisolated=function(a,b,e,d){e=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var c=a[d];if(!(c in e))return;e=e[c]}a=a[a.length-1];d=e[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(e,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,e,d){var c=a.split(".");a=1===c.length;d=c[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var h=0;h<c.length-1;h++){var k=c[h];if(!(k in d))return;d=d[k]}c=c[c.length-1];e=$jscomp.IS_SYMBOL_NATIVE&&"es6"===e?d[c]:null;b=b(e);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,c,{configurable:!0,writable:!0,value:b}):b!==e&&($jscomp.propertyToPolyfillSymbol[c]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(c):$jscomp.POLYFILL_PREFIX+c,c=
$jscomp.propertyToPolyfillSymbol[c],$jscomp.defineProperty(d,c,{configurable:!0,writable:!0,value:b})))};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(e){}return!1};$jscomp.setPrototypeOf=$jscomp.TRUST_ES6_POLYFILLS&&"function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;
$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.generator={};
$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};
$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};
$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype.return=function(a){this.abruptCompletion_={return:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};
$jscomp.generator.Context.prototype.yieldAll=function(a,b){a=$jscomp.makeIterator(a);var e=a.next();$jscomp.generator.ensureIteratorResultIsObject_(e);if(e.done)this.yieldResult=e.value,this.nextAddress=b;else return this.yieldAllIterator_=a,this.yield(e.value,b)};$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};
$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,e){e?this.finallyContexts_[e]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){b=this.finallyContexts_.splice(b||0)[0];if(b=this.abruptCompletion_=this.abruptCompletion_||b){if(b.isException)return this.jumpToErrorHandler_();void 0!=b.jumpTo&&this.finallyAddress_<b.jumpTo?(this.nextAddress=b.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(a){return{value:a,done:!0}},a,this.context_.return);this.context_.return(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,e){try{var d=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(d);if(!d.done)return this.context_.stop_(),d;var c=d.value}catch(h){return this.context_.yieldAllIterator_=null,this.context_.throw_(h),this.nextStep_()}this.context_.yieldAllIterator_=null;e.call(this.context_,c);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a.return,done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this.throw=function(b){return a.throw_(b)};this.return=function(b){return a.return_(b)};this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){b=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&a.prototype&&$jscomp.setPrototypeOf(b,a.prototype);return b};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(b){return a.next(b)}function e(b){return a.throw(b)}return new Promise(function(d,c){function h(a){a.done?d(a.value):Promise.resolve(a.value).then(b,e).then(h,c)}h(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
$jscomp.initSymbol=function(){};$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var e=0,d=function(a){if(this instanceof d)throw new TypeError("Symbol is not a constructor");return new b("jscomp_symbol_"+(a||"")+"_"+e++,a)};return d},"es6","es3");$jscomp.initSymbolIterator=function(){};
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),e=0;e<b.length;e++){var d=$jscomp.global[b[e]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&$jscomp.defineProperty(d.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.initSymbolAsyncIterator=function(){};$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function e(a){return a instanceof c?a:new c(function(b,d){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})}this.batch_.push(a)};var d=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){d(a,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var d=a[b];a[b]=null;try{d()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var c=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(f){b.reject(f)}};c.prototype.createResolveAndReject_=function(){function a(a){return function(e){d||(d=!0,a.call(b,e))}}var b=this,d=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};c.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof c)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};c.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(f){this.reject_(f);return}"function"==typeof b?
this.settleSameAsThenable_(b,a):this.fulfill_(a)};c.prototype.reject_=function(a){this.settle_(2,a)};c.prototype.fulfill_=function(a){this.settle_(1,a)};c.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};c.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)h.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var h=new b;c.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};c.prototype.settleSameAsThenable_=function(a,b){var d=this.createResolveAndReject_();try{a.call(b,d.resolve,d.reject)}catch(l){d.reject(l)}};c.prototype.then=function(a,b){function d(a,b){return"function"==typeof a?function(b){try{e(a(b))}catch(t){g(t)}}:b}var e,g,h=new c(function(a,b){e=a;g=b});this.callWhenSettled_(d(a,e),d(b,g));return h};
c.prototype.catch=function(a){return this.then(void 0,a)};c.prototype.callWhenSettled_=function(a,b){function d(){switch(e.state_){case 1:a(e.result_);break;case 2:b(e.result_);break;default:throw Error("Unexpected state: "+e.state_);}}var e=this;null==this.onSettledCallbacks_?h.asyncExecute(d):this.onSettledCallbacks_.push(d)};c.resolve=e;c.reject=function(a){return new c(function(b,d){d(a)})};c.race=function(a){return new c(function(b,d){for(var c=$jscomp.makeIterator(a),f=c.next();!f.done;f=c.next())e(f.value).callWhenSettled_(b,
d)})};c.all=function(a){var b=$jscomp.makeIterator(a),d=b.next();return d.done?e([]):new c(function(a,c){function f(b){return function(d){h[b]=d;g--;0==g&&a(h)}}var h=[],g=0;do h.push(void 0),g++,e(d.value).callWhenSettled_(f(h.length-1),c),d=b.next();while(!d.done)})};return c},"es6","es3");$jscomp.findInternal=function(a,b,e){a instanceof String&&(a=String(a));for(var d=a.length,c=0;c<d;c++){var h=a[c];if(b.call(e,h,c,a))return{i:c,v:h}}return{i:-1,v:void 0}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,e){return $jscomp.findInternal(this,a,e).v}},"es6","es3");$jscomp.iteratorFromArray=function(a,b){a instanceof String&&(a+="");var e=0,d={next:function(){if(e<a.length){var c=e++;return{value:b(c,a[c]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};
$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");$jscomp.polyfill("Number.isNaN",function(a){return a?a:function(a){return"number"===typeof a&&isNaN(a)}},"es6","es3");
var setSkillLevelBound=function(a,b,e){e=$(e);var d=Number(e.val());d<a&&e.val(a);d>b&&e.val(b);e=e.find("option");for(d=0;d<e.length;++d){var c=e.eq(d),h=Number(c.val());h<a||h>b?c.prop("disabled",!0):c.prop("disabled",!1)}},validateTargetSkillLevel=function(a,b){b=$(b);var e=a.currentSkillLevel,d=[4,7,10][a.targetElite];e>d&&console.log("\uc5d0\ub7ec: \ud558\ud55c\uc774 \uc0c1\ud55c\ubcf4\ub2e4 \ud07d\ub2c8\ub2e4.",e,d,a,b);setSkillLevelBound(e,d,b)},validateCurrentSkillLevel=function(a,b){b=$(b);
var e=[4,7,10][a.currentElite];1>e&&console.log("\uc5d0\ub7ec: \ud558\ud55c\uc774 \uc0c1\ud55c\ubcf4\ub2e4 \ud07d\ub2c8\ub2e4.",1,e,a,b);setSkillLevelBound(1,e,b)},openModalPrompt=function(){$(".modal").css("display","block");$(".modal").css("opacity","1");doNotRefreshResult=!0},closeModalPrompt=function(){$(".modal").css("opacity","0");setTimeout(function(){$(".modal").css("display","none")},300);doNotRefreshResult=!1;showResult()};
$(document).ready(function(){$(".add-btn").click(function(){openModalPrompt()});$(".close-btn").click(function(){closeModalPrompt(!0)});$(window).mousedown(function(a){$(a.target).is($("#modal"))&&closeModalPrompt(!0)});$("#opname").keyup(function(){for(var a="",b=$(this).val().split(" "),e=0;e<b.length;++e)0<e&&(a+=" "),a+=b[e].charAt(0).toUpperCase()+b[e].slice(1).toLowerCase();searchingCondition.name=a;showSearchResult()});$(".rarity-btn").click(function(){var a=Number($(this).attr("name")),b=
searchingCondition.rarityArray.indexOf(a);0<=b?(searchingCondition.rarityArray.splice(b,1),$(this).removeClass("selected")):(searchingCondition.rarityArray.push(a),$(this).addClass("selected"));showSearchResult()});$(".class-btn").click(function(){var a=getTagCodeByKRTagName($(this).attr("name"));a&searchingCondition.tagCode?$(this).removeClass("selected"):$(this).addClass("selected");searchingCondition.tagCode^=a;showSearchResult()});loadLocalStorage()});
var getTextWidth=function(a){var b="font-size:"+a.css("font-size")+";";b+="font-family:"+a.css("font-family")+";";a=$('<span style="'+b+'">'+a.html()+"</span>").appendTo("body");b=a.width();a.remove();return b},centercnt=0,centerSelect=function(a){++centercnt;var b=getTextWidth(a.children(":selected"));b=a.width()-b;a.css("text-indent",b/2)},makeOpForm=function(a){var b=db.op[a].name.en,e=Number(db.op[a].rarity);b=b.toLowerCase();var d=document.createElement("div");d.className="op";d.setAttribute("name",
"op_"+a);a=document.createElement("img");a.className="remove-op thumb rarity_"+e;a.src="./images/op/thumb/"+b+".png";d.appendChild(a);b=document.createElement("span");b.innerText=" \uc815\uc608\ud654 ";d.appendChild(b);b=document.createElement("br");d.appendChild(b);b=document.createElement("select");b.className="current-elite";e=[0,0,1,2,2,2][e-1];for(a=0;a<=e;++a){var c=document.createElement("option");c.value=a;c.innerText=a+"\ub2e8\uacc4";0==a&&(c.selected=!0);b.appendChild(c)}d.appendChild(b);
b=document.createElement("span");b.innerText=" \u25b8 ";d.appendChild(b);b=document.createElement("select");b.className="target-elite";for(a=0;a<=e;++a)c=document.createElement("option"),c.value=a,c.innerText=a+"\ub2e8\uacc4",a==e&&(c.selected=!0),b.appendChild(c);d.appendChild(b);b=document.createElement("br");d.appendChild(b);b=document.createElement("hr");d.appendChild(b);b=document.createElement("button");b.type="button";b.className="set-current-op-level-to-max-btn";b.innerText="MAX";d.appendChild(b);
b=document.createElement("span");b.innerText=" \ub808\ubca8 ";d.appendChild(b);b=document.createElement("button");b.type="button";b.className="set-target-op-level-to-max-btn";b.innerText="MAX";d.appendChild(b);b=document.createElement("br");d.appendChild(b);b=document.createElement("input");b.type="text";b.className="current-op-level";b.value="1";d.appendChild(b);b=document.createElement("span");b.innerText=" \u25b8 ";d.appendChild(b);b=document.createElement("input");b.type="text";b.className="target-op-level";
b.value="1";d.appendChild(b);b=document.createElement("br");d.appendChild(b);b=document.createElement("hr");d.appendChild(b);b=document.createElement("span");b.innerText="\uc2a4\ud0ac \ub808\ubca8";d.appendChild(b);b=document.createElement("br");d.appendChild(b);a=document.createElement("div");a.className="skill";e=[4,7,7][e];for(var h=1;3>=h;++h){1<h&&(b=document.createElement("br"),a.appendChild(b));b=document.createElement("span");b.innerText=h+"\uc2a4\ud0ac ";a.appendChild(b);b=document.createElement("select");
b.className="current-skill-level";for(var k=1;10>=k;++k)c=document.createElement("option"),c.value=k,c.innerText=k,b.appendChild(c);a.appendChild(b);b=document.createElement("span");b.innerText=" \u25b8 ";a.appendChild(b);b=document.createElement("select");b.className="target-skill-level";for(k=1;10>=k;++k)c=document.createElement("option"),c.value=k,c.innerText=k,k==e&&(c.selected=!0),b.appendChild(c);a.appendChild(b)}d.appendChild(a);return d},convertOldIDToNewID=function(){var a={0:"LN02",1:"RL03",
2:"LT77",3:"RE41",4:"LM04",5:"AZ01",6:"JC01",7:"AA01",8:"FO03",9:"FO01",10:"PL03",11:"SS02",12:"LM20",13:"SR02",14:"RL06",15:"LM05",16:"NM01",17:"RL02",18:"GG01",19:"R001",20:"VC03",21:"SK01",22:"RR01",23:"SR27",24:"R137",25:"BS01",26:"GG03",27:"SR01",28:"RB01",29:"AA02",30:"LM08",31:"R132",32:"SS01",33:"RL04",34:"RL01",35:"R106",36:"AA03",37:"LT01",38:"ST01",39:"R110",40:"ST03",41:"KZ03",42:"SR03",43:"JC06",44:"YD01",45:"SG01",46:"SW01",47:"LM16",48:"LM12",49:"R130",50:"R128",51:"RL05",52:"JC05",
53:"PL05",54:"USS2",55:"LM15",56:"PL04",57:"LM19",58:"BS02",59:"FO02",60:"MN02",61:"VC05",62:"HT03",63:"PL02",64:"USS1",65:"SI01",66:"R119",67:"VC02",68:"US10",69:"R100",70:"IU04",71:"R123",72:"HK01",73:"VC04",74:"IU07",75:"R104",76:"MN03",77:"R107",78:"LT02",79:"BS03",80:"VC01",81:"ST02",82:"LM10",83:"R122",84:"KZ04",85:"RB02",86:"LM11",87:"AA04",88:"LN01",89:"IU05",90:"R124",91:"JC03",92:"USS3",93:"JC04",94:"R108",95:"SW02",96:"R105",97:"PA15",98:"PA42",99:"PA41",100:"PA62",101:"PA65",102:"PA43",
103:"PA13",104:"PA44",105:"PA63",106:"PA12",107:"PA61",108:"PA14",109:"PA45",110:"PA64",111:"PA11",112:"LT05",113:"BS04",114:"R303",115:"A44",116:"A43",117:"A41",118:"A42",119:"RCX3",120:"RCX2"},b=Object.keys(localStorage).filter(function(a){return 0<=a.indexOf("optotal_")}),e="",d="",c="";e="";for(var h=0,k=b.length;h<k;++h)c=b[h].split("_"),e=c[1],c[1]=a[e],c[1]?(c=c.join("_"),d=b[h],e=localStorage.getItem(d),localStorage.setItem(c,e),localStorage.removeItem(d)):console.error(e+": \uc624\ud37c\ub808\uc774\ud130 ID \uccb4\uacc4 \ucd5c\uc2e0\ud654 \uc2e4\ud328. \ub9e4\uce6d\ub418\ub294 ID\uac00 \uc874\uc7ac\ud558\uc9c0 \uc54a\uc74c.");
localStorage.setItem("version_optotal_localStorage",JSON.stringify(db.idVersion.op))},sleep=function(a){return new Promise(function(b,e){setTimeout(b,a)})},loadLocalStorage=function(){var a,b,e,d,c,h,k,g,f,l,m,n,p,q;return $jscomp.asyncExecutePromiseGeneratorProgram(function(r){switch(r.nextAddress){case 1:JSON.parse(localStorage.getItem("version_optotal_localStorage")||"1")<db.idVersion.op&&(console.log("\uc624\ud37c\ub808\uc774\ud130 ID \uccb4\uacc4 \ucd5c\uc2e0\ud654 \uc218\ud589"),convertOldIDToNewID());
a="current-elite target-elite current-op-level target-op-level current-skill-level target-skill-level".split(" ");b={IDs:[]};for(e=0;e<db.op.keys.length;++e){d=db.op.keys[e];c="optotal_"+d+"_";b[d]=[];h=!1;for(k=0;k<a.length;++k)g=c+a[k],null!==localStorage.getItem(g)&&(b[d].push(a[k]),h=!0);h&&b.IDs.push(d)}if(0===b.IDs.length)return r.return();doNotRefreshResult=!0;e=0;case 2:if(!(e<b.IDs.length)){r.jumpTo(4);break}d=b.IDs[e];c="optotal_"+d+"_";f={keys:[]};for(k=0;k<b[d].length;++k)l=b[d][k],g=
c+l,m=JSON.parse(localStorage.getItem(g)),f[l]=m,f.keys.push(l);addOp(d,!1);n=$('div[name="op_'+d+'"].op');for(k=0;k<f.keys.length;++k)if(g=f.keys[k],m=f[g],"current-elite"===g)n.find(".current-elite").val(m),n.find(".current-elite").trigger("change");else if("target-elite"===g)n.find(".target-elite").val(m);else if("current-op-level"===g)n.find(".current-op-level").val(m);else if("target-op-level"===g)n.find(".target-op-level").val(m);else if("current-skill-level"===g)for(p=n.find(".current-skill-level"),
q=0;q<m.length;++q)p.eq(q).val(m[q]);else if("target-skill-level"===g)for(p=n.find(".target-skill-level"),q=0;q<m.length;++q)p.eq(q).val(m[q]);n.find(".current-elite").trigger("change");return r.yield(sleep(20),3);case 3:++e;r.jumpTo(2);break;case 4:doNotRefreshResult=!1,showResult(),r.jumpToEnd()}})},removeAllOperators=function(a){confirm("\uc8fc\uc758: \uc774 \uc791\uc5c5\uc740 \ub418\ub3cc\ub9b4 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4.\n\uc815\ub9d0 \uc774 \uc11c\ube44\uc2a4\uc758 \ubaa8\ub4e0 \ub370\uc774\ud130\ub97c \uc0ad\uc81c\ud558\uc2dc\uaca0\uc2b5\ub2c8\uae4c?")?
(Object.keys(localStorage).filter(function(a){return 0<=a.indexOf("optotal_")}).forEach(function(a){return localStorage.removeItem(a)}),location.reload()):alert("\ub370\uc774\ud130 \uc0ad\uc81c\uac00 \ucde8\uc18c\ub418\uc5c8\uc2b5\ub2c8\ub2e4.")},addOp=function(a,b){0>=$('#selected-op div[name|="op_'+a+'"]').length?($("#selected-op").append(makeOpForm(a)),a=$('div[name="op_'+a+'"].op'),a.find(".remove-op").off("mousedown").on("mousedown",function(){$(this).parent().css("opacity",.5)}),a.find(".remove-op").off("mouseout").on("mouseout",
function(){$(this).parent().css("opacity",1)}),a.find(".remove-op").off("click").on("click",function(){var a=$(this).parent(),b=$(this).parent().attr("name").split("_")[1];b in db.op?(a.css("opacity",0),setTimeout(function(){a.remove();for(var d="optotal_"+b+"_",e="current-elite target-elite current-op-level target-op-level current-skill-level target-skill-level".split(" "),k=0;k<e.length;++k)localStorage.removeItem(d+e[k]);0===$('div[name*="op_"].op').length&&$("#selected-op-guide").css("display",
"block");showResult()},100)):console.error("\uc5d0\ub7ec: \ucde8\ub4dd\ud55c \uc624\ud37c\ub808\uc774\ud130 \uc544\uc774\ub514("+b+")\ub97c DB\uc5d0\uc11c \ucc3e\uc744 \uc218 \uc5c6\uc74c")}),a.find(".set-current-op-level-to-max-btn").off("click").on("click",function(){var a=$(this).parent(),b=a.attr("name").split("_")[1],c=a.find(".current-op-level");({})["current-op-level"]=Number(c.val());b in db.op?(a=Number(a.find(".current-elite").val()),b=getMaxLevel(a,Number(db.op[b].rarity)),c.val(b),c.trigger("change")):
console.error("\uc5d0\ub7ec: \ucde8\ub4dd\ud55c \uc624\ud37c\ub808\uc774\ud130 \uc544\uc774\ub514("+b+")\ub97c DB\uc5d0\uc11c \ucc3e\uc744 \uc218 \uc5c6\uc74c")}),a.find(".set-target-op-level-to-max-btn").off("click").on("click",function(){var a=$(this).parent(),b=a.attr("name").split("_")[1],c=a.find(".target-op-level");({})["target-op-level"]=Number(c.val());b in db.op?(a=Number(a.find(".target-elite").val()),b=getMaxLevel(a,Number(db.op[b].rarity)),c.val(b),c.trigger("change")):console.error("\uc5d0\ub7ec: \ucde8\ub4dd\ud55c \uc624\ud37c\ub808\uc774\ud130 \uc544\uc774\ub514("+
b+")\ub97c DB\uc5d0\uc11c \ucc3e\uc744 \uc218 \uc5c6\uc74c")}),a.find(".current-elite").off("change").on("change",function(){var a=$(this).parent(),b=a.attr("name").split("_")[1];if(b in db.op){var c=a.find(".current-elite"),h=a.find(".target-elite"),k=a.find(".current-op-level");a=a.find(".current-skill-level");var g={};g["target-elite"]=Number(h.val());g["current-op-level"]=Number(k.val());g["current-skill-level"]=[];for(var f=0;f<a.length;++f)g["current-skill-level"].push(Number(a.eq(f).val()));
Number(c.val())>Number(h.val())&&h.val(c.val());g=h.find("option").length;for(f=0;f<g;++f)f<Number(c.val())?h.find('option[value="'+f+'"]').prop("disabled",!0):h.find('option[value="'+f+'"]').prop("disabled",!1);f=Number(db.op[b].rarity);g=getMaxLevel(Number(c.val()),f);Number(k.val())>g&&k.val(g);f=[0,0,1,2,2,3][f-1];"\uc544\ubbf8\uc57c"==db.op[b].name.kr&&(f=3);g=[1,2,3][Number(c.val())];g>f&&(g=f);for(f=0;f<g;++f){var l=a.eq(f);l.prop("disabled",!1);var m={};m.currentElite=Number(c.val());validateCurrentSkillLevel(m,
l)}c=a.length;for(f=g;f<c;++f)a.eq(f).val(1),a.eq(f).prop("disabled",!0);b="optotal_"+b+"_current-elite";c=Number($(this).val());c=Number.isNaN(c)?0:c;localStorage.setItem(b,c);centerSelect($(this));h.trigger("change");k.trigger("change");a.trigger("change")}else console.error("\uc5d0\ub7ec: \ucde8\ub4dd\ud55c \uc624\ud37c\ub808\uc774\ud130 \uc544\uc774\ub514("+b+")\ub97c DB\uc5d0\uc11c \ucc3e\uc744 \uc218 \uc5c6\uc74c")}),a.find(".target-elite").off("change").on("change",function(){var a=$(this).parent(),
b=a.attr("name").split("_")[1];if(b in db.op){a.find(".current-elite");var c=a.find(".target-elite"),h=a.find(".target-op-level"),k=a.find(".target-skill-level");a=a.find(".current-skill-level");var g={};g["target-op-level"]=Number(h.val());g["target-skill-level"]=[];for(var f=0;f<k.length;++f)g["target-skill-level"].push(Number(k.eq(f).val()));f=Number(db.op[b].rarity);g=getMaxLevel(Number(c.val()),f);h.val()>g&&h.val(g);f=[0,0,1,2,2,3][f-1];"\uc544\ubbf8\uc57c"==db.op[b].name.kr&&(f=3);g=[1,2,3][Number(c.val())];
g>f&&(g=f);for(f=0;f<g;++f){var l=k.eq(f),m=Number(c.val()),n=Number(a.eq(f).val());l.prop("disabled",!1);var p={};p.targetElite=m;p.currentSkillLevel=n;validateTargetSkillLevel(p,l)}c=k.length;for(f=g;f<c;++f)k.eq(f).val(1),k.eq(f).prop("disabled",!0);b="optotal_"+b+"_target-elite";c=Number($(this).val());c=Number.isNaN(c)?2:c;localStorage.setItem(b,c);centerSelect($(this));h.trigger("change");k.trigger("change")}else console.error("\uc5d0\ub7ec: \ucde8\ub4dd\ud55c \uc624\ud37c\ub808\uc774\ud130 \uc544\uc774\ub514("+
b+")\ub97c DB\uc5d0\uc11c \ucc3e\uc744 \uc218 \uc5c6\uc74c")}),a.find(".current-op-level").off("change").on("change",function(){var a=$(this).parent(),b=a.attr("name").split("_")[1];if(b in db.op){a=Number(a.find(".current-elite").val());a=getMaxLevel(a,Number(db.op[b].rarity));var c=Number($(this).val());c=Number.isNaN(c)?1:c;c=1>c?1:c;c=c>a?a:c;$(this).val(c);localStorage.setItem("optotal_"+b+"_current-op-level",c);showResult()}else console.error("\uc5d0\ub7ec: \ucde8\ub4dd\ud55c \uc624\ud37c\ub808\uc774\ud130 \uc544\uc774\ub514("+
b+")\ub97c DB\uc5d0\uc11c \ucc3e\uc744 \uc218 \uc5c6\uc74c")}),a.find(".target-op-level").off("change").on("change",function(){var a=$(this).parent(),b=a.attr("name").split("_")[1];if(b in db.op){a=Number(a.find(".target-elite").val());a=getMaxLevel(a,Number(db.op[b].rarity));var c=Number($(this).val());c=Number.isNaN(c)?1:c;c=1>c?1:c;c=c>a?a:c;$(this).val(c);localStorage.setItem("optotal_"+b+"_target-op-level",c);showResult()}else console.error("\uc5d0\ub7ec: \ucde8\ub4dd\ud55c \uc624\ud37c\ub808\uc774\ud130 \uc544\uc774\ub514("+
b+")\ub97c DB\uc5d0\uc11c \ucc3e\uc744 \uc218 \uc5c6\uc74c")}),a.find(".current-skill-level").off("change").on("change",function(){if(!0!==$(this).prop("disabled")){for(var a=Number($(this).val()),b=$(this).parent().parent(),c=b.find(".target-skill-level:enabled").length,h=b.find(".current-skill-level"),k=b.find(".target-skill-level"),g={"target-skill-level":[]},f=0;f<k.length;++f)g["target-skill-level"].push(Number(k.eq(f).val()));if(6>=a)for(f=0;f<c;++f){var l=h.eq(f);g=k.eq(f);var m=Number(b.find(".target-elite").val()),
n=Number(l.val());l.val(a);l={};l.targetElite=m;l.currentSkillLevel=n;validateTargetSkillLevel(l,g)}else for(f=0;f<c;++f)l=h.eq(f),g=k.eq(f),m=Number(b.find(".target-elite").val()),n=Number(l.val()),7>n&&l.val(7),l={},l.targetElite=m,l.currentSkillLevel=n,validateTargetSkillLevel(l,g);f=b.attr("name").split("_")[1];if(f in db.op){a="optotal_"+f+"_current-skill-level";b=[];for(f=0;f<h.length;++f)b.push(Number(h.eq(f).val()));b=JSON.stringify(b);localStorage.setItem(a,b);centerSelect($(this));k.trigger("change")}else console.error("\uc5d0\ub7ec: \ucde8\ub4dd\ud55c \uc624\ud37c\ub808\uc774\ud130 \uc544\uc774\ub514("+
f+")\ub97c DB\uc5d0\uc11c \ucc3e\uc744 \uc218 \uc5c6\uc74c")}}),a.find(".target-skill-level").off("change").on("change",function(){if(!0!==$(this).prop("disabled")){var a=Number($(this).val()),b=$(this).parent().parent(),c=b.find(".target-skill-level:enabled").length,h=Number(b.find(".current-skill-level").eq(0).val());7<h&&(h=7);var k=b.find(".current-skill-level"),g=b.find(".target-skill-level");if(6>=a)for(var f=0;f<c;++f){var l=k.eq(f),m=g.eq(f),n=Number(b.find(".target-elite").val());l=Number(l.val());
l<h&&(l=h);m.val(a);var p={};p.targetElite=n;p.currentSkillLevel=l;validateTargetSkillLevel(p,m)}else for(f=0;f<c;++f)l=k.eq(f),m=g.eq(f),n=Number(b.find(".target-elite").val()),l=Number(l.val()),l<h&&(l=h),7>Number(m.val())&&m.val(7),p={},p.targetElite=n,p.currentSkillLevel=l,validateTargetSkillLevel(p,m);f=b.attr("name").split("_")[1];if(f in db.op){a="optotal_"+f+"_target-skill-level";b=[];for(f=0;f<g.length;++f)b.push(Number(g.eq(f).val()));b=JSON.stringify(b);localStorage.setItem(a,b);centerSelect($(this));
showResult()}else console.error("\uc5d0\ub7ec: \ucde8\ub4dd\ud55c \uc624\ud37c\ub808\uc774\ud130 \uc544\uc774\ub514("+f+")\ub97c DB\uc5d0\uc11c \ucc3e\uc744 \uc218 \uc5c6\uc74c")}}),a.find(".current-elite").trigger("change"),$("#selected-op-guide").css("display","none")):console.log("\uc774\ubbf8 \ucd94\uac00\ub418\uc5b4 \uc788\uc74c",a,db.op[a].name.kr)},searchingCondition={name:"",rarityArray:[],tagCode:0},getTagCodeByKRTagName=function(a){for(var b=0;b<db.tag.keys.length;++b)if(db.tag[db.tag.keys[b]].name.kr==
a)return Number(db.tag[db.tag.keys[b]].tagCode)},showSearchResult=function(){searchingCondition.rarityArray.sort(function(a,b){return a>b?-1:1});for(var a=searchOp(searchingCondition.name,searchingCondition.rarityArray,searchingCondition.tagCode),b=[],e=0,d=a.keys.length,c="";e<d;++e)c=a.keys[e],b.push([a[c].name.kr,a[c].name.en,c]);b.sort(function(a,b){return a[0].localeCompare(b[0])});a="";for(e=0;e<b.length;++e)a+='<div class="search-result-op" name="op_'+b[e][2]+'"><img src="./images/op/thumb/'+
b[e][1].toLowerCase()+'.png"><div><span>'+b[e][0]+"</span></div></div>";""==a&&(a='<p style="font-size: 0.5em; text-align: center">\uac80\uc0c9 \uacb0\uacfc\uac00 \uc5ec\uae30\uc5d0 \ud45c\uc2dc\ub429\ub2c8\ub2e4.</p>');$("div.modal-footer>div.search-result").html(a);$(".search-result-op").off("click").on("click",function(){var a=$(this),b=a.attr("name").split("_")[1];addOp(b,!0);a.css("opacity","0");setTimeout(function(){a.remove()},200)});$(".search-result-op div").each(function(){$(this).textfill()})};
(function(a){a.fn.textfill=function(b){b=parseInt(b,10);return this.each(function(){function e(){var a=d.parent(),e=a.height(),k=a.width();a=parseInt(d.css("font-size"),10);k/=d.width();var g=a*(k-.1);k=e/d.height();b=a*k;d.css("fontSize",0<b&&g>b?b:g)}var d=a("span",this);a(window).resize(function(){"block"===document.querySelector(".modal").style.display&&e()});e()})}})(jQuery);
var searchOp=function(a,b,e){for(var d={},c=Object.keys(localStorage).filter(function(a){return 0===a.indexOf("optotal_")}),h=0,k=db.op.keys.length,g="",f="";h<k;++h){g=db.op.keys[h];f="optotal_"+g;for(var l=0,m=c.length;l<m&&0!==c[l].indexOf(f);++l);l<m||(d[g]={},d[g].rarity=db.op[g].rarity,d[g].tagCode=db.op[g].tagCode,d[g].name={},d[g].name.kr=db.op[g].name.kr,d[g].name.en=db.op[g].name.en,d[g].name.jp=db.op[g].name.jp,d[g].name.cn=db.op[g].name.cn)}d.keys=Object.keys(d);a=a.replace(/(\s*)/g,"").toLowerCase();
if(0<a.replace(/(\s*)/g,"").length)for(h=0,k=d.keys.length,g="";h<k;++h)g=d.keys[h],0>d[g].name.kr.replace(/(\s*)/g,"").toLowerCase().indexOf(a)&&0>d[g].name.en.replace(/(\s*)/g,"").toLowerCase().indexOf(a)&&0>d[g].name.jp.replace(/(\s*)/g,"").toLowerCase().indexOf(a)&&0>d[g].name.cn.replace(/(\s*)/g,"").toLowerCase().indexOf(a)&&(delete d[g],d.keys.splice(h,1),--h,--k);if(0<b.length)for(a=!1,h=0,c=d.keys.length,g="";h<c;++h){g=d.keys[h];a=!1;l=0;for(m=b.length;l<m;++l)if(rarity=b[l],d[g].rarity==
rarity){a=!0;break}a||(delete d[g],d.keys.splice(h,1),--h,--c)}if(0!=e)for(h=0,k=d.keys.length,g="";h<k;++h)g=d.keys[h],e&d[g].tagCode||(delete d[g],d.keys.splice(h,1),--h,--k);return d},addResultToMcalc=function(a){var b=fetchInputData();if(!1===b)showTooltip("\uc804\uc1a1\ud560 \ub370\uc774\ud130\uac00 \uc874\uc7ac\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4",a.target,"error");else if(confirm("\uc8fc\uc758: \uc774 \uc791\uc5c5\uc740 \ub418\ub3cc\ub9b4 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4.\n\uacb0\uacfc \ub370\uc774\ud130\ub97c \uc804\uc1a1\ud558\uc2dc\ub824\uba74 \ud655\uc778 \ubc84\ud2bc\uc744 \ub20c\ub7ec\uc8fc\uc2ed\uc2dc\uc624.")){b=
sortResultData(calc(b));for(var e=0;e<b.total.IDs.length;++e){var d=Number(b.total.IDs[e]),c=Number(b.total[d]);c+=JSON.parse(localStorage.getItem("mcalc_item-need_"+d));localStorage.setItem("mcalc_item-need_"+d,JSON.stringify(c))}showTooltip("\uc131\uacf5\uc801\uc73c\ub85c \uacb0\uacfc \ub370\uc774\ud130\ub97c \uc804\uc1a1\ud558\uc600\uc2b5\ub2c8\ub2e4",a.target,"success");confirm("\uc131\uacf5\uc801\uc73c\ub85c \uacb0\uacfc \ub370\uc774\ud130\ub97c \uc804\uc1a1\ud558\uc600\uc2b5\ub2c8\ub2e4.\n\ubc14\ub85c \uc7ac\ub8cc \uacc4\uc0b0\uae30\ub85c \uc774\ub3d9\ud558\uc2dc\uaca0\uc2b5\ub2c8\uae4c?")&&
(location.href="mcalc.html")}else showTooltip("\ub370\uc774\ud130 \uc804\uc1a1\uc774 \ucde8\uc18c\ub418\uc5c8\uc2b5\ub2c8\ub2e4",a.target,"error")};
