var gtag_searchByNameUsed=!1,gtag_searchByRarityUsed=!1;gtag_searchByClassUsed=!1;
const openModalPrompt=function(){gtag("event","\ub300\uc6d0 \ucd94\uac00 \ud504\ub86c\ud504\ud2b8 \uc5f4\uae30",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"});var c=document.querySelector(".modal");c.style.display="block";c.style.opacity="1";doNotRefreshResult=!0;showSearchResult()},closeModalPrompt=function(){var c=document.querySelector(".modal");c.style.opacity="0";setTimeout(function(){c.style.display="none"},300);doNotRefreshResult=!1;showResult()};
var getAllIDs=function(c){c=c.split("-")[0];for(var b=[],d=0;d<db.op.keys.length;++d)db.op.keys[d]===c?b.push(db.op.keys[d]):0===db.op.keys[d].indexOf(c+"-")&&b.push(db.op.keys[d]);b.sort(function(g,a){g=g.split("-");a=a.split("-");1===g.length&&g.push(0);1===a.length&&a.push(0);return g[0]<a[0]?-1:g[0]>a[0]?1:Number(g[1])<Number(a[1])?-1:1});return b},main=function(){document.querySelector(".add-btn").addEventListener("click",function(){openModalPrompt()});document.querySelector(".close-btn").addEventListener("click",
function(){gtag("event","\ub300\uc6d0 \ucd94\uac00 \ud504\ub86c\ud504\ud2b8 \ub2eb\uae30: \ubc84\ud2bc \ud074\ub9ad",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"});closeModalPrompt(!0)});window.addEventListener("mousedown",function(c){"modal"===c.target.getAttribute("id")&&(gtag("event","\ub300\uc6d0 \ucd94\uac00 \ud504\ub86c\ud504\ud2b8 \ub2eb\uae30: \uc678\ubd80 \ud074\ub9ad",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"}),
closeModalPrompt(!0))});document.getElementById("opname").addEventListener("keyup",function(c){gtag_searchByNameUsed||(gtag_searchByNameUsed=!0,gtag("event","\ub300\uc6d0 \uc774\ub984\uc73c\ub85c \ucd5c\ucd08 \uac80\uc0c9",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"}));if(13===c.keyCode){for(;0<document.querySelectorAll(".search-result-op").length;)document.querySelector(".search-result-op").click();this.value="";searchingCondition.name=""}else{c=
"";for(var b=this.value.split(" "),d=0,g=b.length;d<g;++d)0!==b[d].length&&(0<d&&(c+=" "),c+=b[d][0].toUpperCase()+b[d].slice(1).toLowerCase());searchingCondition.name=c;showSearchResult()}});document.querySelectorAll(".rarity-btn").forEach(function(c){c.addEventListener("click",function(){gtag_searchByRarityUsed||(gtag_searchByRarityUsed=!0,gtag("event","\ub300\uc6d0 \ub808\uc5b4\ub3c4\ub85c \ucd5c\ucd08 \uac80\uc0c9",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"}));
var b=Number(this.getAttribute("name")),d=searchingCondition.rarityArray.indexOf(b);0<=d?(searchingCondition.rarityArray.splice(d,1),this.classList.remove("selected")):(searchingCondition.rarityArray.push(b),this.classList.add("selected"));showSearchResult()})});document.querySelectorAll(".class-btn").forEach(function(c){c.addEventListener("click",function(){gtag_searchByClassUsed||(gtag_searchByClassUsed=!0,gtag("event","\ub300\uc6d0 \ud074\ub798\uc2a4\ub85c \ucd5c\ucd08 \uac80\uc0c9",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"}));
var b=getTagCodeByKRTagName(this.getAttribute("name"));b&searchingCondition.tagCode?this.classList.remove("selected"):this.classList.add("selected");searchingCondition.tagCode^=b;showSearchResult()})});loadLocalStorage()},getTextWidth=function(c){var b="font-size:"+c.css("font-size")+";";b+="font-family:"+c.css("font-family")+";";c=$('<span style="'+b+'">'+c.html()+"</span>").appendTo("body");b=c.width();c.remove();return b},centerCnt=0,centerCacheHit=0,centerCache={},csp=[],ncsp=[],centerTime=0,
doNotCenter=!1,centerSelect=function(c){if(!doNotCenter){centerTime=Date.now();var b=c.options[c.selectedIndex].innerText,d=centerCache[b];d?(c.style.textIndent=d,csp.push(Date.now()-centerTime)):(d=$(c),c=getTextWidth($(c.options[c.selectedIndex])),c=(d.width()-c)/2,d.css("text-indent",c),centerCache[b]=c+"px",ncsp.push(Date.now()-centerTime))}};
const makeOpForm=function(c,b={}){var d={},g=!0;b||={};"object"===typeof b.values&&(d=b.values);"boolean"===typeof b.asElement&&(g=b.asElement);var a=Number(db.op[c].rarity);b=[0,0,1,2,2,2][a-1];var n=getMaxLevel(b,a),f=[4,7,7][b];db.op[c].name.en.toLowerCase();var m=Number.isInteger(d["current-elite"])?d["current-elite"]:0,h=Number.isInteger(d["target-elite"])?d["target-elite"]:b,l=Number.isInteger(d["current-op-level"])?d["current-op-level"]:1;n=Number.isInteger(d["target-op-level"])?d["target-op-level"]:
n;var k=[];if(d["current-skill-level"]){d["current-skill-level"].forEach(function(w){k.push(1<=w&&10>=w?w:1)});for(var u=0,q=3-k.length;u<q;++u)k.push(1)}else k=[1,1,1];var v=[];if(d["target-skill-level"])for(d["target-skill-level"].forEach(function(w){v.push(1<=w&&10>=w?w:f)}),u=0,q=3-v.length;u<q;++u)v.push(f);else v=[f,f,f];u=null!==db.op[c].module;q=d.module?d.module:!1;d=`<div class="remove-op thumb rarity_${a}"><button class="no-margin square caution button remove-btn">\uc81c\uac70</button><img alt=${db.op[c].releaseOrder} src="./images/op/thumb/${db.op[c].releaseOrder}.png">`;
u&&(d+='<button class="no-margin square button module-btn ',d=q?d+'selected">\ubaa8\ub4c8 \ubc18\uc601\ub428</button>':d+'">\ubaa8\ub4c8 \ubbf8\ubc18\uc601\ub428</button>');d+='</div><div class="elite"><span>\uc815\uc608\ud654</span><br><select class="current-elite">';for(a=0;a<=b;++a)d+=`<option value="${a}"`,a===m&&(d+=" selected"),d+=`>${a}\ub2e8\uacc4</option>`;d+='</select><span> \u25b8 </span><select class="target-elite">';for(a=0;a<=b;++a)d+=`<option value="${a}"`,a===h&&(d+=" selected"),d+=
`>${a}\ub2e8\uacc4</option>`;d=d+'</select></div><div class="opLevel"><hr><button type="button" class="set-current-op-level-to-max-btn">MAX</button><span> \ub808\ubca8 </span><button type="button" class="set-target-op-level-to-max-btn">MAX</button><br>'+`<input type="text" class="current-op-level" value="${l}">`+"<span> \u25b8 </span>"+`<input type="text" class="target-op-level" value="${n}"></div><hr>`;b=getNumOfSkills(c);if(0<b)for(d+="<span>\uc2a4\ud0ac \ub808\ubca8</span><br>",d+='<div class="skill">',
u=1;u<=b;++u){1<u&&(d+="<br>");d+=`<span>${u}\uc2a4\ud0ac </span>`;d+=`<select class="current-skill-level" data-index="${u-1}">`;for(m=1;10>=m;++m)d+=`<option value="${m}"`,m===k[u-1]&&(d+="selected"),d+=`>${m}</option>`;d+="</select>";d+="<span> \u25b8 </span>";d+=`<select class="target-skill-level" data-index="${u-1}">`;for(m=1;10>=m;++m)d+=`<option value="${m}"`,m===v[u-1]&&(d+="selected"),d+=`>${m}</option>`;d+="</select>"}d+="</div></div>";return g?(g=document.createElement("div"),g.classList.add("op"),
g.setAttribute("name",`op_${c}`),g.innerHTML=d,g):`<div class="op" name="op_${c}">`+d+"</div>"};
var convertOldIDToNewID=function(){gtag("event","ID \uccb4\uacc4 \uc804\ud658(\ubc84\uc804 1\uc5d0\uc11c 2\ub85c)",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"});var c={0:"LN02",1:"RL03",2:"LT77",3:"RE41",4:"LM04",5:"AZ01",6:"JC01",7:"AA01",8:"FO03",9:"FO01",10:"PL03",11:"SS02",12:"LM20",13:"SR02",14:"RL06",15:"LM05",16:"NM01",17:"RL02",18:"GG01",19:"R001",20:"VC03",21:"SK01",22:"RR01",23:"SR27",24:"R137",25:"BS01",26:"GG03",27:"SR01",28:"RB01",29:"AA02",
30:"LM08",31:"R132",32:"SS01",33:"RL04",34:"RL01",35:"R106",36:"AA03",37:"LT01",38:"ST01",39:"R110",40:"ST03",41:"KZ03",42:"SR03",43:"JC06",44:"YD01",45:"SG01",46:"SW01",47:"LM16",48:"LM12",49:"R130",50:"R128",51:"RL05",52:"JC05",53:"PL05",54:"USS2",55:"LM15",56:"PL04",57:"LM19",58:"BS02",59:"FO02",60:"MN02",61:"VC05",62:"HT03",63:"PL02",64:"USS1",65:"SI01",66:"R119",67:"VC02",68:"US10",69:"R100",70:"IU04",71:"R123",72:"HK01",73:"VC04",74:"IU07",75:"R104",76:"MN03",77:"R107",78:"LT02",79:"BS03",80:"VC01",
81:"ST02",82:"LM10",83:"R122",84:"KZ04",85:"RB02",86:"LM11",87:"AA04",88:"LN01",89:"IU05",90:"R124",91:"JC03",92:"USS3",93:"JC04",94:"R108",95:"SW02",96:"R105",97:"PA15",98:"PA42",99:"PA41",100:"PA62",101:"PA65",102:"PA43",103:"PA13",104:"PA44",105:"PA63",106:"PA12",107:"PA61",108:"PA14",109:"PA45",110:"PA64",111:"PA11",112:"LT05",113:"BS04",114:"R303",115:"A44",116:"A43",117:"A41",118:"A42",119:"RCX3",120:"RCX2"},b=Object.keys(localStorage).filter(m=>0<=m.indexOf("optotal_")),d="",g="",a="";d="";
for(var n=0,f=b.length;n<f;++n)a=b[n].split("_"),d=a[1],a[1]=c[d],a[1]?(a=a.join("_"),g=b[n],d=localStorage.getItem(g),localStorage.setItem(a,d),localStorage.removeItem(g)):console.error(d+": \uc624\ud37c\ub808\uc774\ud130 ID \uccb4\uacc4 \ucd5c\uc2e0\ud654 \uc2e4\ud328. \ub9e4\uce6d\ub418\ub294 ID\uac00 \uc874\uc7ac\ud558\uc9c0 \uc54a\uc74c.");localStorage.setItem("version_optotal_localStorage",JSON.stringify(db.idVersion.op))};
const sleep=function(c){return new Promise((b,d)=>{setTimeout(b,c)})},loadLocalStorage=function(){console.log("loadLocalStorage");JSON.parse(localStorage.getItem("version_optotal_localStorage")||"1")<db.idVersion.op&&(console.log("\uc624\ud37c\ub808\uc774\ud130 ID \uccb4\uacc4 \ucd5c\uc2e0\ud654 \uc218\ud589"),convertOldIDToNewID());for(var c="current-elite target-elite current-op-level target-op-level current-skill-level target-skill-level module".split(" "),b={IDs:[]},d=0;d<db.op.keys.length;++d){var g=
db.op.keys[d],a="optotal_"+g+"_";b[g]=[];for(var n=!1,f=0;f<c.length;++f)null!==localStorage.getItem(a+c[f])&&(b[g].push(c[f]),n=!0);n&&b.IDs.push(g)}if(0===b.IDs.length)document.getElementById("content-body").style.opacity=1,console.log("loadComplete");else{document.getElementById("selected-op-guide").style.display="none";b.IDs.sort(function(m,h){if(Number(db.op[m].rarity)>Number(db.op[h].rarity))return-1;if(Number(db.op[m].rarity)<Number(db.op[h].rarity))return 1;m=m.split("-");h=h.split("-");if(m[0]<
h[0])return-1;if(m[0]>h[0])return 1;1===m.length&&m.push(0);1===h.length&&h.push(0);return Number(m[1])<Number(h[1])?-1:1});Date.now();doNotRefreshResult=!0;c="";d=0;for(g=b.IDs.length;d<g;++d)c+=`<div class="op" name="${b.IDs[d]}" style="color:#bbb;text-align:center;"><pre>\n\n\n\nLoading...</pre></div>`;document.getElementById("selected-op").innerHTML=c;document.getElementById("content-body").style.opacity=1;setTimeout(function(){for(var m="",h=0,l=b.IDs.length;h<l;++h){for(var k=b.IDs[h],u="optotal_"+
k+"_",q={keys:[]},v=0,w=b[k].length;v<w;++v){var C=b[k][v],x=JSON.parse(localStorage.getItem(u+C));q[C]=x;q.keys.push(C)}m+=makeOpForm(k,{values:q,asElement:!1})}h=document.getElementById("selected-op");h.innerHTML=m;doNotCenter=!0;h.querySelectorAll(".op").forEach(function(z){addOpEventListener(z,!0)});doNotRefreshResult=!1;showResult();console.log("loadComplete")},0)}},removeAllInputData=function(c){gtag("event","\ubaa8\ub4e0 \uc785\ub825 \ub370\uc774\ud130 \uc0ad\uc81c: \ubc84\ud2bc \ud074\ub9ad",
{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"});confirm("\uc8fc\uc758: \uc774 \uc791\uc5c5\uc740 \ub418\ub3cc\ub9b4 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4.\n\uc815\ub9d0 \uc774 \uc11c\ube44\uc2a4\uc758 \ubaa8\ub4e0 \ub370\uc774\ud130\ub97c \uc0ad\uc81c\ud558\uc2dc\uaca0\uc2b5\ub2c8\uae4c?")?(Object.keys(localStorage).filter(b=>0<=b.indexOf("optotal_")).forEach(b=>localStorage.removeItem(b)),location.reload()):(gtag("event","\ubaa8\ub4e0 \uc785\ub825 \ub370\uc774\ud130 \uc0ad\uc81c: \ucde8\uc18c",
{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"}),alert("\ub370\uc774\ud130 \uc0ad\uc81c\uac00 \ucde8\uc18c\ub418\uc5c8\uc2b5\ub2c8\ub2e4."))};
var triggerEvent=function(c,b,d=null){null!==d?c.dispatchEvent(new CustomEvent(b,{detail:d})):c.dispatchEvent(new CustomEvent(b))},getMaxElite=function(c){return[0,0,1,2,2,2][c-1]},getNumOfSkills=function(c,b=null){var d=db.op[c].rarity;null===b&&(b=getMaxElite(d));if(null===db.op[c].skill){var g=c.split("-")[0];if(g===c||null===db.op[g].skill)return console.error("\ub2e4\uc74c \uc6d0\ubcf8 \uc624\ud37c\ub808\uc774\ud130\uc758 skill \uac12\uc774 null\uc784:",c),0;c=g}c=2<=getMaxElite(d)?db.op[c].skill.mastery.length:
[0,0,1,2,2,3][d-1];g=[1,2,3][b];void 0===g&&(console.error("elite \uac12\uc5d0 \ubb38\uc81c \uc788\uc74c:",b),g=[1,2,3][getMaxElite(d)]);g>c&&(g=c);return g},getMaxSkillLevel=function(c){return[4,7,10][c]},opFormRecalcHandler=function(c){var b=this.getAttribute("name").split("_")[1],d=b.split("-")[0],g=b===d,a={};document.querySelectorAll(`#selected-op [name^="op_${d}"]`).forEach(function(e){let p=e.getAttribute("name").split("_")[1];a[p]={};a[p].form=e;a[p].currentEliteElem=e.querySelectorAll(".current-elite")[0];
a[p].targetEliteElem=e.querySelectorAll(".target-elite")[0];a[p].currentLevelElem=e.querySelectorAll(".current-op-level")[0];a[p].targetLevelElem=e.querySelectorAll(".target-op-level")[0];a[p].currentSkillLevelElems=e.querySelectorAll(".current-skill-level");a[p].targetSkillLevelElems=e.querySelectorAll(".target-skill-level");a[p].currentElite=Number(e.querySelector(".current-elite").value);a[p].targetElite=Number(e.querySelector(".target-elite").value);a[p].currentLevel=Number(e.querySelector(".current-op-level").value);
a[p].targetLevel=Number(e.querySelector(".target-op-level").value);a[p].currentSkillLevels=Array.from(e.querySelectorAll(".current-skill-level"),D=>Number(D.value));a[p].targetSkillLevels=Array.from(e.querySelectorAll(".target-skill-level"),D=>Number(D.value))});if(!g){var n=null===db.op[b].elite;var f=null===db.op[b].skill}n&&(a[b].currentElite=a[d].currentElite,a[b].targetElite=a[d].targetElite,a[b].currentLevel=a[d].currentLevel,a[b].targetLevel=a[d].targetLevel,a[b].currentEliteElem.disabled=
!0,a[b].targetEliteElem.disabled=!0,a[b].currentLevelElem.disabled=!0,a[b].targetLevelElem.disabled=!0,this.querySelectorAll(".set-current-op-level-to-max-btn, .set-target-op-level-to-max-btn").forEach(e=>e.disabled=!0),this.querySelectorAll(".elite, .opLevel").forEach(e=>e.style.opacity=0));f&&(a[b].currentSkillLevels=[...a[d].currentSkillLevels],a[b].targetSkillLevels=[...a[d].targetSkillLevels],a[b].currentSkillLevelElems.forEach(function(e){e.disabled=!0}),a[b].targetSkillLevelElems.forEach(function(e){e.disabled=
!0}),this.querySelector(".skill").style.opacity=0);var m=[a[b].currentElite,a[b].targetElite,a[b].currentLevel,a[b].targetLevel,...a[b].currentSkillLevels,...a[b].targetSkillLevels],h=this.dataset.inputValue;h=h?h.split(",").map(Number):[];var l=!1;n=0;for(var k=m.length;n<k;++n)if(m[n]!==h[n]){l=!0;break}if(l){m=Number(db.op[b].rarity);getNumOfSkills(b);l=null;l=c.detail&&c.detail.from?c.detail.from:{type:"all"};if("all"===l.type)n=c=h=!0;else{if("elite"===l.type)n=c=h=!0;else if("level"===l.type)h=
!1,c=!0,n=!1;else if("skill"===l.type){if(c=h=!1,n=!0,!Number.isInteger(l.index)||0>l.index||3<=l.index){console.error("\uc778\ub371\uc2a4 \uc624\ub958:",l.index);return}}else{console.error("\ud0c0\uc785 \uc624\ub958:",l.type);return}if("current"!==l.position&&"target"!==l.position){console.error("\ud3ec\uc9c0\uc158 \uc624\ub958:",l.position);return}}f&&(n=!1);if(h&&(f=getMaxElite(m),a[b].currentElite>f&&(a[b].currentElite=f),a[b].targetElite>f&&(a[b].targetElite=f),a[b].targetElite<a[b].currentElite&&
(a[b].targetElite=a[b].currentElite),g))for(var u in a)1==a[u].currentEliteElem.disabled&&(a[u].currentElite=a[d].currentElite),1==a[u].targetEliteElem.disabled&&(a[u].targetElite=a[d].targetElite);if(n){for(var q in a)for(d=getMaxSkillLevel(a[q].currentElite),u=getNumOfSkills(q),f=0;f<u;++f)a[q].currentSkillLevels[f]>d&&(a[q].currentSkillLevels[f]=d);if("skill"===l.type&&"current"===l.position){let e=a[b].currentSkillLevels[l.index];if(7>e)for(var v in a)a[v].currentSkillLevels=a[v].currentSkillLevels.map(p=>
e);else for(let p in a)a[p].currentSkillLevels=a[p].currentSkillLevels.map(D=>7>D?7:D)}else{let e=-Infinity;for(var w in a){q=getNumOfSkills(w,a[w].currentElite);for(v=0;v<q&&(e=a[w].currentSkillLevels[v]>e?a[w].currentSkillLevels[v]:e,e=7<e?7:e,7!==e);++v);if(7===e)break}for(var C in a)a[C].currentSkillLevels=a[C].currentSkillLevels.map(p=>p<e?e:p)}console.log(JSON.parse(JSON.stringify(a)));for(var x in a)for(w=getMaxSkillLevel(a[x].targetElite),C=getNumOfSkills(x),q=0;q<C;++q)a[x].targetSkillLevels[q]<
a[x].currentSkillLevels[q]?a[x].targetSkillLevels[q]=a[x].currentSkillLevels[q]:a[x].targetSkillLevels[q]>w&&(a[x].targetSkillLevels[q]=w);if("skill"===l.type&&"target"===l.position){let e=a[b].targetSkillLevels[l.index];if(7>e)for(var z in a)a[z].targetSkillLevels=a[z].targetSkillLevels.map(p=>e);else for(var E in a)a[E].targetSkillLevels=a[E].targetSkillLevels.map(p=>7>p?7:p)}else{let e=-Infinity;for(var A in a){x=getNumOfSkills(A,a[A].targetElite);for(z=0;z<x&&(e=a[A].targetSkillLevels[z]>e?a[A].targetSkillLevels[z]:
e,e=7<e?7:e,7!==e);++z);if(7===e)break}for(var y in a)a[y].targetSkillLevels=a[y].targetSkillLevels.map(p=>p<e?e:p)}}if(c)for(var r in a)A=getMaxLevel(a[r].currentElite,m),a[r].currentLevel>A&&(a[r].currentLevel=A),1>a[r].currentLevel&&(a[r].currentLevel=1),A=getMaxLevel(a[r].targetElite,m),a[r].targetLevel>A&&(a[r].targetLevel=A),a[r].currentElite===a[r].targetElite&&a[r].targetLevel<a[r].currentLevel?a[r].targetLevel=a[r].currentLevel:1>a[r].targetLevel&&(a[r].targetLevel=1);if(h){r=null;for(var B in a){A=
getMaxElite(db.op[B].rarity);r=a[B].currentEliteElem.options;for(let e=0,p=A;e<p;++e)r[e].disabled=e>A?!0:!1;a[B].currentEliteElem.value=a[B].currentElite;r=a[B].targetEliteElem.options;for(let e=0,p=r.length;e<p;++e)r[e].disabled=e<a[B].currentElite||e>A?!0:!1;a[B].targetEliteElem.value=a[B].targetElite}}if(n)for(var t in a){B=getNumOfSkills(t);y=getNumOfSkills(t,a[t].currentElite);r=getNumOfSkills(t,a[t].targetElite);x=getMaxSkillLevel(a[t].currentElite);A=getMaxSkillLevel(a[t].targetElite);for(z=
0;z<y;++z){a[t].currentSkillLevelElems[z].disabled=!1;E=a[t].currentSkillLevelElems[z].options;for(let e=0,p=E.length;e<p;++e)E[e].disabled=e>=x?!0:!1;a[t].currentSkillLevelElems[z].value=a[t].currentSkillLevels[z]}for(;y<B;++y)a[t].currentSkillLevelElems[y].disabled=!0,a[t].currentSkillLevelElems[y].value=a[t].currentSkillLevels[y];for(y=0;y<r;++y){a[t].targetSkillLevelElems[y].disabled=!1;x=a[t].targetSkillLevelElems[y].options;for(let e=0,p=x.length,D=a[t].currentSkillLevels[y]-1;e<p;++e)x[e].disabled=
e<D||e>=A?!0:!1;a[t].targetSkillLevelElems[y].value=a[t].targetSkillLevels[y]}for(;r<B;++r)a[t].targetSkillLevelElems[r].disabled=!0,a[t].targetSkillLevelElems[r].value=a[t].targetSkillLevels[r]}if(c)for(let e in a)a[e].currentLevelElem.value=a[e].currentLevel,a[e].targetLevelElem.value=a[e].targetLevel;for(let e in a)a[e].form.dataset.inputValue=[a[e].currentElite,a[e].targetElite,a[e].currentLevel,a[e].targetLevel,...a[e].currentSkillLevels,...a[e].targetSkillLevels].join(),t="optotal_"+e+"_",localStorage.setItem(t+
"current-elite",JSON.stringify(a[e].currentElite)),localStorage.setItem(t+"current-op-level",JSON.stringify(a[e].currentLevel)),localStorage.setItem(t+"current-skill-level",JSON.stringify(a[e].currentSkillLevels)),localStorage.setItem(t+"target-elite",JSON.stringify(a[e].targetElite)),localStorage.setItem(t+"target-op-level",JSON.stringify(a[e].targetLevel)),localStorage.setItem(t+"target-skill-level",JSON.stringify(a[e].targetSkillLevels));if(g)for(b=document.querySelectorAll(`#selected-op [name^="op_${b}-"]`),
n=0;n<b.length;++n)triggerEvent(b[n],"recalc");showResult()}else console.log(b,"nodiff: return")},thumbMouseoverHandler=function(c){c.currentTarget.querySelectorAll(".remove-btn, .module-btn").forEach(function(b){b.classList.add("active")})},thumbMouseoutHandler=function(c){c.currentTarget.querySelectorAll(".remove-btn, .module-btn").forEach(function(b){b.classList.remove("active")})},removeBtnClickHandler=function(){gtag("event","\uc624\ud37c\ub808\uc774\ud130 \uc0ad\uc81c: \ubc84\ud2bc \ud074\ub9ad",
{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"});var c=this.closest(".op").getAttribute("name").split("_")[1];c=getAllIDs(c);for(var b=0;b<c.length;++b){document.querySelector(`#selected-op [name="op_${c[b]}"]`).remove();for(var d="optotal_"+c[b]+"_",g="current-elite target-elite current-op-level target-op-level current-skill-level target-skill-level module".split(" "),a=0;a<g.length;++a)localStorage.removeItem(d+g[a])}null===document.querySelector('div[name*="op_"].op')&&
(document.getElementById("selected-op-guide").style.display="block");showResult()},moduleBtnClickHandler=function(){var c=`optotal_${this.closest(".op").getAttribute("name").split("_")[1]}_module`,b=!JSON.parse(localStorage.getItem(c)||"false");localStorage.setItem(c,JSON.stringify(b));b?this.classList.add("selected"):this.classList.remove("selected");this.innerText=b?"\ubaa8\ub4c8 \ubc18\uc601\ub428":"\ubaa8\ub4c8 \ubbf8\ubc18\uc601\ub428";showResult()},setCurrentOpLevelToMaxHandler=function(){gtag("event",
"\ud604\uc7ac \ub808\ubca8 \ucd5c\ub300 \uc124\uc815",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"});if(!this.disabled){var c=this.closest(".op"),b=c.getAttribute("name").split("_")[1],d=c.querySelector(".current-op-level");if(b in db.op){var g=Number(c.querySelector(".current-elite").value);b=getMaxLevel(g,Number(db.op[b].rarity));d.value=b;triggerEvent(c,"recalc",{from:{type:"level",position:"current"}})}else console.error("\uc5d0\ub7ec: \ucde8\ub4dd\ud55c \uc624\ud37c\ub808\uc774\ud130 \uc544\uc774\ub514("+
b+")\ub97c DB\uc5d0\uc11c \ucc3e\uc744 \uc218 \uc5c6\uc74c")}},setTargetOpLevelToMaxHandler=function(){gtag("event","\ubaa9\ud45c \ub808\ubca8 \ucd5c\ub300 \uc124\uc815",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"});if(!this.disabled){var c=this.closest(".op"),b=c.getAttribute("name").split("_")[1],d=c.querySelector(".target-op-level");if(b in db.op){var g=Number(c.querySelector(".target-elite").value);b=getMaxLevel(g,Number(db.op[b].rarity));d.value=
b;triggerEvent(c,"recalc",{from:{type:"level",position:"target"}})}else console.error("\uc5d0\ub7ec: \ucde8\ub4dd\ud55c \uc624\ud37c\ub808\uc774\ud130 \uc544\uc774\ub514("+b+")\ub97c DB\uc5d0\uc11c \ucc3e\uc744 \uc218 \uc5c6\uc74c")}},currentEliteChangeHandler=function(){this.disabled||triggerEvent(this.closest(".op"),"recalc",{from:{type:"elite",position:"current"}})},targetEliteChangeHandler=function(){this.disabled||triggerEvent(this.closest(".op"),"recalc",{from:{type:"elite",position:"target"}})},
currentOpLevelChangeHandler=function(){this.disabled||triggerEvent(this.closest(".op"),"recalc",{from:{type:"level",position:"current"}})},targetOpLevelChangeHandler=function(){this.disabled||triggerEvent(this.closest(".op"),"recalc",{from:{type:"level",position:"target"}})},currentSkillLevelChangeHandler=function(c){this.disabled||triggerEvent(this.closest(".op"),"recalc",{from:{type:"skill",position:"current",index:Number(c.target.dataset.index)}})},targetSkillLevelChangeHandler=function(){this.disabled||
triggerEvent(this.closest(".op"),"recalc",{from:{type:"skill",position:"target",index:Number(event.target.dataset.index)}})};
const addOpEventListener=function(c,b=!1){c.addEventListener("recalc",opFormRecalcHandler);c.querySelector(".thumb").addEventListener("mouseover",thumbMouseoverHandler);c.querySelector(".thumb").addEventListener("mouseout",thumbMouseoutHandler);c.querySelector(".remove-btn").addEventListener("click",removeBtnClickHandler);c.querySelector(".module-btn")&&c.querySelector(".module-btn").addEventListener("click",moduleBtnClickHandler);c.querySelector(".set-current-op-level-to-max-btn").addEventListener("click",
setCurrentOpLevelToMaxHandler);c.querySelector(".set-target-op-level-to-max-btn").addEventListener("click",setTargetOpLevelToMaxHandler);c.querySelector(".current-elite").addEventListener("change",currentEliteChangeHandler);c.querySelector(".target-elite").addEventListener("change",targetEliteChangeHandler);c.querySelector(".current-op-level").addEventListener("change",currentOpLevelChangeHandler);c.querySelector(".target-op-level").addEventListener("change",targetOpLevelChangeHandler);c.querySelectorAll(".current-skill-level").forEach(function(d){d.addEventListener("change",
currentSkillLevelChangeHandler)});c.querySelectorAll(".target-skill-level").forEach(function(d){d.addEventListener("change",targetSkillLevelChangeHandler)});b&&triggerEvent(c,"recalc",{from:{type:"all"}})};var searchingCondition={name:"",rarityArray:[],tagCode:0};
const getTagCodeByKRTagName=function(c){for(var b=0;b<db.tag.keys.length;++b)if(db.tag[db.tag.keys[b]].name.kr==c)return Number(db.tag[db.tag.keys[b]].tagCode)},showSearchResult=function(){searchingCondition.rarityArray.sort(function(n,f){return n>f?-1:1});for(var c=searchOp(searchingCondition.name,searchingCondition.rarityArray,searchingCondition.tagCode),b=[],d=0,g=c.keys.length,a="";d<g;++d)a=c.keys[d],b.push([c[a].name.kr,a]);b.sort(function(n,f){return n[0].localeCompare(f[0])});c="";for(d=0;d<
b.length;++d)c+='<div class="search-result-op" name="op_'+b[d][1]+'"><img src="./images/op/thumb/'+db.op[b[d][1]].releaseOrder+'.png"><div><span>'+b[d][0]+"</span></div></div>";""==c&&(c='<p style="font-size: 0.5em; text-align: center">\uac80\uc0c9 \uacb0\uacfc\uac00 \uc874\uc7ac\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.</p>');document.querySelector(".modal-footer>.search-result").innerHTML=c;document.querySelectorAll(".search-result-op").forEach(function(n){n.addEventListener("click",function(){for(var f=
this.getAttribute("name").split("_")[1],m=f.split("-")[0],h=getAllIDs(f),l=0;l<h.length;++l)if(console.log(h[l],"\ucd94\uac00"),`optotal_${h[l]}_current-elite`in localStorage)console.error(f+": \uc774\ubbf8 \ucd94\uac00\ub41c \uc624\ud37c\ub808\uc774\ud130");else{var k=makeOpForm(h[l],{values:{},asElement:!0});document.getElementById("selected-op").appendChild(k);addOpEventListener(k,!0);document.getElementById("selected-op-guide").style.display="none";gtag("event","\uc624\ud37c\ub808\uc774\ud130 \ucd94\uac00",
{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"})}f=document.querySelectorAll('.search-result-op[name^="op_'+m+'"]');for(l=0;l<f.length;++l)f[l].remove();0===document.querySelectorAll(".modal-footer>.search-result>.search-result-op").length&&(document.querySelector(".modal-footer>.search-result").innerHTML='<p style="font-size: 0.5em; text-align: center">\uac80\uc0c9 \uacb0\uacfc\uac00 \uc874\uc7ac\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.</p>')})});document.querySelectorAll(".search-result-op div").forEach(function(n){$(n).textfill()})};
(function(c){c.fn.textfill=function(b){b=parseInt(b,10);return this.each(function(){function d(){var a=g.parent(),n=a.height(),f=a.width();a=parseInt(g.css("font-size"),10);f/=g.width();var m=a*(f-.1);f=n/g.height();b=a*(f-.1);g.css("fontSize",0<b&&m>b?b:m)}var g=c("span",this);c(window).resize(function(){"block"===document.querySelector(".modal").style.display&&d()});d()})}})(jQuery);
const searchOp=function(c,b,d){c=c.replace(/(\s*)/g,"").toLowerCase();var g=0<c.length,a=0<b.length,n=0!=d;if(!(g||a||n))return{keys:[]};for(var f={},m=Object.keys(localStorage).filter(w=>0===w.indexOf("optotal_")),h=0,l=db.op.keys.length,k="",u="";h<l;++h){k=db.op.keys[h];u="optotal_"+k;for(var q=0,v=m.length;q<v&&0!==m[q].indexOf(u);++q);q<v||(f[k]={},f[k].rarity=db.op[k].rarity,f[k].tagCode=db.op[k].tagCode,f[k].name={},f[k].name.kr=db.op[k].name.kr,f[k].name.en=db.op[k].name.en,f[k].name.jp=db.op[k].name.jp,
f[k].name.cn=db.op[k].name.cn)}f.keys=Object.keys(f);if(g)for(h=0,l=f.keys.length,k="";h<l;++h)k=f.keys[h],0>f[k].name.kr.replace(/(\s*)/g,"").toLowerCase().indexOf(c)&&0>f[k].name.en.replace(/(\s*)/g,"").toLowerCase().indexOf(c)&&0>f[k].name.jp.replace(/(\s*)/g,"").toLowerCase().indexOf(c)&&0>f[k].name.cn.replace(/(\s*)/g,"").toLowerCase().indexOf(c)&&(delete f[k],f.keys.splice(h,1),--h,--l);if(a)for(c=!1,h=0,g=f.keys.length,k="";h<g;++h){k=f.keys[h];c=!1;q=0;for(v=b.length;q<v;++q)if(rarity=b[q],
f[k].rarity==rarity){c=!0;break}c||(delete f[k],f.keys.splice(h,1),--h,--g)}if(n)for(h=0,l=f.keys.length,k="";h<l;++h)k=f.keys[h],d&f[k].tagCode||(delete f[k],f.keys.splice(h,1),--h,--l);return f},addResultToMcalc=function(c){var b=fetchInputData();if(!1===b)showTooltip("\uc804\uc1a1\ud560 \ub370\uc774\ud130\uac00 \uc874\uc7ac\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4",c.target,"error");else if(gtag("event","\uc7ac\ub8cc \uacc4\uc0b0\uae30\ub85c \uc804\uc1a1 \uc2dc\uc791",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"}),
confirm("\uacb0\uacfc \ub370\uc774\ud130\ub97c \uc804\uc1a1\ud558\uc2dc\ub824\uba74 \ud655\uc778 \ubc84\ud2bc\uc744 \ub20c\ub7ec\uc8fc\uc2ed\uc2dc\uc624.")){b=sortResultData(calc(b));for(var d=0;d<b.total.IDs.length;++d){var g=Number(b.total.IDs[d]),a=Number(b.total[g]);a+=JSON.parse(localStorage.getItem("mcalc_item-need_"+g));localStorage.setItem("mcalc_item-need_"+g,JSON.stringify(a))}showTooltip("\uc131\uacf5\uc801\uc73c\ub85c \uacb0\uacfc \ub370\uc774\ud130\ub97c \uc804\uc1a1\ud558\uc600\uc2b5\ub2c8\ub2e4",
c.target,"success");confirm("\uc131\uacf5\uc801\uc73c\ub85c \uacb0\uacfc \ub370\uc774\ud130\ub97c \uc804\uc1a1\ud558\uc600\uc2b5\ub2c8\ub2e4.\n\ubc14\ub85c \uc7ac\ub8cc \uacc4\uc0b0\uae30\ub85c \uc774\ub3d9\ud558\uc2dc\uaca0\uc2b5\ub2c8\uae4c?")&&("1"==localStorage.getItem("preferred-version_mcalc")?location.href="mcalc-legacy.html":location.href="mcalc.html")}else gtag("event","\uc7ac\ub8cc \uacc4\uc0b0\uae30\ub85c \uc804\uc1a1 \ucde8\uc18c",{event_category:"\uc624\ud37c\ub808\uc774\ud130 \uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30"}),
showTooltip("\ub370\uc774\ud130 \uc804\uc1a1\uc774 \ucde8\uc18c\ub418\uc5c8\uc2b5\ub2c8\ub2e4",c.target,"error")};main();
