var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.arrayFromIterator=function(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c};$jscomp.arrayFromIterable=function(a){return a instanceof Array?a:$jscomp.arrayFromIterator($jscomp.makeIterator(a))};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};
$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var f=a[d];if(!(f in c))return;c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var f=a.split(".");a=1===f.length;d=f[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var m=0;m<f.length-1;m++){var g=f[m];if(!(g in d))return;d=d[g]}f=f[f.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[f]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,f,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[f]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(f):$jscomp.POLYFILL_PREFIX+f,f=
$jscomp.propertyToPolyfillSymbol[f],$jscomp.defineProperty(d,f,{configurable:!0,writable:!0,value:b})))};$jscomp.polyfill("Number.isFinite",function(a){return a?a:function(a){return"number"!==typeof a?!1:!isNaN(a)&&Infinity!==a&&-Infinity!==a}},"es6","es3");$jscomp.polyfill("Number.isInteger",function(a){return a?a:function(a){return Number.isFinite(a)?a===Math.floor(a):!1}},"es6","es3");$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var c=0,d=function(a){if(this instanceof d)throw new TypeError("Symbol is not a constructor");return new b("jscomp_symbol_"+(a||"")+"_"+c++,a)};return d},"es6","es3");$jscomp.initSymbolIterator=function(){};
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=$jscomp.global[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&$jscomp.defineProperty(d.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.initSymbolAsyncIterator=function(){};$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,b){a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};
$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(a){return a instanceof f?a:new f(function(b,c){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})}this.batch_.push(a)};var d=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){d(a,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];a[b]=null;try{c()}catch(r){this.asyncThrow_(r)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var f=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(k){b.reject(k)}};f.prototype.createResolveAndReject_=function(){function a(a){return function(g){c||(c=!0,a.call(b,g))}}var b=this,c=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};f.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof f)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};f.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(k){this.reject_(k);return}"function"==typeof b?
this.settleSameAsThenable_(b,a):this.fulfill_(a)};f.prototype.reject_=function(a){this.settle_(2,a)};f.prototype.fulfill_=function(a){this.settle_(1,a)};f.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};f.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)m.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var m=new b;f.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};f.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(r){c.reject(r)}};f.prototype.then=function(a,b){function c(a,b){return"function"==typeof a?function(b){try{d(a(b))}catch(q){g(q)}}:b}var d,g,m=new f(function(a,b){d=a;g=b});this.callWhenSettled_(c(a,d),c(b,g));return m};
f.prototype.catch=function(a){return this.then(void 0,a)};f.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?m.asyncExecute(c):this.onSettledCallbacks_.push(c)};f.resolve=c;f.reject=function(a){return new f(function(b,c){c(a)})};f.race=function(a){return new f(function(b,d){for(var f=$jscomp.makeIterator(a),g=f.next();!g.done;g=f.next())c(g.value).callWhenSettled_(b,
d)})};f.all=function(a){var b=$jscomp.makeIterator(a),d=b.next();return d.done?c([]):new f(function(a,f){function g(b){return function(c){h[b]=c;k--;0==k&&a(h)}}var h=[],k=0;do h.push(void 0),k++,c(d.value).callWhenSettled_(g(h.length-1),f),d=b.next();while(!d.done)})};return f},"es6","es3");
var openModalPrompt=function(){var a=document.querySelector(".modal");a.style.display="block";a.style.opacity="1";doNotRefreshResult=!0},closeModalPrompt=function(){var a=document.querySelector(".modal");a.style.opacity="0";setTimeout(function(){a.style.display="none"},300);doNotRefreshResult=!1;showResult()},main=function(){document.querySelector(".add-btn").addEventListener("click",function(){openModalPrompt()});document.querySelector(".close-btn").addEventListener("click",function(){closeModalPrompt(!0)});
window.addEventListener("mousedown",function(a){"modal"===a.target.getAttribute("id")&&closeModalPrompt(!0)});document.getElementById("opname").addEventListener("keyup",function(){for(var a="",b=this.value.split(" "),c=0,d=b.length;c<d;++c)0!==b[c].length&&(0<c&&(a+=" "),a+=b[c][0].toUpperCase()+b[c].slice(1).toLowerCase());searchingCondition.name=a;showSearchResult()});document.querySelectorAll(".rarity-btn").forEach(function(a){a.addEventListener("click",function(){var a=Number(this.getAttribute("name")),
c=searchingCondition.rarityArray.indexOf(a);0<=c?(searchingCondition.rarityArray.splice(c,1),this.classList.remove("selected")):(searchingCondition.rarityArray.push(a),this.classList.add("selected"));showSearchResult()})});document.querySelectorAll(".class-btn").forEach(function(a){a.addEventListener("click",function(){var a=getTagCodeByKRTagName(this.getAttribute("name"));a&searchingCondition.tagCode?this.classList.remove("selected"):this.classList.add("selected");searchingCondition.tagCode^=a;showSearchResult()})});
loadLocalStorage()},getTextWidth=function(a){var b="font-size:"+a.css("font-size")+";";b+="font-family:"+a.css("font-family")+";";a=$('<span style="'+b+'">'+a.html()+"</span>").appendTo("body");b=a.width();a.remove();return b},centerCnt=0,centerCacheHit=0,centerCache={},csp=[],ncsp=[],centerTime=0,doNotCenter=!1,centerSelect=function(a){if(!doNotCenter){centerTime=Date.now();var b=a.options[a.selectedIndex].innerText,c=centerCache[b];c?(a.style.textIndent=c,csp.push(Date.now()-centerTime)):(c=$(a),
a=getTextWidth($(a.options[a.selectedIndex])),a=(c.width()-a)/2,c.css("text-indent",a),centerCache[b]=a+"px",ncsp.push(Date.now()-centerTime))}},makeOpForm=function(a,b){b=void 0===b?{}:b;var c={},d=!0;b||(b={});"object"===typeof b.values&&(c=b.values);"boolean"===typeof b.asElement&&(d=b.asElement);var f=Number(db.op[a].rarity);b=[0,0,1,2,2,2][f-1];var m=getMaxLevel(b,f),g=[4,7,7][b],t=db.op[a].name.en.toLowerCase(),k=Number.isInteger(c["current-elite"])?c["current-elite"]:0,r=Number.isInteger(c["target-elite"])?
c["target-elite"]:b,l=Number.isInteger(c["current-op-level"])?c["current-op-level"]:1;m=Number.isInteger(c["target-op-level"])?c["target-op-level"]:m;var n=[];if(c["current-skill-level"]){c["current-skill-level"].forEach(function(a){n.push(1<=a&&10>=a?a:1)});for(var h=0,v=3-n.length;h<v;++h)n.push(1)}else n=[1,1,1];var u=[];if(c["target-skill-level"])for(c["target-skill-level"].forEach(function(a){u.push(1<=a&&10>=a?a:g)}),h=0,v=3-u.length;h<v;++h)u.push(g);else u=[g,g,g];c='<div class="remove-op thumb rarity_'+
f+'"><img alt='+db.op[a].name.kr+' src="./images/op/thumb/'+t+'.png"></div><span>\uc815\uc608\ud654</span><br><select class="current-elite">';for(h=0;h<=b;++h)c+='<option value="'+h+'"',h===k&&(c+=" selected"),c+=">"+h+"\ub2e8\uacc4</option>";c+='</select><span> \u25b8 </span><select class="target-elite">';for(h=0;h<=b;++h)c+='<option value="'+h+'"',h===r&&(c+=" selected"),c+=">"+h+"\ub2e8\uacc4</option>";c=c+'</select><br><hr><button type="button" class="set-current-op-level-to-max-btn">MAX</button><span> \ub808\ubca8 </span><button type="button" class="set-target-op-level-to-max-btn">MAX</button><br><input type="text" class="current-op-level" value="'+
(l+'"><span> \u25b8 </span><input type="text" class="target-op-level" value="')+(m+'"><br><hr>');c+="<span>\uc2a4\ud0ac \ub808\ubca8</span><br>";c+='<div class="skill">';for(h=1;3>=h;++h){1<h&&(c+="<br>");c+="<span>"+h+"\uc2a4\ud0ac </span>";c+='<select class="current-skill-level" data-index="'+(h-1)+'">';for(b=1;10>=b;++b)c+='<option value="'+b+'"',b===n[h-1]&&(c+="selected"),c+=">"+b+"</option>";c+="</select>";c+="<span> \u25b8 </span>";c+='<select class="target-skill-level" data-index="'+(h-1)+
'">';for(b=1;10>=b;++b)c+='<option value="'+b+'"',b===u[h-1]&&(c+="selected"),c+=">"+b+"</option>";c+="</select>"}c+="</div></div>";return d?(d=document.createElement("div"),d.classList.add("op"),d.setAttribute("name","op_"+a),d.innerHTML=c,d):'<div class="op" name="op_'+a+'">'+c+"</div>"},convertOldIDToNewID=function(){var a={0:"LN02",1:"RL03",2:"LT77",3:"RE41",4:"LM04",5:"AZ01",6:"JC01",7:"AA01",8:"FO03",9:"FO01",10:"PL03",11:"SS02",12:"LM20",13:"SR02",14:"RL06",15:"LM05",16:"NM01",17:"RL02",18:"GG01",
19:"R001",20:"VC03",21:"SK01",22:"RR01",23:"SR27",24:"R137",25:"BS01",26:"GG03",27:"SR01",28:"RB01",29:"AA02",30:"LM08",31:"R132",32:"SS01",33:"RL04",34:"RL01",35:"R106",36:"AA03",37:"LT01",38:"ST01",39:"R110",40:"ST03",41:"KZ03",42:"SR03",43:"JC06",44:"YD01",45:"SG01",46:"SW01",47:"LM16",48:"LM12",49:"R130",50:"R128",51:"RL05",52:"JC05",53:"PL05",54:"USS2",55:"LM15",56:"PL04",57:"LM19",58:"BS02",59:"FO02",60:"MN02",61:"VC05",62:"HT03",63:"PL02",64:"USS1",65:"SI01",66:"R119",67:"VC02",68:"US10",69:"R100",
70:"IU04",71:"R123",72:"HK01",73:"VC04",74:"IU07",75:"R104",76:"MN03",77:"R107",78:"LT02",79:"BS03",80:"VC01",81:"ST02",82:"LM10",83:"R122",84:"KZ04",85:"RB02",86:"LM11",87:"AA04",88:"LN01",89:"IU05",90:"R124",91:"JC03",92:"USS3",93:"JC04",94:"R108",95:"SW02",96:"R105",97:"PA15",98:"PA42",99:"PA41",100:"PA62",101:"PA65",102:"PA43",103:"PA13",104:"PA44",105:"PA63",106:"PA12",107:"PA61",108:"PA14",109:"PA45",110:"PA64",111:"PA11",112:"LT05",113:"BS04",114:"R303",115:"A44",116:"A43",117:"A41",118:"A42",
119:"RCX3",120:"RCX2"},b=Object.keys(localStorage).filter(function(a){return 0<=a.indexOf("optotal_")}),c="",d="",f="";c="";for(var m=0,g=b.length;m<g;++m)f=b[m].split("_"),c=f[1],f[1]=a[c],f[1]?(f=f.join("_"),d=b[m],c=localStorage.getItem(d),localStorage.setItem(f,c),localStorage.removeItem(d)):console.error(c+": \uc624\ud37c\ub808\uc774\ud130 ID \uccb4\uacc4 \ucd5c\uc2e0\ud654 \uc2e4\ud328. \ub9e4\uce6d\ub418\ub294 ID\uac00 \uc874\uc7ac\ud558\uc9c0 \uc54a\uc74c.");localStorage.setItem("version_optotal_localStorage",
JSON.stringify(db.idVersion.op))},sleep=function(a){return new Promise(function(b,c){setTimeout(b,a)})},loadLocalStorage=function(){console.log("loadLocalStorage");JSON.parse(localStorage.getItem("version_optotal_localStorage")||"1")<db.idVersion.op&&(console.log("\uc624\ud37c\ub808\uc774\ud130 ID \uccb4\uacc4 \ucd5c\uc2e0\ud654 \uc218\ud589"),convertOldIDToNewID());for(var a="current-elite target-elite current-op-level target-op-level current-skill-level target-skill-level".split(" "),b={IDs:[]},
c=0;c<db.op.keys.length;++c){var d=db.op.keys[c],f="optotal_"+d+"_";b[d]=[];for(var m=!1,g=0;g<a.length;++g)null!==localStorage.getItem(f+a[g])&&(b[d].push(a[g]),m=!0);m&&b.IDs.push(d)}if(0===b.IDs.length)document.getElementById("content-body").style.opacity=1,console.log("loadComplete");else{document.getElementById("selected-op-guide").style.display="none";b.IDs.sort(function(a,b){return Number(db.op[a].rarity)>Number(db.op[b].rarity)?-1:1});Date.now();doNotRefreshResult=!0;a="";c=0;for(d=b.IDs.length;c<
d;++c)a+='<div class="op" name="'+b.IDs[c]+'" style="color:#bbb;text-align:center;"><pre>\n\n\n\nLoading...</pre></div>';document.getElementById("selected-op").innerHTML=a;document.getElementById("content-body").style.opacity=1;setTimeout(function(){for(var a="",c=0,d=b.IDs.length;c<d;++c){for(var f=b.IDs[c],g="optotal_"+f+"_",h={keys:[]},m=0,u=b[f].length;m<u;++m){var q=b[f][m],e=JSON.parse(localStorage.getItem(g+q));h[q]=e;h.keys.push(q)}a+=makeOpForm(f,{values:h,asElement:!1})}c=document.getElementById("selected-op");
c.innerHTML=a;doNotCenter=!0;c.querySelectorAll(".op").forEach(function(a){addOpEventListener(a,!0)});doNotRefreshResult=!1;showResult();console.log("loadComplete")},0)}},removeAllOperators=function(a){confirm("\uc8fc\uc758: \uc774 \uc791\uc5c5\uc740 \ub418\ub3cc\ub9b4 \uc218 \uc5c6\uc2b5\ub2c8\ub2e4.\n\uc815\ub9d0 \uc774 \uc11c\ube44\uc2a4\uc758 \ubaa8\ub4e0 \ub370\uc774\ud130\ub97c \uc0ad\uc81c\ud558\uc2dc\uaca0\uc2b5\ub2c8\uae4c?")?(Object.keys(localStorage).filter(function(a){return 0<=a.indexOf("optotal_")}).forEach(function(a){return localStorage.removeItem(a)}),
location.reload()):alert("\ub370\uc774\ud130 \uc0ad\uc81c\uac00 \ucde8\uc18c\ub418\uc5c8\uc2b5\ub2c8\ub2e4.")},triggerEvent=function(a,b,c){c=void 0===c?null:c;null!==c?a.dispatchEvent(new CustomEvent(b,{detail:c})):a.dispatchEvent(new CustomEvent(b))},getMaxElite=function(a){return[0,0,1,2,2,2][a-1]},getNumOfSkills=function(a,b){var c=db.op[a].rarity;a="R001"===a?3:[0,0,1,2,2,3][c-1];b=[1,2,3][b];void 0===b&&(b=[1,2,3][getMaxElite(c)]);b>a&&(b=a);return b},getMaxSkillLevel=function(a){return[4,7,
10][a]},opFormRecalcHandler=function(a){var b=this.querySelectorAll(".current-elite")[0],c=this.querySelectorAll(".target-elite")[0],d=this.querySelectorAll(".current-op-level")[0],f=this.querySelectorAll(".target-op-level")[0],m=this.querySelectorAll(".current-skill-level"),g=this.querySelectorAll(".target-skill-level"),t=Number(b.value),k=Number(c.value),r=Number(d.value),l=Number(f.value),n=[],h=[];m.forEach(function(a){n.push(Number(a.value))});g.forEach(function(a){h.push(Number(a.value))});
var v=[t,k,r,l].concat($jscomp.arrayFromIterable(n),$jscomp.arrayFromIterable(h)),u=this.dataset.inputValue;u=u?u.split(",").map(Number):[];for(var q=!1,e=0,x=v.length;e<x;++e)if(v[e]!==u[e]){q=!0;break}if(q){v=this.getAttribute("name").split("_")[1];x=Number(db.op[v].rarity);a.detail&&a.detail.from||(console.error("from property not exists"),a.detail={from:{type:"all"}});var p=a.detail.from;if("all"===p.type)u=a=q=!0;else{if("elite"===p.type)u=a=q=!0;else if("level"===p.type)q=!1,a=!0,u=!1;else if("skill"===
p.type){if(a=q=!1,u=!0,!Number.isInteger(p.index)||0>p.index||3<=p.index){console.error("\uc778\ub371\uc2a4 \uc624\ub958:",p.index);return}}else{console.error("\ud0c0\uc785 \uc624\ub958:",p.type);return}if("current"!==p.position&&"target"!==p.position){console.error("\ud3ec\uc9c0\uc158 \uc624\ub958:",p.position);return}}if(q){var y=getMaxElite(x);t>y&&(t=y);k>y&&(k=y);k<t&&(k=t)}if(u){var z=getNumOfSkills(v,t),A=getNumOfSkills(v,k),B=getMaxSkillLevel(t);for(e=0;3>e;++e)n[e]>B&&(n[e]=B);if("skill"===
p.type&&"current"===p.position){var w=n[p.index];if(7>w)for(e=0;3>e;++e)n[e]=w;else for(e=0;3>e;++e)7>n[e]&&(n[e]=7)}else{w=-Infinity;for(e=0;e<z;++e)if(n[e]>w&&(w=n[e],7<=w)){w=7;break}for(e=0;3>e;++e)n[e]<w&&(n[e]=w)}w=getMaxSkillLevel(k);for(e=0;3>e;++e)h[e]<n[e]?h[e]=n[e]:h[e]>w&&(h[e]=w);if("skill"===p.type&&"target"===p.position)if(p=h[p.index],7>p)for(e=0;3>e;++e)h[e]=p;else for(e=0;3>e;++e)7>h[e]&&(h[e]=7);else{p=-Infinity;for(e=0;e<A;++e)if(h[e]>p&&(p=h[e],7<=p)){p=7;break}for(e=0;3>e;++e)h[e]<
p&&(h[e]=p)}}a&&(e=getMaxLevel(t,x),r>e&&(r=e),1>r&&(r=1),e=getMaxLevel(k,x),l>e&&(l=e),t===k&&l<r?l=r:1>l&&(l=1));if(q){q=b.options;e=0;for(x=y;e<x;++e)q[e].disabled=e>y?!0:!1;b.value=t;q=c.options;e=0;for(x=q.length;e<x;++e)q[e].disabled=e<t||e>y?!0:!1;c.value=k}if(u){for(e=0;e<z;++e){m[e].disabled=!1;q=m[e].options;b=0;for(c=q.length;b<c;++b)q[b].disabled=b>=B?!0:!1;m[e].value=n[e]}for(e=z;3>e;++e)m[e].disabled=!0,m[e].value=n[e];for(e=0;e<A;++e){g[e].disabled=!1;q=g[e].options;b=0;c=q.length;
for(m=n[e]-1;b<c;++b)q[b].disabled=b<m||b>=w?!0:!1;g[e].value=h[e]}for(e=A;3>e;++e)g[e].disabled=!0,g[e].value=h[e]}a&&(d.value=r,f.value=l);this.dataset.inputValue=[t,k,r,l].concat($jscomp.arrayFromIterable(n),$jscomp.arrayFromIterable(h)).join(",");d="optotal_"+v+"_";localStorage.setItem(d+"current-elite",JSON.stringify(t));localStorage.setItem(d+"current-op-level",JSON.stringify(r));localStorage.setItem(d+"current-skill-level",JSON.stringify(n));localStorage.setItem(d+"target-elite",JSON.stringify(k));
localStorage.setItem(d+"target-op-level",JSON.stringify(l));localStorage.setItem(d+"target-skill-level",JSON.stringify(h));showResult()}else console.log("return")},removeOpMousedownHandler=function(){this.parentElement.style.opacity=.5},removeOpMouseoutHandler=function(){this.parentElement.style.opacity=1},removeOpClickHandler=function(){var a=this.parentElement,b=this.parentElement.getAttribute("name").split("_")[1];if(b in db.op){a.remove();a="optotal_"+b+"_";b="current-elite target-elite current-op-level target-op-level current-skill-level target-skill-level".split(" ");
for(var c=0;c<b.length;++c)localStorage.removeItem(a+b[c]);null===document.querySelector('div[name*="op_"].op')&&(document.getElementById("selected-op-guide").style.display="block");showResult()}else console.error("\uc5d0\ub7ec: \ucde8\ub4dd\ud55c \uc624\ud37c\ub808\uc774\ud130 \uc544\uc774\ub514("+b+")\ub97c DB\uc5d0\uc11c \ucc3e\uc744 \uc218 \uc5c6\uc74c")},setCurrentOpLevelToMaxHandler=function(){var a=this.parentElement,b=a.getAttribute("name").split("_")[1],c=a.querySelector(".current-op-level");
if(b in db.op){var d=Number(a.querySelector(".current-elite").value);b=getMaxLevel(d,Number(db.op[b].rarity));c.value=b;triggerEvent(a,"recalc",{from:{type:"level",position:"current"}})}else console.error("\uc5d0\ub7ec: \ucde8\ub4dd\ud55c \uc624\ud37c\ub808\uc774\ud130 \uc544\uc774\ub514("+b+")\ub97c DB\uc5d0\uc11c \ucc3e\uc744 \uc218 \uc5c6\uc74c")},setTargetOpLevelToMaxHandler=function(){var a=this.parentElement,b=a.getAttribute("name").split("_")[1],c=a.querySelector(".target-op-level");if(b in
db.op){var d=Number(a.querySelector(".target-elite").value);b=getMaxLevel(d,Number(db.op[b].rarity));c.value=b;triggerEvent(a,"recalc",{from:{type:"level",position:"target"}})}else console.error("\uc5d0\ub7ec: \ucde8\ub4dd\ud55c \uc624\ud37c\ub808\uc774\ud130 \uc544\uc774\ub514("+b+")\ub97c DB\uc5d0\uc11c \ucc3e\uc744 \uc218 \uc5c6\uc74c")},currentEliteChangeHandler=function(){triggerEvent(this.parentElement,"recalc",{from:{type:"elite",position:"current"}})},targetEliteChangeHandler=function(){triggerEvent(this.parentElement,
"recalc",{from:{type:"elite",position:"target"}})},currentOpLevelChangeHandler=function(){triggerEvent(this.parentElement,"recalc",{from:{type:"level",position:"current"}})},targetOpLevelChangeHandler=function(){triggerEvent(this.parentElement,"recalc",{from:{type:"level",position:"target"}})},currentSkillLevelChangeHandler=function(a){this.disabled||triggerEvent(this.parentElement.parentElement,"recalc",{from:{type:"skill",position:"current",index:Number(a.target.dataset.index)}})},targetSkillLevelChangeHandler=
function(){this.disabled||triggerEvent(this.parentElement.parentElement,"recalc",{from:{type:"skill",position:"target",index:Number(event.target.dataset.index)}})},addOpEventListener=function(a,b){b=void 0===b?!1:b;a.addEventListener("recalc",opFormRecalcHandler);a.querySelector(".remove-op").addEventListener("mousedown",removeOpMousedownHandler);a.querySelector(".remove-op").addEventListener("mouseout",removeOpMouseoutHandler);a.querySelector(".remove-op").addEventListener("click",removeOpClickHandler);
a.querySelector(".set-current-op-level-to-max-btn").addEventListener("click",setCurrentOpLevelToMaxHandler);a.querySelector(".set-target-op-level-to-max-btn").addEventListener("click",setTargetOpLevelToMaxHandler);a.querySelector(".current-elite").addEventListener("change",currentEliteChangeHandler);a.querySelector(".target-elite").addEventListener("change",targetEliteChangeHandler);a.querySelector(".current-op-level").addEventListener("change",currentOpLevelChangeHandler);a.querySelector(".target-op-level").addEventListener("change",
targetOpLevelChangeHandler);a.querySelectorAll(".current-skill-level").forEach(function(a){a.addEventListener("change",currentSkillLevelChangeHandler)});a.querySelectorAll(".target-skill-level").forEach(function(a){a.addEventListener("change",targetSkillLevelChangeHandler)});b&&triggerEvent(a,"recalc",{from:{type:"all"}})},addOp=function(a,b){b=void 0===b?{}:b;if("optotal_"+a+"_current-elite"in localStorage)console.error(a+": \uc774\ubbf8 \ucd94\uac00\ub41c \uc624\ud37c\ub808\uc774\ud130");else return a=
makeOpForm(a,{values:b,asElement:!0}),addOpEventListener(a,!0),document.getElementById("selected-op-guide").style.display="none",a},searchingCondition={name:"",rarityArray:[],tagCode:0},getTagCodeByKRTagName=function(a){for(var b=0;b<db.tag.keys.length;++b)if(db.tag[db.tag.keys[b]].name.kr==a)return Number(db.tag[db.tag.keys[b]].tagCode)},showSearchResult=function(){searchingCondition.rarityArray.sort(function(a,b){return a>b?-1:1});for(var a=searchOp(searchingCondition.name,searchingCondition.rarityArray,
searchingCondition.tagCode),b=[],c=0,d=a.keys.length,f="";c<d;++c)f=a.keys[c],b.push([a[f].name.kr,a[f].name.en,f]);b.sort(function(a,b){return a[0].localeCompare(b[0])});a="";for(c=0;c<b.length;++c)a+='<div class="search-result-op" name="op_'+b[c][2]+'"><img src="./images/op/thumb/'+b[c][1].toLowerCase()+'.png"><div><span>'+b[c][0]+"</span></div></div>";""==a&&(a='<p style="font-size: 0.5em; text-align: center">\uac80\uc0c9 \uacb0\uacfc\uac00 \uc874\uc7ac\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.</p>');
document.querySelector(".modal-footer>.search-result").innerHTML=a;document.querySelectorAll(".search-result-op").forEach(function(a){a.addEventListener("click",function(){var a=this.getAttribute("name").split("_")[1];document.getElementById("selected-op").appendChild(addOp(a));this.remove();0===document.querySelectorAll(".modal-footer>.search-result>.search-result-op").length&&(document.querySelector(".modal-footer>.search-result").innerHTML='<p style="font-size: 0.5em; text-align: center">\uac80\uc0c9 \uacb0\uacfc\uac00 \uc874\uc7ac\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.</p>')})});
document.querySelectorAll(".search-result-op div").forEach(function(a){$(a).textfill()})};(function(a){a.fn.textfill=function(b){b=parseInt(b,10);return this.each(function(){function c(){var a=d.parent(),c=a.height(),g=a.width();a=parseInt(d.css("font-size"),10);g/=d.width();var t=a*(g-.1);g=c/d.height();b=a*(g-.1);d.css("fontSize",0<b&&t>b?b:t)}var d=a("span",this);a(window).resize(function(){"block"===document.querySelector(".modal").style.display&&c()});c()})}})(jQuery);
var searchOp=function(a,b,c){a=a.replace(/(\s*)/g,"").toLowerCase();var d=0<a.length,f=0<b.length,m=0!=c;if(!(d||f||m))return{keys:[]};for(var g={},t=Object.keys(localStorage).filter(function(a){return 0===a.indexOf("optotal_")}),k=0,r=db.op.keys.length,l="",n="";k<r;++k){l=db.op.keys[k];n="optotal_"+l;for(var h=0,v=t.length;h<v&&0!==t[h].indexOf(n);++h);h<v||(g[l]={},g[l].rarity=db.op[l].rarity,g[l].tagCode=db.op[l].tagCode,g[l].name={},g[l].name.kr=db.op[l].name.kr,g[l].name.en=db.op[l].name.en,
g[l].name.jp=db.op[l].name.jp,g[l].name.cn=db.op[l].name.cn)}g.keys=Object.keys(g);if(d)for(k=0,r=g.keys.length,l="";k<r;++k)l=g.keys[k],0>g[l].name.kr.replace(/(\s*)/g,"").toLowerCase().indexOf(a)&&0>g[l].name.en.replace(/(\s*)/g,"").toLowerCase().indexOf(a)&&0>g[l].name.jp.replace(/(\s*)/g,"").toLowerCase().indexOf(a)&&0>g[l].name.cn.replace(/(\s*)/g,"").toLowerCase().indexOf(a)&&(delete g[l],g.keys.splice(k,1),--k,--r);if(f)for(a=!1,k=0,d=g.keys.length,l="";k<d;++k){l=g.keys[k];a=!1;h=0;for(v=
b.length;h<v;++h)if(rarity=b[h],g[l].rarity==rarity){a=!0;break}a||(delete g[l],g.keys.splice(k,1),--k,--d)}if(m)for(k=0,r=g.keys.length,l="";k<r;++k)l=g.keys[k],c&g[l].tagCode||(delete g[l],g.keys.splice(k,1),--k,--r);return g},addResultToMcalc=function(a){var b=fetchInputData();if(!1===b)showTooltip("\uc804\uc1a1\ud560 \ub370\uc774\ud130\uac00 \uc874\uc7ac\ud558\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4",a.target,"error");else if(confirm("\uacb0\uacfc \ub370\uc774\ud130\ub97c \uc804\uc1a1\ud558\uc2dc\ub824\uba74 \ud655\uc778 \ubc84\ud2bc\uc744 \ub20c\ub7ec\uc8fc\uc2ed\uc2dc\uc624.")){b=
sortResultData(calc(b));for(var c=0;c<b.total.IDs.length;++c){var d=Number(b.total.IDs[c]),f=Number(b.total[d]);f+=JSON.parse(localStorage.getItem("mcalc_item-need_"+d));localStorage.setItem("mcalc_item-need_"+d,JSON.stringify(f))}showTooltip("\uc131\uacf5\uc801\uc73c\ub85c \uacb0\uacfc \ub370\uc774\ud130\ub97c \uc804\uc1a1\ud558\uc600\uc2b5\ub2c8\ub2e4",a.target,"success");confirm("\uc131\uacf5\uc801\uc73c\ub85c \uacb0\uacfc \ub370\uc774\ud130\ub97c \uc804\uc1a1\ud558\uc600\uc2b5\ub2c8\ub2e4.\n\ubc14\ub85c \uc7ac\ub8cc \uacc4\uc0b0\uae30\ub85c \uc774\ub3d9\ud558\uc2dc\uaca0\uc2b5\ub2c8\uae4c?")&&
(location.href="mcalc.html")}else showTooltip("\ub370\uc774\ud130 \uc804\uc1a1\uc774 \ucde8\uc18c\ub418\uc5c8\uc2b5\ub2c8\ub2e4",a.target,"error")};main();
