const calc=function(a){for(var b,c=db.oplv.leveling.expTable,f=db.oplv.leveling.lmdTable,g,d,e=d=g=0;e<a.to.elite;++e)g+=c["elite_"+String(e)][getMaxLevel(e,a.rarity)-1];g+=c["elite_"+String(a.to.elite)][a.to.level-1];g+=a.to.exp;for(e=0;e<a.to.elite;++e)d+=f["elite_"+String(e)][getMaxLevel(e,a.rarity)-1];d+=f["elite_"+String(a.to.elite)][a.to.level-1];if(a.to.level<getMaxLevel(a.to.elite,a.rarity)){e=f["elite_"+String(a.to.elite)][a.to.level];e-=f["elite_"+String(a.to.elite)][a.to.level-1];var k=
c["elite_"+String(a.to.elite)][a.to.level];k-=c["elite_"+String(a.to.elite)][a.to.level-1];d+=Math.ceil(e/k*a.to.exp)}var h;for(e=b=h=0;e<a.from.elite;++e)h+=c["elite_"+String(e)][getMaxLevel(e,a.rarity)-1];h+=c["elite_"+String(a.from.elite)][a.from.level-1];h+=a.from.exp;for(e=0;e<a.from.elite;++e)b+=f["elite_"+String(e)][getMaxLevel(e,a.rarity)-1];b+=f["elite_"+String(a.from.elite)][a.from.level-1];a.from.level<getMaxLevel(a.from.elite,a.rarity)&&(e=f["elite_"+String(a.from.elite)][a.from.level],
e-=f["elite_"+String(a.from.elite)][a.from.level-1],k=c["elite_"+String(a.from.elite)][a.from.level],k-=c["elite_"+String(a.from.elite)][a.from.level-1],b+=Math.ceil(e/k*a.from.exp));f=a.resource.exp;k=a.resource.lmd;c={};c.exp=g-h;c.lmd=d-b;for(e=a.from.elite;e<a.to.elite;++e)c.lmd+=db.oplv.elitePromotion.lmdTable["elite_"+String(e)][a.rarity-1];g={};g.exp=c.exp-f;g.lmd=c.lmd-k;c.exp=0>c.exp?0:c.exp;c.lmd=0>c.lmd?0:c.lmd;g.exp=0>g.exp?0:g.exp;g.lmd=0>g.lmd?0:g.lmd;d={};b=db.oplv.stage.exp[a.stage.exp];
d.exp={};d.exp.name=a.stage.exp;d.exp.worst=Math.ceil(g.exp/b.reward.lowerBound);d.exp.expectation=Math.ceil(g.exp/b.reward.expectation);d.exp.best=Math.ceil(g.exp/b.reward.upperBound);b=db.oplv.stage.lmd[a.stage.lmd];d.lmd={};d.lmd.name=a.stage.lmd;d.lmd.worst=Math.ceil(g.lmd/b.reward.lowerBound);d.lmd.expectation=Math.ceil(g.lmd/b.reward.expectation);d.lmd.best=Math.ceil(g.lmd/b.reward.upperBound);h={};b=db.oplv.stage.exp[a.stage.exp].sanity;h.exp={};h.exp.worst=d.exp.worst*b;h.exp.expectation=
d.exp.expectation*b;h.exp.best=d.exp.best*b;b=db.oplv.stage.lmd[a.stage.lmd].sanity;h.lmd={};h.lmd.worst=d.lmd.worst*b;h.lmd.expectation=d.lmd.expectation*b;h.lmd.best=d.lmd.best*b;h.total={};h.total.worst=h.exp.worst+h.lmd.worst;h.total.expectation=h.exp.expectation+h.lmd.expectation;h.total.best=h.exp.best+h.lmd.best;a={};a.sanity=h;a.stage=d;a.required=g;a.consumption=c;return a},getFormData=function(){var a={};a.rarity=Number($("#rarity").val());a.from={};a.from.elite=Number($("#from_elite").val());
a.from.level=Number($("#from_level").val());0>=a.from.level&&(a.from.level=1);a.from.exp=Number($("#from_exp").val());a.to={};a.to.elite=Number($("#to_elite").val());a.to.level=Number($("#to_level").val());0==a.to.level&&(a.to.level=1);a.to.exp=Number($("#to_exp").val());a.resource={};a.resource.exp=Number($("#resource_expCard_tier1").val())*db.oplv.expCard.tier_1;a.resource.exp+=Number($("#resource_expCard_tier2").val())*db.oplv.expCard.tier_2;a.resource.exp+=Number($("#resource_expCard_tier3").val())*
db.oplv.expCard.tier_3;a.resource.exp+=Number($("#resource_expCard_tier4").val())*db.oplv.expCard.tier_4;a.resource.lmd=Number($("#resource_lmd").val());a.stage={};a.stage.exp=$("#stage_exp").val();a.stage.lmd=$("#stage_lmd").val();return a},showToast=function(a){console.log(a);$(".toast").html(a);$(".toast").addClass("show");setTimeout(function(){$(".toast").removeClass("show")},1600)},copyResult=function(a){gtag("event","\uacb0\uacfc \ubcf5\uc0ac",{event_category:"\ub808\ubca8\ub9c1 \uacc4\uc0b0\uae30"});
var b=$(".result-panel").text();console.log(b);var c=document.createElement("textArea");$(c).css("position","fixed");$(c).css("top","0");$(c).css("left","0");$(c).attr("id","tempTextArea");$(c).val(b);$("body").append(c);c.focus();c.select();try{document.execCommand("copy"),showTooltip("\uc131\uacf5\uc801\uc73c\ub85c \ubcf5\uc0ac\ud558\uc600\uc2b5\ub2c8\ub2e4",a.target,"success")}catch(f){console.error(f),showTooltip("\ubcf5\uc0ac\uc5d0 \uc2e4\ud328\ud558\uc600\uc2b5\ub2c8\ub2e4",a.target,"error")}document.body.removeChild(c)},
showTooltip=function(a,b,c){b=$(b);var f=$(document.createElement("div"));f.addClass("tooltip "+c).text(a).prependTo(b.parent());a=b.offset();a.left+=(b.innerWidth()-f.innerWidth())/2;a.top-=f.height()+parseInt(f.css("margin-top"),10)+parseInt(f.css("margin-bottom"),10)+parseInt(f.css("border-bottom-width"),10)+parseInt(f.css("border-top-width"),10)+parseInt($("body").css("font-size"),10);f.offset(a);var g=function(d){d.css("opacity","0");setTimeout(function(){d.remove()},300)};setTimeout(function(){g(f)},
1E3)},showResult=function(){gtag("event","\uacb0\uacfc \ud45c\uc2dc",{event_category:"\ub808\ubca8\ub9c1 \uacc4\uc0b0\uae30"});var a=getFormData();a=calc(a);var b='<div class="panel result-panel"><br><div class="result-panel-subtitle">\uae30\ub300\uce58 \u25b8 <span class="tag result-item">'+(String(a.sanity.total.expectation)+" \uc774\uc131</span><br>\n");b=b+'</div><hr class="dotted"><span style="color: #777">\uacbd\ud5d8\uce58</span> '+(a.stage.exp.name+' \u25b8 <span class="tag result-item">'+
a.stage.exp.expectation+"\ud68c \ud074\ub9ac\uc5b4</span><br>\n");b+='<span style="color: #777">\uc6a9\ubb38\ud3d0</span> '+a.stage.lmd.name+' \u25b8 <span class="tag result-item">'+a.stage.lmd.expectation+"\ud68c \ud074\ub9ac\uc5b4</span><br>\n\n";b+="</div>";if(a.stage.exp.best!=a.stage.exp.expectation||a.stage.lmd.best!=a.stage.lmd.expectation)b=b+'<div class="panel result-panel" style="color: #1c70b0"><br><div class="result-panel-subtitle">\ucd5c\uc18c\uce58 \u25b8 <span class="tag result-item">'+
(String(a.sanity.total.best)+" \uc774\uc131</span><br>\n"),b=b+'</div><hr class="dotted"><span style="color: #777">\uacbd\ud5d8\uce58</span> '+(a.stage.exp.name+' \u25b8 <span class="tag result-item">'+a.stage.exp.best+"\ud68c \ud074\ub9ac\uc5b4</span><br>\n"),b+='<span style="color: #777">\uc6a9\ubb38\ud3d0</span> '+a.stage.lmd.name+' \u25b8 <span class="tag result-item">'+a.stage.lmd.best+"\ud68c \ud074\ub9ac\uc5b4</span><br>\n\n",b+="</div>";if(a.stage.exp.worst!=a.stage.exp.expectation||a.stage.lmd.worst!=
a.stage.lmd.expectation)b=b+'<div class="panel result-panel" style="color: #c70808"><br><div class="result-panel-subtitle">\ucd5c\ub300\uce58 \u25b8 <span class="tag result-item">'+(String(a.sanity.total.worst)+" \uc774\uc131</span><br>\n"),b=b+'</div><hr class="dotted"><span style="color: #777">\uacbd\ud5d8\uce58</span> '+(a.stage.exp.name+' \u25b8 <span class="tag result-item">'+a.stage.exp.worst+"\ud68c \ud074\ub9ac\uc5b4</span><br>\n"),b+='<span style="color: #777">\uc6a9\ubb38\ud3d0</span> '+
a.stage.lmd.name+' \u25b8 <span class="tag result-item">'+a.stage.lmd.worst+"\ud68c \ud074\ub9ac\uc5b4</span><br>\n\n",b+="</div>";b=b+'<br><div class="panel result-panel"><br><span style="color: #888">\uc815\uc608\ud654 \ube44\uc6a9\uae4c\uc9c0 \ubc18\uc601\ub41c \uacb0\uacfc\uc785\ub2c8\ub2e4.</span><br><br>\n\n\ud544\uc694 \uacbd\ud5d8\uce58 \ud569\uacc4 \u25b8 <span class="tag result-item">'+(String(a.required.exp)+" Exp.</span><br>\n");b+='\ud544\uc694 \uc6a9\ubb38\ud3d0 \ud569\uacc4 \u25b8 <span class="tag result-item">'+
String(a.required.lmd)+" LMD</span><br>\n";b=b+'<br>\n\uc18c\ubaa8 \uacbd\ud5d8\uce58 \ud569\uacc4 \u25b8 <span class="tag result-item">'+(String(a.consumption.exp)+" Exp.</span><br>\n");b+='\uc18c\ubaa8 \uc6a9\ubb38\ud3d0 \ud569\uacc4 \u25b8 <span class="tag result-item">'+String(a.consumption.lmd)+" LMD</span><br>\n";b+="<br></div>";$("#result-panel").html(b)},getMaxLevel=function(a,b){return db.oplv.maxLevel["elite_"+a][b-1]};var fixCurrentLevelToMax=!1,fixTargetLevelToMax=!1;
const btnClicked=function(a){a=$(a).attr("name");"fix-current-level-to-max-btn"==a&&(gtag("event","\ucd5c\ub300 \ub808\ubca8 \uace0\uc815",{event_category:"\ub808\ubca8\ub9c1 \uacc4\uc0b0\uae30"}),(fixCurrentLevelToMax=!fixCurrentLevelToMax)?($('[name="fix-current-level-to-max-btn"]').addClass("checked"),setCurrentLevelToMax()):($('[name="fix-current-level-to-max-btn"]').removeClass("checked"),$("#from_level").val("1")),$("#from_level").trigger("change"));"fix-target-level-to-max-btn"==a&&(gtag("event",
"\ucd5c\ub300 \ub808\ubca8 \uace0\uc815",{event_category:"\ub808\ubca8\ub9c1 \uacc4\uc0b0\uae30"}),(fixTargetLevelToMax=!fixTargetLevelToMax)?($('[name="fix-target-level-to-max-btn"]').addClass("checked"),setTargetLevelToMax()):($('[name="fix-target-level-to-max-btn"]').removeClass("checked"),$("#to_level").val("1")),$("#to_level").trigger("change"));"show-detail-info-panel-btn"==a&&(gtag("event","\uc0c1\uc138 \uc815\ubcf4 \uc785\ub825\ub780 \ud45c\uc2dc",{event_category:"\ub808\ubca8\ub9c1 \uacc4\uc0b0\uae30"}),
$("#detail-info-panel").css("display","block"),$(".hide-detail-info-panel-btn").css("display","inline-block"),$(".show-detail-info-panel-btn").css("display","none"));"hide-detail-info-panel-btn"==a&&(gtag("event","\uc0c1\uc138 \uc815\ubcf4 \uc785\ub825\ub2e8 \uc228\uae40",{event_category:"\ub808\ubca8\ub9c1 \uacc4\uc0b0\uae30"}),$("#detail-info-panel").css("display","none"),$(".hide-detail-info-panel-btn").css("display","none"),$(".show-detail-info-panel-btn").css("display","inline-block"))},setCurrentLevelToMax=
function(){var a=getFormData();a=getMaxLevel(a.from.elite,a.rarity);$("#from_level").val(a)},setTargetLevelToMax=function(){var a=getFormData();a=getMaxLevel(a.to.elite,a.rarity);$("#to_level").val(a)};
$(document).ready(function(){$("*").change(function(){if($(this).is($("#rarity"))){var a=getFormData(),b=a.rarity,c=a.from.elite,f=a.to.elite;$("#to_elite option").attr("disabled","disabled").siblings().removeAttr("disabled");$("#from_elite option").attr("disabled","disabled").siblings().removeAttr("disabled");if(3>=b){var g=c,d=f;$('#from_elite option[value="2"]').attr("disabled","disabled");$('#to_elite option[value="2"]').attr("disabled","disabled");2<=g&&($('#from_elite option[value="1"]').prop("selected",
!0),c=1);2<=d&&($('#to_elite option[value="1"]').prop("selected",!0),f=1)}2>=b&&(g=c,d=f,$('#from_elite option[value="1"]').attr("disabled","disabled"),$('#to_elite option[value="1"]').attr("disabled","disabled"),1<=g&&($('#from_elite option[value="0"]').prop("selected",!0),c=0),1<=d&&($('#to_elite option[value="0"]').prop("selected",!0),f=0));c=getMaxLevel(c,b);b=getMaxLevel(f,b);a.from.level>c&&$("#from_level").val(c);a.to.level>b&&$("#to_level").val(b)}fixCurrentLevelToMax&&setCurrentLevelToMax();
fixTargetLevelToMax&&setTargetLevelToMax();showResult()})});
