var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};
$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var e=a.split(".");a=1===e.length;d=e[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<e.length-1;f++){var g=e[f];if(!(g in d))return;d=d[g]}e=e[e.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[e]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+e,e=
$jscomp.propertyToPolyfillSymbol[e],$jscomp.defineProperty(d,e,{configurable:!0,writable:!0,value:b})))};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var c=0,d=function(a){if(this instanceof d)throw new TypeError("Symbol is not a constructor");return new b("jscomp_symbol_"+(a||"")+"_"+c++,a)};return d},"es6","es3");$jscomp.initSymbolIterator=function(){};
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=$jscomp.global[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&$jscomp.defineProperty(d.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.initSymbolAsyncIterator=function(){};$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,b){a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};
$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
function dataMigration(){if(confirm('\ub370\uc774\ud130\ub97c \ub0b4\ubcf4\ub0b4\ub824\uba74 "\ud655\uc778" \ubc84\ud2bc\uc744,\n\ub370\uc774\ud130\ub97c \ubd88\ub7ec\uc624\ub824\uba74 "\ucde8\uc18c" \ubc84\ud2bc\uc744 \ub20c\ub7ec\uc8fc\uc138\uc694.')){var a=new Blob([JSON.stringify(localStorage)],{type:"text/plain;charset=utf-8"}),b="minase_\uc124\uc815_\ub370\uc774\ud130_"+(new Date).toISOString().replace(/:/g,"-")+".txt";saveAs(a,b)}else if(confirm('\uc8fc\uc758: \uc774 \uc791\uc5c5\uc744 \uc218\ud589\ud558\uba74 \uae30\uc874 \ub370\uc774\ud130\ub294 \uc0ad\uc81c\ub429\ub2c8\ub2e4.\n\uc815\ub9d0 \ub370\uc774\ud130\ub97c \ubd88\ub7ec\uc624\uc2dc\ub824\uba74 "\ud655\uc778" \ubc84\ud2bc\uc744 \ub20c\ub7ec\uc8fc\uc138\uc694.'))if(a=
prompt("\uc5ec\uae30\uc5d0 \ub370\uc774\ud130\ub97c \ubd99\uc5ec\ub123\uc73c\uc138\uc694.")){try{a=JSON.parse(a)}catch(h){alert("\uc785\ub825\ub41c \ub370\uc774\ud130\uac00 \uc815\uc0c1\uc801\uc774\uc9c0 \uc54a\uc2b5\ub2c8\ub2e4.\n\ubd88\ub7ec\uc624\uae30 \uc791\uc5c5\uc744 \ucde8\uc18c\ud558\uace0 \uae30\uc874 \ub370\uc774\ud130\ub97c \uadf8\ub300\ub85c \uc720\uc9c0\ud569\ub2c8\ub2e4.");return}var c={mcalc_:"\uc7ac\ub8cc \uacc4\uc0b0\uae30",recr_:"\uacf5\uac1c\ubaa8\uc9d1 \uacc4\uc0b0\uae30",optotal_:"\uc721\uc131 \uc790\uc6d0 \uacc4\uc0b0\uae30",
oplv_:"\ub808\ubca8 \uacc4\uc0b0\uae30"},d={};Object.keys(c).forEach(function(a){return d[a]=!1});b=[];for(var e in a)for(var f in c)!d[f]&&0<=e.indexOf(f)&&(d[f]=!0,b.push(c[f]));c=Object.keys(localStorage);for(f in d)if(d[f])for(var g=0;g<c.length;++g)0<=c[g].indexOf(f)&&localStorage.removeItem(c[g]);for(e in a)localStorage.setItem(e,a[e]);alert("\ub370\uc774\ud130 \ubd88\ub7ec\uc624\uae30\ub97c \uc644\ub8cc\ud558\uc600\uc2b5\ub2c8\ub2e4.\n\uc601\ud5a5\uc744 \ubc1b\uc740 \uc11c\ube44\uc2a4: "+b.join(", "))}else alert("\ub370\uc774\ud130 \ubd88\ub7ec\uc624\uae30\ub97c \ucde8\uc18c\ud558\uc600\uc2b5\ub2c8\ub2e4.");
else alert("\ub370\uc774\ud130 \ubd88\ub7ec\uc624\uae30\ub97c \ucde8\uc18c\ud558\uc600\uc2b5\ub2c8\ub2e4.")}document.querySelector("#data-migration").addEventListener("click",function(a){dataMigration()});
