var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){if(a==Array.prototype||a==Object.prototype)return a;a[b]=d.value;return a};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var d=a[b];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var d=$jscomp.propertyToPolyfillSymbol[b];if(null==d)return a[b];d=a[d];return void 0!==d?d:a[b]};
$jscomp.polyfill=function(a,b,d,c){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,d,c):$jscomp.polyfillUnisolated(a,b,d,c))};$jscomp.polyfillUnisolated=function(a,b,d,c){d=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var e=a[c];if(!(e in d))return;d=d[e]}a=a[a.length-1];c=d[a];b=b(c);b!=c&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,d,c){var e=a.split(".");a=1===e.length;c=e[0];c=!a&&c in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<e.length-1;f++){var m=e[f];if(!(m in c))return;c=c[m]}e=e[e.length-1];d=$jscomp.IS_SYMBOL_NATIVE&&"es6"===d?c[e]:null;b=b(d);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==d&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+e,e=
$jscomp.propertyToPolyfillSymbol[e],$jscomp.defineProperty(c,e,{configurable:!0,writable:!0,value:b})))};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var d=0,c=function(a){if(this instanceof c)throw new TypeError("Symbol is not a constructor");return new b("jscomp_symbol_"+(a||"")+"_"+d++,a)};return c},"es6","es3");$jscomp.initSymbolIterator=function(){};
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),d=0;d<b.length;d++){var c=$jscomp.global[b[d]];"function"===typeof c&&"function"!=typeof c.prototype[a]&&$jscomp.defineProperty(c.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.initSymbolAsyncIterator=function(){};$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,b){a instanceof String&&(a+="");var d=0,c={next:function(){if(d<a.length){var e=d++;return{value:b(e,a[e]),done:!1}}c.next=function(){return{done:!0,value:void 0}};return c.next()}};c[Symbol.iterator]=function(){return c};return c};
$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
var itemOrder=[["\ucee8\ub514\uc158","\ub4dc\ub860"],["\uacbd\ud5d8\uce58","\uc6a9\ubb38\ud3d0"],["\uace0\uae09\uc99d\uba85\uc11c","\uad6c\ub9e4\uc99d\uba85\uc11c","\uc790\uaca9\uc99d\uba85\uc11c"],["\uc6a9\uace8","\uac00\uad6c \ubd80\ud488"],"\uace0\uae09\uac74\uc124\uc790\uc7ac;\uc911\uae09\uac74\uc124\uc790\uc7ac;\ucd08\uae09\uac74\uc124\uc790\uc7ac;\uce74\ubcf8 \ud329;\uce74\ubcf8 \ubc88\ub4e4;\uce74\ubcf8".split(";"),["\uace0\uae09\uc791\uc804\uae30\ub85d","\uc911\uae09\uc791\uc804\uae30\ub85d",
"\ucd08\uae09\uc791\uc804\uae30\ub85d","\uae30\ucd08\uc791\uc804\uae30\ub85d"],["\uc2a4\ud0ac\uac1c\ub860 \uc81c3\uad8c","\uc2a4\ud0ac\uac1c\ub860 \uc81c2\uad8c","\uc2a4\ud0ac\uac1c\ub860 \uc81c1\uad8c"],"\uce69 \ucca8\uac00\uc81c;\ubc45\uac00\ub4dc \ub4c0\uc5bc \uce69;\uac00\ub4dc \ub4c0\uc5bc \uce69;\ub514\ud39c\ub354 \ub4c0\uc5bc \uce69;\uc2a4\ub098\uc774\ud37c \ub4c0\uc5bc \uce69;\uce90\uc2a4\ud130 \ub4c0\uc5bc \uce69;\uba54\ub515 \ub4c0\uc5bc \uce69;\uc11c\ud3ec\ud130 \ub4c0\uc5bc \uce69;\uc2a4\ud398\uc15c\ub9ac\uc2a4\ud2b8 \ub4c0\uc5bc \uce69;\ubc45\uac00\ub4dc \uce69\uc14b;\uac00\ub4dc \uce69\uc14b;\ub514\ud39c\ub354 \uce69\uc14b;\uc2a4\ub098\uc774\ud37c \uce69\uc14b;\uce90\uc2a4\ud130 \uce69\uc14b;\uba54\ub515 \uce69\uc14b;\uc11c\ud3ec\ud130 \uce69\uc14b;\uc2a4\ud398\uc15c\ub9ac\uc2a4\ud2b8 \uce69\uc14b;\ubc45\uac00\ub4dc \uce69;\uac00\ub4dc \uce69;\ub514\ud39c\ub354 \uce69;\uc2a4\ub098\uc774\ud37c \uce69;\uce90\uc2a4\ud130 \uce69;\uba54\ub515 \uce69;\uc11c\ud3ec\ud130 \uce69;\uc2a4\ud398\uc15c\ub9ac\uc2a4\ud2b8 \uce69".split(";"),
["D32\uac15","\ubc14\uc774\ud3f4\ub77c \ub098\ub178\ud50c\ub808\uc774\ud06c \uce69","\uc911\ud569\uc81c","\ud06c\ub9ac\uc2a4\ud0c8 \uc804\uc790 \uc720\ub2db"],"RMA70-24;\ub9dd\uac04 \uc911\ud569\uccb4;\ud654\uc774\ud2b8 \ud638\uc2a4 \ucf5c;\uace0\uae09 \uc5f0\ub9c8\uc11d;\uc911\ud569\uc824;\uc5f4\ud569\uae08 \ud329;\ud06c\ub9ac\uc2a4\ud0c8 \ud68c\ub85c;RMA70-12;\ub9dd\uac04 \uad11\uc11d;\ub85c\uc2dd \ucf5c;\uc5f0\ub9c8\uc11d;\uc824;\uc5f4\ud569\uae08;\ud06c\ub9ac\uc2a4\ud0c8 \uc18c\uc790".split(";"),
"\ud3ec\ub3c4\ub2f9 \ud329;\ud3f4\ub9ac\uc5d0\uc2a4\ud14c\ub974 \ud329;\uac1c\ub7c9 \uc7a5\uce58;\uc815\uc81c \uc6d0\uc554;\uc544\ucf00\ud1a4 \ud329;\uc774\ucca0 \ud329;\ud3ec\ub3c4\ub2f9 \ubc88\ub4e4;\ud3f4\ub9ac\uc5d0\uc2a4\ud14c\ub974 \ubc88\ub4e4;\ub9ac\ub274\uc5bc \uc7a5\uce58;\uc6d0\uc554 \ud050\ube0c \ubc88\ub4e4;\uc544\ucf00\ud1a4 \uc751\uc9d1\uccb4 \ubc88\ub4e4;\uc774\ucca0 \ubc88\ub4e4;\ud3ec\ub3c4\ub2f9;\ud3f4\ub9ac\uc5d0\uc2a4\ud14c\ub974;\uc7a5\uce58;\uc6d0\uc554 \ud050\ube0c;\uc544\ucf00\ud1a4 \uc751\uc9d1\uccb4;\uc774\ucca0;\ub300\uccb4\ub2f9;\uc5d0\uc2a4\ud14c\ub974 \uc6d0\ub8cc;\ud30c\uc190\ub41c \uc7a5\uce58;\uc6d0\uc554;\ub514\ucf00\ud1a4;\uc774\ucca0 \uc870\uac01".split(";")],
getGroupIdx=function(a){for(var b=db.item[a].name.kr,d=0;d<itemOrder.length;++d)if(0<=itemOrder[d].indexOf(b))return d;console.log("\uc5d0\ub7ec: \uadf8\ub8f9 \uc778\ub371\uc2a4\ub97c \ucc3e\uc744 \uc218 \uc5c6\uc74c: ",b,a);return-1},showDetailedResult=function(){$("#result-container #detailed-result").css("display","block");$("#result-container .show-detailed-result").css("display","none");$("#result-container .hide-detailed-result").css("display","inline-block")},hideDetailedResult=function(){$("#result-container #detailed-result").css("display",
"none");$("#result-container .show-detailed-result").css("display","inline-block");$("#result-container .hide-detailed-result").css("display","none")},toImg=function(a,b,d){d=void 0===d?!1:d;var c=getItemIDByKRName(a),e=' class="result-item-container',f="";0<=c&&(0<db.item[c].craft.length&&(e+=" clickable"),f+=' name="item_'+c+'"');c="<div"+(e+'"')+f+'><img src="./images/item/t/'+(a+'.png" alt="'+a+'"><div class="result-item-quantity');d?c+=" small":"\uc6a9\ubb38\ud3d0"===a&&(c+=" small");c+='">';
c+=decimalComma(String(b));c+="</div>";c+='<span class="result-item-name">';c+=a;c+="</span>";return c+="</div> "},makeResultHtml=function(a){for(var b="",d=0;d<a.IDs.length;++d){var c=a.IDs[d];b+=toImg(db.item[c].name.kr,a[c])}return b},makeResultHtmlByGroup=function(a){for(var b=' <div class="result-group">',d=-1,c=0;c<a.IDs.length;++c){var e=a.IDs[c],f=getGroupIdx(e);-1==f&&console.log("\uc5d0\ub7ec: \uadf8\ub8f9 \uc778\ub371\uc2a4\ub97c \ucc3e\uc744 \uc218 \uc5c6\uc74c: ",db.item[e].name.kr,e);
0<c&&d!=f&&(b+='</div> <br><br> <div class="result-group">');b+=toImg(db.item[e].name.kr,a[e]);d=f}return b+"</div> "},getItemIDByKRName=function(a){for(var b=0,d=db.item.keys.length,c;b<d;++b)if(c=db.item.keys[b],db.item[c].name.kr===a)return b;return-1},decimalComma=function(a){a=a.toString();var b=a.length%3;var d=0<b?[a.slice(0,b)]:[];for(var c=a.length;b<c;b+=3)d.push(a.slice(b,b+3));return d.join(",")},tt=function(a){var b='<hr class="main-line"><span class="result-maintitle">\ud569\uacc4</span><br><hr class="sub-line"><span class="result-subtitle">\uacbd\ud5d8\uce58, \uc6a9\ubb38\ud3d0</span><hr> <div style="margin-top: 2px; display: inline-block; border: none; width: 100%; text-align: center">'+
toImg("\uacbd\ud5d8\uce58",a.total.exp,!0);b+=toImg("\uc6a9\ubb38\ud3d0",a.total.lmd,!0);var d=db.oplv.stage.exp["LS-5"].sanity,c=Math.ceil(a.total.exp/db.oplv.stage.exp["LS-5"].reward.expectation),e=db.oplv.stage.lmd["CE-5"].sanity,f=Math.ceil(a.total.lmd/db.oplv.stage.lmd["CE-5"].reward.expectation);b=b+'</div><br><div style="margin-top: 8px; margin-bottom: 8px; width: 100%; font-size: 10px; text-align: center">\u25bc</div> <div class="result-exp-lmd-container"><div class="result-exp-lmd"><span style="color: #777; font-size: 15px">\uacbd\ud5d8\uce58</span> LS-5 \u25b8 <span class="tag stage-guide-item">'+
(decimalComma(c)+"\ud68c \ud074\ub9ac\uc5b4</span>");b=b+'</span><br><span style="color: #777; font-size: 15px">\uc6a9\ubb38\ud3d0</span> CE-5 \u25b8 <span class="tag stage-guide-item">'+(decimalComma(f)+"\ud68c \ud074\ub9ac\uc5b4</span>");b=b+'</span><br><span style="color: #777; font-size: 15px">\uacbd\ud5d8\uce58+\uc6a9\ubb38\ud3d0</span> \u25b8 <span class="tag stage-guide-item">'+(decimalComma(c*d+f*e)+"\uc774\uc131 \uc18c\ubaa8</span>");b=b+'</span><br></div></div> <br><br><hr class="sub-line"><span class="result-subtitle">\uc815\uc608\ud654 \ubc0f \uc2a4\ud0ac\uac15\ud654 \uc7ac\ub8cc</span><hr>'+
makeResultHtmlByGroup(a.total);b=b+'<hr><button type="button" class="show-detailed-result" onclick="showDetailedResult()">\uc138\ubd80 \uacb0\uacfc \ubcf4\uc774\uae30</button><button type="button" class="hide-detailed-result" onclick="hideDetailedResult()" style="display: none">\uc138\ubd80 \uacb0\uacfc \uc228\uae30\uae30</button><div id="detailed-result" style="display:none"><hr class="sub-line"><span class="result-subtitle">\uc624\ud37c\ub808\uc774\ud130 \ub808\ubca8\ub9c1 \ube44\uc6a9<br>(\uc815\uc608\ud654 \ube44\uc6a9 \uc81c\uc678)</span><hr> <div class="result-group">'+
toImg("\uacbd\ud5d8\uce58",a.total.exp,!0);b+=toImg("\uc6a9\ubb38\ud3d0",a.opLeveling.lmd,!0);b=b+'</div> <hr><hr class="sub-line"><span class="result-subtitle">\uc815\uc608\ud654 \uc7ac\ub8cc</span><hr>'+makeResultHtmlByGroup(a.elitePromotion);b=b+'<hr><hr class="sub-line"><span class="result-subtitle">\uc2a4\ud0ac\uac15\ud654 \uc7ac\ub8cc</span><hr>'+makeResultHtmlByGroup(a.skillLeveling);return b+'<hr></div><button type="button" class="hide-detailed-result" onclick="hideDetailedResult()" style="display: none">\uc138\ubd80 \uacb0\uacfc \uc228\uae30\uae30</button><hr style="border-top-color: #777; border-top-width: 3px;">'},
doNotRefreshResult=!1,showt=0,mshow=[],showResult=function(){if(!0!==doNotRefreshResult){showt=Date.now();var a=fetchInputData();mshow.push(Date.now()-showt);if(!1===a)return $("#result-container").html('<div id="result-guide"><hr class="main-line"><span class="result-maintitle" style="display: inline-block; width: 100%; text-align: left">\ud569\uacc4</span><br><br>\uc5ec\uae30\uc5d0 \uacb0\uacfc\uac00 \ud45c\uc2dc\ub429\ub2c8\ub2e4.</div>'),!1;showt=Date.now();a=calc(a);mshow.push(Date.now()-showt);
showt=Date.now();sortResultData(a);mshow.push(Date.now()-showt);showt=Date.now();a=tt(a);mshow.push(Date.now()-showt);showt=Date.now();document.getElementById("result-container").innerHTML=a;mshow.push(Date.now()-showt)}},fetchInputData=function(){var a={opIDs:[]},b=document.querySelectorAll('.op[name*="op_"]');if(0===b.length)return!1;for(var d=0,c=b.length;d<c;++d){var e=b[d],f=e.getAttribute("name").split("_")[1],m={},k={},h={};null===db.op[f].elite?k=m=!1:(m.current=Number(e.querySelector(".current-elite").value),
m.target=Number(e.querySelector(".target-elite").value),k.current=Number(e.querySelector(".current-op-level").value),k.target=Number(e.querySelector(".target-op-level").value));if(null===db.op[f].skill)h=!1;else{var n=e.querySelectorAll(".current-skill-level"),g=e.querySelectorAll(".target-skill-level"),p=0;g.forEach(function(a){a.disabled||++p});if(0<p){var l=[];for(e=0;e<p;++e)l[e]={},l[e].current=Number(n[e].value),l[e].target=Number(g[e].value);h.common={};h.common.current=7<l[0].current?7:l[0].current;
h.common.target=7<l[0].target?7:l[0].target;h.mastery={};for(e=0;e<p;++e)h.mastery[e]={};for(e=0;e<p;++e)n=l[e].current-7,h.mastery[e].current=0<n?n:0,n=l[e].target-7,h.mastery[e].target=0<n?n:0;l=!0;h.common.current!=h.common.target&&(l=!1);if(l){for(e=0;e<p;++e)if(h.mastery[e].current!=h.mastery[e].target){l=!1;break}l&&(h=!1)}}else h=!1}a.opIDs.push(f);a[f]={};a[f].elite=m;a[f].opLevel=k;a[f].skillLevel=h}return a},sortResultData=function(a){var b=function(a,b){var c,d;a=db.item[a].name.kr;var m=
db.item[b].name.kr;var k=b=d=c=-1;for(var h=0,n=itemOrder.length,g;h<n;++h)if(g=itemOrder[h].indexOf(a),0<=g){c=h;d=g;break}h=0;for(n=itemOrder.length;h<n;++h)if(g=itemOrder[h].indexOf(m),0<=g){b=h;k=g;break}-1!=c&&-1!=d||console.error(a,"\uc6b0\uc120\ub3c4 \uc624\ub958:",c,d);-1!=b&&-1!=k||console.error(m,"\uc6b0\uc120\ub3c4 \uc624\ub958:",b,k);return c<b?-1:b<c?1:d<k?-1:1};a.skillLeveling.IDs.sort(b);a.elitePromotion.IDs.sort(b);a.total.IDs.sort(b);return a},getMaxLevel=function(a,b){return Number(db.oplv.maxLevel["elite_"+
a][b-1])},levelingCalc=function(a){for(var b=db.oplv.leveling.expTable,d=db.oplv.leveling.lmdTable,c,e,f=e=c=0;f<a.target.elite;++f)c+=b["elite_"+String(f)][getMaxLevel(f,a.rarity)-1];c+=b["elite_"+String(a.target.elite)][a.target.level-1];c+=a.target.exp;for(f=0;f<a.target.elite;++f)e+=d["elite_"+String(f)][getMaxLevel(f,a.rarity)-1];e+=d["elite_"+String(a.target.elite)][a.target.level-1];if(a.target.level<getMaxLevel(a.target.elite,a.rarity)){f=d["elite_"+String(a.target.elite)][a.target.level];
f-=d["elite_"+String(a.target.elite)][a.target.level-1];var m=b["elite_"+String(a.target.elite)][a.target.level];m-=b["elite_"+String(a.target.elite)][a.target.level-1];e+=Math.ceil(f/m*a.target.exp)}var k,h;for(f=h=k=0;f<a.current.elite;++f)k+=b["elite_"+String(f)][getMaxLevel(f,a.rarity)-1];k+=b["elite_"+String(a.current.elite)][a.current.level-1];k+=a.current.exp;for(f=0;f<a.current.elite;++f)h+=d["elite_"+String(f)][getMaxLevel(f,a.rarity)-1];h+=d["elite_"+String(a.current.elite)][a.current.level-
1];a.current.level<getMaxLevel(a.current.elite,a.rarity)&&(f=d["elite_"+String(a.current.elite)][a.current.level],f-=d["elite_"+String(a.current.elite)][a.current.level-1],m=b["elite_"+String(a.current.elite)][a.current.level],m-=b["elite_"+String(a.current.elite)][a.current.level-1],h+=Math.ceil(f/m*a.current.exp));a={};a.exp=c-k;a.lmd=e-h;a.exp=0>a.exp?0:a.exp;a.lmd=0>a.lmd?0:a.lmd;return a},calc=function(a){var b={opLeveling:{},skillLeveling:{},elitePromotion:{},total:{}};b.opLeveling.exp=0;for(var d=
b.opLeveling.lmd=0;d<a.opIDs.length;++d){var c=a.opIDs[d];if(!1!==a[c].opLevel){var e={};e.rarity=db.op[c].rarity;e.current={};e.current.elite=a[c].elite.current;e.current.level=a[c].opLevel.current;e.current.exp=0;e.target={};e.target.elite=a[c].elite.target;e.target.level=a[c].opLevel.target;e.target.exp=0;c=levelingCalc(e);b.opLeveling.exp+=c.exp;b.opLeveling.lmd+=c.lmd}}b.elitePromotion.IDs=[];d=0;for(e=a.opIDs.length;d<e;++d)if(c=a.opIDs[d],!1!==a[c].elite){var f=a[c].elite.current,m=a[c].elite.target;
if(f!=m)for(;f<m;++f){var k=[];try{k=db.op[c].elite[f]}catch(q){console.error(q);console.error("opID:",c,db.op[c]);return}for(var h=0,n=k.length;h<n;++h){var g=k[h][0],p=Number(k[h][1]);b.elitePromotion.hasOwnProperty(g)?b.elitePromotion[g]+=p:(b.elitePromotion[g]=p,b.elitePromotion.IDs.push(g))}}}b.skillLeveling.IDs=[];d=0;for(e=a.opIDs.length;d<e;++d)if(c=a.opIDs[d],!1!==a[c].skillLevel){m=Number(a[c].skillLevel.common.current);k=Number(a[c].skillLevel.common.target);for(f=m-1;f<k-1;++f){var l;
(l=db.op[c].skill.common[f])||console.log(l,"\n",db.op[c],f,m,k);h=0;for(n=l.length;h<n;++h)g=l[h][0],p=Number(l[h][1]),b.skillLeveling.hasOwnProperty(g)?b.skillLeveling[g]+=p:(b.skillLeveling[g]=p,b.skillLeveling.IDs.push(g))}n=Object.keys(a[c].skillLevel.mastery).length;for(f=0;f<n;++f)for(m=Number(a[c].skillLevel.mastery[f].target),h=Number(a[c].skillLevel.mastery[f].current);h<m;++h)for(k=db.op[c].skill.mastery[f][h],l=0;l<k.length;++l)g=k[l][0],p=Number(k[l][1]),b.skillLeveling.hasOwnProperty(g)?
b.skillLeveling[g]+=p:(b.skillLeveling[g]=p,b.skillLeveling.IDs.push(g))}b.total.exp=0;b.total.lmd=0;b.total.IDs=[];b.total.exp+=b.opLeveling.exp;b.total.lmd+=b.opLeveling.lmd;for(d=0;d<b.elitePromotion.IDs.length;++d)g=b.elitePromotion.IDs[d],"\uc6a9\ubb38\ud3d0"==db.item[g].name.kr?b.total.lmd+=b.elitePromotion[g]:b.total.hasOwnProperty(g)?b.total[g]+=b.elitePromotion[g]:(b.total[g]=b.elitePromotion[g],b.total.IDs.push(g));for(d=0;d<b.skillLeveling.IDs.length;++d)g=b.skillLeveling.IDs[d],"\uc6a9\ubb38\ud3d0"==
db.item[g].name.kr&&(b.total.lmd+=b.skillLeveling[g]),b.total.hasOwnProperty(g)?b.total[g]+=b.skillLeveling[g]:(b.total[g]=b.skillLeveling[g],b.total.IDs.push(g));return b};
