var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(a){return a.raw=a};$jscomp.createTemplateTagFirstArgWithRaw=function(a,b){a.raw=b;return a};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;$jscomp.polyfills={};
$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var c=$jscomp.propertyToPolyfillSymbol[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]};$jscomp.polyfill=function(a,b,c,d){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,c,d):$jscomp.polyfillUnisolated(a,b,c,d))};
$jscomp.polyfillUnisolated=function(a,b,c,d){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))return;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,c,d){var e=a.split(".");a=1===e.length;d=e[0];d=!a&&d in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var f=0;f<e.length-1;f++){var g=e[f];if(!(g in d))return;d=d[g]}e=e[e.length-1];c=$jscomp.IS_SYMBOL_NATIVE&&"es6"===c?d[e]:null;b=b(c);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,e,{configurable:!0,writable:!0,value:b}):b!==c&&($jscomp.propertyToPolyfillSymbol[e]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(e):$jscomp.POLYFILL_PREFIX+e,e=
$jscomp.propertyToPolyfillSymbol[e],$jscomp.defineProperty(d,e,{configurable:!0,writable:!0,value:b})))};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var c=0,d=function(a){if(this instanceof d)throw new TypeError("Symbol is not a constructor");return new b("jscomp_symbol_"+(a||"")+"_"+c++,a)};return d},"es6","es3");$jscomp.initSymbolIterator=function(){};
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=$jscomp.global[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&$jscomp.defineProperty(d.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.initSymbolAsyncIterator=function(){};$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,b){a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var e=c++;return{value:b(e,a[e]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};
$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
var providedConfigs=[{title:"\uc9c0\uc5ed \uc124\uc815",id:"locale",configs:[{title:"\uc11c\ubc84",id:"region",exclusive:!0,options:[{title:"\ud55c\uad6d",value:"kr",default:!0},{title:"\uc911\uad6d",value:"cn"},{title:"\uc77c\ubcf8",value:"jp"},{title:"\uae00\ub85c\ubc8c",value:"en"}]},{title:"\uc5b8\uc5b4",id:"lang",exclusive:!0,options:[{title:"\ud55c\uad6d\uc5b4",value:"kr",default:!0},{title:"\uc911\uad6d\uc5b4",value:"cn"},{title:"\uc77c\ubcf8\uc5b4",value:"jp"},{title:"\uc601\uc5b4",value:"en"}]}]},
{title:"\uc785\ub825 \uc124\uc815",id:"input",configs:[{title:"\ud0dc\uadf8 \uc785\ub825\uae30",id:"batchSelector",exclusive:!0,options:[{title:"\uc0ac\uc6a9",value:!0,default:!0},{title:"\ubbf8\uc0ac\uc6a9",value:!1}]},{title:"\ud0dc\uadf8 \ucd08\uae30\ud654 \ud6c4 \uc790\ub3d9 \ud3ec\ucee4\uc2a4",id:"autoFocusBatchSelector",exclusive:!0,options:[{title:"\uc0ac\uc6a9",value:!0},{title:"\ubbf8\uc0ac\uc6a9",value:!1,default:!0}]}]},{title:"\ud45c\uc2dc \uc124\uc815",id:"display",configs:[{title:"\uc774\ubbf8\uc9c0",
id:"image",exclusive:!0,options:[{title:"\uc5c6\uc74c",value:"none",default:!0},{title:"\ub9e4\uc6b0 \uc791\uac8c",value:"tiny"},{title:"\uc791\uac8c",value:"small"},{title:"\uc911\uac04",value:"medium"},{title:"\ud06c\uac8c",value:"large"}]},{title:"\uc774\ub984",id:"name",exclusive:!0,options:[{title:"\ud45c\uc2dc",value:!0,default:!0},{title:"\ube44\ud45c\uc2dc",value:!1}]},{title:"\ub808\uc5b4\ub3c4",id:"rarity",exclusive:!0,options:[{title:"\ud45c\uc2dc",value:!0,default:!0},{title:"\ube44\ud45c\uc2dc",
value:!1}]},{title:"\uac00\uc774\ub4dc \ud328\ub110",id:"guidePanel",exclusive:!0,options:[{title:"\ud45c\uc2dc",value:!0,default:!0},{title:"\ube44\ud45c\uc2dc",value:!1}]}]},{title:"\ud544\ud130 \uc124\uc815",id:"filter",configs:[{title:"\ud5c8\uc6a9 \ub808\uc5b4\ub3c4",id:"rarity",exclusive:!1,options:[{title:"1\uc131",value:1,default:!0},{title:"2\uc131",value:2,default:!0},{title:"3\uc131",value:3,default:!0},{title:"4\uc131",value:4,default:!0},{title:"5\uc131",value:5,default:!0},{title:"6\uc131",
value:6,default:!0}]}]}],saveToStorage=function(a,b){localStorage.setItem("recr_"+a,JSON.stringify(b))},loadFromStorage=function(a,b){b=void 0===b?null:b;a=localStorage.getItem("recr_"+a)||b;return null!==a?JSON.parse(a):{}},userConfig={},saveUserConfig=function(){saveToStorage("userConfig",userConfig)},loadUserConfig=function(){userConfig=loadFromStorage("userConfig");for(var a=0,b=providedConfigs.length;a<b;++a){var c=providedConfigs[a];userConfig[c.id]||(userConfig[c.id]={});for(var d=0,e=c.configs.length;d<
e;++d){var f=c.configs[d];if(void 0===userConfig[c.id][f.id]||void 0===userConfig[c.id][f.id].value){userConfig[c.id][f.id]={};!0===f.exclusive?userConfig[c.id][f.id].exclusive=!0:(userConfig[c.id][f.id].exclusive=!1,userConfig[c.id][f.id].value=[]);for(var g=0,h=f.options.length;g<h;++g)if(!0===f.options[g].default)if(!0===f.exclusive){userConfig[c.id][f.id].value=f.options[g].value;break}else userConfig[c.id][f.id].value.push(f.options[g].value)}}}},setConfigModal=function(){for(var a=document.createDocumentFragment(),
b=0,c=providedConfigs.length;b<c;++b){var d=providedConfigs[b],e=document.createElement("div");e.style.fontSize="90%";e.classList.add("user-config-category");e.dataset.id=d.id;e.innerHTML+='<hr style="border-color:#444;display:inline-block"><span style="font-size: 0.9em">'+d.title+"</span><br><br>";for(var f=0,g=d.configs.length;f<g;++f){var h=d.configs[f],k=document.createElement("div");k.classList.add("user-config-config");k.dataset.id=h.id;k.innerHTML+='<span style="font-size: 0.75em;color:#eee">'+
h.title+"</span><br>";for(var m=0,r=h.options.length;m<r;++m){var p=h.options[m],q=["user-config-",d.id,h.id,m.toString()].join("-"),l=document.createElement("input");l.classList.add("checkboxButton","user-config-option");l.dataset.value=JSON.stringify(p.value);l.setAttribute("id",q);l.setAttribute("name",h.id);!0===h.exclusive?l.setAttribute("type","radio"):l.setAttribute("type","checkbox");var n=document.createElement("label");n.className="tag";n.innerText=p.title;n.setAttribute("for",q);k.appendChild(l);
k.appendChild(n)}e.appendChild(k)}a.appendChild(e)}document.querySelector(".modal-body").appendChild(a)},selectUserConfig=function(){Object.keys(userConfig);for(var a=document.querySelectorAll(".user-config-option"),b=0;b<a.length;++b){var c=a[b],d=$jscomp.makeIterator(c.getAttribute("id").split("--")[1].split("-")),e=d.next().value,f=d.next().value;d=JSON.parse(c.dataset.value);if(userConfig[e]&&userConfig[e][f])if(!0===userConfig[e][f].exclusive&&d===userConfig[e][f].value)c.checked=!0;else{e=userConfig[e][f].value;
f=0;for(var g=e.length;f<g;++f)if(e[f]===d){c.checked=!0;break}}}},fetchUserConfig=function(){for(var a=Object.keys(userConfig),b=0,c=a.length;b<c;++b)for(var d=Object.keys(userConfig[a[b]]),e=0,f=d.length;e<f;++e)!1===userConfig[a[b]][d[e]].exclusive&&(userConfig[a[b]][d[e]].value=[]);a=document.querySelectorAll(".user-config-option:checked");b=0;for(c=a.length;b<c;++b)e=a[b],f=$jscomp.makeIterator(e.getAttribute("id").split("--")[1].split("-")),d=f.next().value,f=f.next().value,e=JSON.parse(e.dataset.value),
void 0===userConfig[d]&&(userConfig[d]={}),!0===userConfig[d][f].exclusive?userConfig[d][f].value=e:userConfig[d][f].value.push(e);saveUserConfig();loadUserConfig()},openConfigModal=function(){selectUserConfig();document.getElementById("config-modal").style.display="block";document.getElementById("config-modal").style.opacity="1"},checkBatchSelectorOption=function(){var a=document.getElementById("tagBatchSelector-container"),b=userConfig.input.batchSelector.value;console.log(b);a.style.display=!1===
b?"none":"block"},checkGuidePanelOption=function(){var a=document.querySelectorAll(".guide-panel");!1===userConfig.display.guidePanel.value?(a.forEach(function(a){a.style.display="none"}),$("#result-panel").prepend('<div class="panel"></div>')):a.forEach(function(a){a.style.display="block"})},closeConfigModal=function(){fetchUserConfig();checkBatchSelectorOption();checkGuidePanelOption();document.getElementById("tag-top").dataset.lang!=userConfig.locale.region.value&&configSelectionPanel();showResult();
document.getElementById("config-modal").style.opacity="0";setTimeout(function(){document.getElementById("config-modal").style.display="none"},300)};document.querySelector(".menu-btn").addEventListener("click",openConfigModal);document.querySelector(".close-btn").addEventListener("click",closeConfigModal);window.addEventListener("click",function(a){a.target.isSameNode(document.getElementById("config-modal"))&&closeConfigModal()});setConfigModal();loadUserConfig();checkBatchSelectorOption();checkGuidePanelOption();
var recrWhiteList={};recrWhiteList.en=recrWhiteList.jp=recrWhiteList.kr="A41 A42 A43 A44 AA02 AA03 BS02 BS03 BS04 FO01 FO02 FO03 GG01 GG03 HK01 IU04 IU05 JC01 JC03 JC05 JC06 KZ03 KZ04 LM05 LM10 LM11 LN01 LT05 MN02 MN03 PA11 PA12 PA13 PA14 PA15 PA41 PA42 PA43 PA44 PA61 PL02 PL03 PL04 R100 R104 R105 R106 R123 R303 RB02 RCX2 RCX3 RL01 RL02 RL03 RL04 RL05 SG01 SI01 SR03 ST01 ST02 ST03 SW01 SW02 USS1 USS2 USS3 VC02 VC04 YD01".split(" ");recrWhiteList.cn="A41 A42 A43 A44 AA01 AA02 AA03 BS02 BS03 BS04 FO01 FO02 FO03 GG01 GG03 HK01 IU04 IU05 JC01 JC03 JC05 JC06 KZ03 KZ04 LM04 LM05 LM08 LM10 LM11 LN01 LT05 MN02 MN03 PA11 PA12 PA13 PA14 PA15 PA41 PA42 PA43 PA44 PA61 PA62 PA63 PA64 PA65 PL02 PL03 PL04 R100 R104 R105 R106 R119 R123 R303 RB02 RCX2 RCX3 RCX4 RL01 RL02 RL03 RL04 RL05 SG01 SI01 SR03 ST01 ST02 ST03 SW01 SW02 US10 USS1 USS2 USS3 VC02 VC03 VC04 YD01".split(" ");
